- services/hanke-service/README.md
- services/hanke-service/build.gradle.kts
Swagger UI and OpenAPI v3 description with SpringDoc (https://springdoc.org/)
> Hai 67 rajapintakuvaus backendiin

- services/hanke-service/Dockerfile
- services/hanke-service/README.md
- services/hanke-service/build.gradle.kts
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hello/ActuatorEndpointITests.kt
- services/hanke-service/src/main/resources/application.properties
Added Spring Boot Actuator liveness and readiness probes for Kubernetes and general info endpoint
Gradle integration tests:
`$ ./gradlew :services:hanke-service:clean integrationTest`
Build and run for manual testing:
`$ ./gradlew :services:hanke-service:bootRun`
Readiness probe:
> http://localhost:8081/actuator/health/readiness
Liveness probe:
> http://localhost:8081/actuator/health/liveness
Info:
> http://localhost:8081/actuator/info
With Docker:
```
$ ./gradlew build
$ cd services/hanke-service
$ cp build/libs/hanke-service-0.0.1-SNAPSHOT.jar .
$ docker build . -t hanke-service:0.0.1-SNAPSHOT
$ docker run -p 8080:8080 -p 8081:8081 hanke-service:0.0.1-SNAPSHOT
```
Urls for testing are the same as above.
or other location: not yet - will have to add info about the probe urls on IBM Jira …
> Hai 90 readiness and liveness probes

- scripts/docker-postgres/configure-database.sh
Created postgis extension for test db. 
Instructions for testing:
1. Delete containers
2. Rebuild container db with
`docker-compose docker-compose --env-file .env.local up db
`
3. Login to psql and validate that extension exists:
```
psql -U postgres -d haitaton -h 127.0.0.1 -p 5432
select * from pg_extension;
```
> HAI-221 added postgis extension to docker

- scripts/docker-postgres/configure-database.sh
- services/hanke-service/src/main/resources/application.properties
As per request from ibm to azure, also added the db name to env variables. In addition added if exists to postgis extension creation since noticed it was lacking (and docker-compose up fails if you try to add it to already existing db).
> HAI-256added haitaton db to env variables

- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/ActuatorEndpointITests.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/HankeControllerITests.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/HankeGeometriaControllerITests.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/HankeRepositoryITests.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/HankeRepositoryTests.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/hello/HelloApiControllerITests.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/Configuration.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/Domain.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/HankeController.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/HankeService.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/HankeServiceImpl.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/Persistence.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/Utils.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/validation/HankeValidator.kt
- services/hanke-service/src/main/resources/application.properties
- services/hanke-service/src/main/resources/db/changelog/changesets/create-initial-tables.yml
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/HankeControllerTest.kt
Adding Liquibase master file, first changeset, JPA/Hibernate based entity and mappings to database fields, proper HankeService implementation, and changes to controllers and tests to accommodate these changes. Covers the first page data, and some meta-data for Hanke.
HAI-61
HAI-202
See README.md how to build with unit and integration tests.
The swagger UI can be used to test and investigate the API (if the service and database is running).
https://helsinkisolutionoffice.atlassian.net/wiki/spaces/HAI/pages/981696609/Hanke+API+UI+lle
https://helsinkisolutionoffice.atlassian.net/wiki/spaces/HAI/pages/939262392/Hanke
API change: Most field/parameter names were changed (to Finnish), and many new fields have been added. The requests for saving/submitting Hanke data must now …
> HAI-61 and HAI-202 liquibase base and hanke basic info db operations

- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/HankeService.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/HankeServiceImpl.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/Persistence.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/domain/Hanke.kt
- services/hanke-service/src/main/resources/db/changelog/changesets/add-hanke-tyomaatiedot-fields.yml
- services/hanke-service/src/main/resources/db/changelog/db.changelog-master.yaml
Adds new fields to hanke-table, and a new table for one field that can contain multiple enum values, using a new changeset.
Tested with swagger and integrationTests run.
Documentation update in confluence (API page) being done.
TODO: validations and unit tests.
> HAI-247 added fields tyomaaKatuosoite, tyomaaTyyppi and tyomaaKoko

- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/Domain.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/HankeController.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/HankeServiceImpl.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/Persistence.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/domain/Hanke.kt
- services/hanke-service/src/main/resources/db/changelog/changesets/add-hanke-haitat-fields.yml
- services/hanke-service/src/main/resources/db/changelog/db.changelog-master.yaml
**Note: also includes a fix for tyomaakoko-enum entity-mapping, which changes the field mapping to convert enum to/from string value/names (instead of string-format ordinal number). If there are existing values in the database, they need to be null'ed or converted to corresponding values/names .**
Documentation updated.
IntegrationTests run.
Tested with swagger.
TODO: validation and tests.
> HAI-249 added fields for 'haitat'-page

- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/HankeControllerITests.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/HankeRepositoryITests.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/Constants.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/HankeController.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/HankeServiceImpl.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/domain/Hanke.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/validation/HankeValidator.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/HankeControllerTest.kt
and some minor fixes, cleanups and an additional test
Integrationtests run, confluence docs updated.
UI no longer needs to send the unnecessary createdBy-field. On the other hand, e.g. date values have now some checks.
> HAI-247 and HAI-249 validations

- .github/workflows/hanke-service-feature.yml
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/geometria/HankeGeometriatDaoImplITest.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/geometria/HankeGeometriatServiceImplITest.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/geometria/HankeGeometriatDaoImpl.kt
* geometry srid will be transformed into 3879 if it is different in incoming request
* returned geojson featurecollection will have csr information and srid 3879 in it (maybe later is needed to have a parameter stating the desired srid)
* fixed geometry integration tests by deleting existing data from database before each test
> Hai 208 geometry srid transform

- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/HankeRepositoryITests.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/HankeServiceITests.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/Configuration.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/Domain.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/HankeService.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/HankeServiceImpl.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/HankeYhteystietoEntity.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/Persistence.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/validation/HankeValidator.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/HankeControllerTest.kt
yhteystieto persistence changed to use Cascade.ALL and not using own Repository.
Fixed outgoing yhteystieto createdAt-field getting value from saved modifiedAt field.
Changed yhteystieto audit-fields to use internal info only, and along with cascade-all usage, updates to fields are copied to existing entity objects, instead of creating new ones.
Effects are contained mostly internally into the HankeServiceImpl-class.
Tested manually in swagger that the persistency and yhteystietohandling code changes should not affect REST API.
Did not cause changes to database.
Integration tests run.
TODO: some more tests to service and controller -levels.
> HAI-247 and HAI-249 tests and changed yhteystieto persistence

- docker-compose.yml
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/Application.kt
- services/hanke-service/src/main/resources/application.properties
* docker-compose.yml:ssä HAITATON_CORS_ALLOWED_ORIGINS: http://localhost:8000, jotta voisi Dockerilla ajaa kantoja ja bäkkäriä ja fronttia IDE:ssä tms erikseen
* application.properties:ssa oletuksena http://localhost:3001, jotta voisi ajaa Dockerilla kantaa ja UI:a ja bäkkäriä IDE:ssä erikseen
Jotta voi testata (siten, että hanke-service on localhost:8080), niin haitaton-ui:ssa pitää tehdä muutos src/common/utils/api.ts:
```
const api: AxiosInstance = axios.create({
baseURL: 'http://localhost:8080',
});
```
> HAI-467 CORS

- services/hanke-service/src/main/resources/db/changelog/changesets/set-defaults-to-hanke-flag-fields.yml
- services/hanke-service/src/main/resources/db/changelog/db.changelog-master.yaml
Would have been cleaner in the original changeset, but since that has already been run in to dev database, this does the relevant changes as additional step.
Tested locally, observing database results directly. Not yet tested in full environment, but since dev isn't working now, this certainly does not make it worse. Might even fix the problem.
> HAI-583 added default value and notnull constraint to flag fields

- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/ActuatorEndpointITests.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/IntegrationTestConfiguration.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/IntegrationTestResourceServerConfig.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/security/HankeControllerSecurityTests.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/security/HankeGeometriaControllerSecurityTests.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/security/OrganisaatioControllerSecurityTests.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/security/AccessRules.kt
Only tests the controller endpoints and their settings, not the actual authentication handling (JWT-token etc.) handling in front of it all. Also, if service-classes get method-level security later, these tests do not cover those.
Integration tests run.
> HAI-628 authentication & authorization tests for controllers

- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/HankeControllerITests.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/geometria/HankeGeometriaControllerITests.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/organisaatio/OrganisaatioControllerITests.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/tormaystarkastelu/TormaystarkasteluControllerITests.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/ResourceServerConfig.kt
and both tests and main code to use shared access rules.
Integration tests still pass.
The purpose of adding the class in the WebMvcTest annotation is to let spring-test to know that only the specified controller needs to be instantiated.
> HAI-628 similar annotation setups for integration tests

- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/IntegrationTestConfiguration.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/tormaystarkastelu/TormaysTarkasteluTulosRepositoryITests.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/tormaystarkastelu/TormaystarkasteluLaskentaServiceImplITest.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/Configuration.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/Domain.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/HankeService.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/HankeServiceImpl.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/Persistence.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/domain/Hanke.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/domain/HankeTilat.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/tormaystarkastelu/Persistence.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/tormaystarkastelu/TormaystarkasteluController.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/tormaystarkastelu/TormaystarkasteluLaskentaServiceImpl.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/tormaystarkastelu/TormaystarkasteluTulos.kt
- services/hanke-service/src/main/resources/db/changelog/changesets/add-tormaystarkastelu-results.yml
- services/hanke-service/src/main/resources/db/changelog/db.changelog-master.yaml
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/tormaystarkastelu/TormaystarkasteluCalculatorTest.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/tormaystarkastelu/TormaystarkasteluLaskentaServiceImplTest.kt
Implementation of persisting tormaystarkasteluTulos data for Hanke, and loading them from saved data.
HAI-537
Integration test results pass.
With latest UI, should be possible to see the result directly via initiating tormays tarkastelu, and later by observing the values on previously calculated hanke instances.
https://helsinkisolutionoffice.atlassian.net/wiki/spaces/HAI/pages/1468661795/T+rm+ystarkastelun+tietokantamallit
> Hai 537 tormtark tulosten tallennus

- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/HankeServiceITests.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/IntegrationTestConfiguration.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/PersonalDataLogRepositoryITests.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/Configuration.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/HankeServiceImpl.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/HankeYhteystietoEntity.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/logging/Persistence.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/logging/YhteystietoLoggingEntryHolder.kt
- services/hanke-service/src/main/resources/db/changelog/changesets/create-log-tables-for-personaldata.yml
- services/hanke-service/src/main/resources/db/changelog/db.changelog-master.yaml
Adds audit and change logging of personal data related events (except read access).
[HAI-793](https://helsinkisolutionoffice.atlassian.net/browse/HAI-793)
[HAI-799](https://helsinkisolutionoffice.atlassian.net/browse/HAI-799)
[HAI-800](https://helsinkisolutionoffice.atlassian.net/browse/HAI-800)
[HAI-801](https://helsinkisolutionoffice.atlassian.net/browse/HAI-801)
Using the full setup with local docker-compose, start creating a new hanke, fill in to reach yhteystieto-page.
First add the owner info and 'tallenna luonnos'. Check the database (schema "personaldatalogs") that new row got added (for CREATE action) in both tables.
Then modify that same owner info and 'tallenna luonnos'. Check the database for a new row (UPDATE action) in both tables.
Finally, add a second yhteystieto, save, …
> Hai 793 henkilotietojen lokitukset

- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/HankeRepositoryITests.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/HankeServiceITests.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/PersonalDataLogRepositoryITests.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/logging/PersonalDataLogRepositoryITests.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/ControllerExceptionHandler.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/Domain.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/HankeServiceImpl.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/HankeYhteystietoEntity.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/logging/Persistence.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/logging/YhteystietoLoggingEntryHolder.kt
- services/hanke-service/src/main/resources/db/changelog/changesets/add-personal-data-logs-failed-field.yml
- services/hanke-service/src/main/resources/db/changelog/changesets/add-personal-data-processing-restriction-support.yml
- services/hanke-service/src/main/resources/db/changelog/db.changelog-master.yaml
Quite crude implementation for support of data processing restriction for Yhteystietos. Setting or unsetting the restriction flag needs manual database operation (instructions for which will be in confluence, soon..)
Once set, if an update to a Hanke would try to change or delete such restricted Yhteystieto, the attempt will be blocked and (audit) logged, and the whole update to the Hanke will also be prevented. User will see normal "something went wrong" popup in the UI.
https://helsinkisolutionoffice.atlassian.net/browse/HAI-805
Have a hanke that can be modified, with e.g. two yhteystieto (easier to test with e.g. one owner and one arvioija). Manually set the datalocked-flag on the to-be-tested yhteystieto. Make sure the flag gets updated to backend (e.g. restart whole Haitaton or just …
> Hai 805 henkilotietojen kasittelyn kiellon tuki

- services/hanke-service/build.gradle.kts
Avoid liquibase changelog from locking down all together when one instance fails / is shut down by the orchestrator.
Also upgrade to Kotlin 1.6.10
> Add liquibase-sessionlock to avoid changelog from locking

- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/permissions/Permissions.kt
- services/hanke-service/src/main/resources/db/changelog/changesets/003-update-permissions-to-creator.sql
- services/hanke-service/src/main/resources/db/changelog/db.changelog-master.yaml
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/permissions/PermissionsTest.kt
Code was wrong in two both ways and the test wasn't asserting anything.
For every `Hanke` add every permission to the user who created it.
> Fix permission handling

- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/HankeControllerITests.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/HankeController.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/domain/Hanke.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/HankeControllerTest.kt
Include users permissions under `permissions` key for each hanke in response to `GET /hankkeet`
> Include users permissions in response

- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/HankeControllerITests.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/security/HankeControllerSecurityTests.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/HankeController.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/HankeServiceImpl.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/HankeControllerTest.kt
Add permission check to `GET /hankkeet/{hankeTunnus}`
> Check viewing permission when getting hanke by tunnus

- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/StatusControllerITests.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/StatusController.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/security/AccessRules.kt
Add `/api/status` endpoint for monitoring purposes. The functionality tests that database connections are working and also checks that the database is populated with at least some of the data required by the service.
> Add dedicated liveness endpoint to hanke-service

- .gitignore
- scripts/HEL-GIS-data-import.sh
- services/hanke-service/README.md
- services/hanke-service/build.gradle.kts
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/HankeServiceITests.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/IntegrationTestConfiguration.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/logging/PersonalDataLogRepositoryITests.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/Configuration.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/HankeServiceImpl.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/logging/Persistence.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/logging/YhteystietoLoggingEntryHolder.kt
- services/hanke-service/src/main/resources/application.properties
- services/hanke-service/src/main/resources/db/changelog/changesets/010-create-table-for-database-logging.yml
- services/hanke-service/src/main/resources/db/changelog/changesets/011-drop-old-personal-data-log-tables.yml
- services/hanke-service/src/main/resources/db/changelog/db.changelog-master.yaml
Unify all existing audit logging to log to a single table. This is done
in preparation for transferring the logs to a centralized storage.
The logging principles are described at
https://helsinkisolutionoffice.atlassian.net/wiki/spaces/HAI/pages/7990181897/Lokituksista
The old logs are simply deleted, since we don't have full audit logs
anyway, and we're not really in production yet. I'm still waiting on
confirmation if this is ok.
Also fix some issues that stopped the service working on a Silicon-based
mac.
or other location: https://helsinkisolutionoffice.atlassian.net/wiki/spaces/HAI/pages/7990181897/Lokituksista
> HAI-1180 Refactor audit logging to use unified database table

- services/hanke-service/README.md
- services/hanke-service/build.gradle.kts
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/HankeServiceITests.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/IntegrationTestConfiguration.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/logging/PersonalDataLogRepositoryITests.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/Configuration.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/HankeServiceImpl.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/logging/Persistence.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/logging/YhteystietoLoggingEntryHolder.kt
Use the Spotless Gradle plugin to run ktfmt on the codebase. Ktfmt is a
opinionated formatter for Kotlin code that's non-customizable by design.
Spotless checks during the build stage that all code is formatted with
ktfmt. If the code is not formatted correctly, the build will fail.
Only code changed since the origin/dev will be checked and formatted.
When a file is touched, the whole file needs to be reformatted, though.
The formatting can be checked with:
```
./gradlew spotlessCheck
```
And the code can be reformatted with:
```
./gradlew :services:hanke-service:spotlessApply
```
The formatting broke the line wrapping on some comments, so I fixed them
and rewrote some comments to make them shorter and/or more informative. …
> HAI-1222 Add ktfmt for automated formatting

- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/domain/PublicHankeControllerITests.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/domain/PublicHanke.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/security/AccessRules.kt
Allow anonymous access to the /public-hankkeet endpoint. Also add some tests that verify this endpoint exists and is accessible to all.
The new front page for unregistered users should still show the list of public hankkeet. Access to the endpoint seems to have been removed by accident. There were no tests in place to notice the mistake.
Call `/public-hankkeet` on the backend server after logging out.
or other location: -
> HAI-1257 Allow anonymous access to public hankkeet

- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/StatusControllerITests.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/StatusController.kt
Change the status endpoint to check for existence of any rows in the `tormays_central_business_area_polys` table, instead of checking that the table has one row.
Currently, there are 116 rows in that table at least on dev and staging environments. The check for one row fails, so the status endpoint always return 500 Internal Error. This stops us from using it as a health check endpoint. Old availability checks are calling `/organisaatiot/`, but that has required logging in for a while now, so they all fail.
> HAI Fix status endpoint

- .github/workflows/hanke-service-feature.yml
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/HankeControllerITests.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/HankeServiceITests.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/domain/PublicHankeControllerITests.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/factory/DateFactory.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/factory/HankeFactory.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/factory/HankeYhteystietoFactory.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/factory/PermissionFactory.kt
Add factories to make it easier to create some test data. Instead of creating e.g. a hanke from scratch and having to list all of its fields, factories enable the developer to create a hanke with sensible default values and override those defaults when necessary.
Also add methods to those factories that make it easier to create contact information to any test hanke.
Some tests didn't pass when run individually because of missing mocking. This also means that mocks were leaking between tests. Added a `@AfterEach` method for cleaning mocks in a few test classes to stop the leaking. This is something that should be kept in mind when writing new tests or editing old ones.
> HAI-1238 Add factories to create test data

- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/domain/PublicHankeControllerITests.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/factory/Factory.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/factory/HankeFactory.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/factory/HankeYhteystietoFactory.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/factory/PermissionFactory.kt
Add a generic mutate method to factories that can be used to alter the test objects without breaking method chains. Useful when the use-case is rare enough to not warrant a custom factory method.
> HAI-1238 Add a generic mutate method to factories

- services/hanke-service/Dockerfile-local
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/HankeControllerITests.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/HankeServiceITests.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/IntegrationTestConfiguration.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/security/HankeControllerSecurityTests.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/HankeController.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/HankeError.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/HankeServiceImpl.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/logging/Persistence.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/logging/YhteystietoLoggingEntryHolder.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/logging/YhteystietoLoggingService.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/ExtensionsKtTest.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/HankeControllerTest.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/factory/AuditLogEntryFactory.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/factory/HankeFactory.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/factory/HankeYhteystietoFactory.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/logging/YhteystietoLoggingServiceTest.kt
Add entries to audit logs whenever users read contacts from hankket. This is done, because we need to know who has accessed personal information and what that information was.
Check that READ type audit logs are added to DB whenever yhteystiedot are returned to the user. Ie. when hankkeet are read, listed, updated or created (if they have yhteystiedot).
or other location: Already documented in https://helsinkisolutionoffice.atlassian.net/wiki/spaces/HAI/pages/7990181897/Lokituksista
> HAI-1076 Create audit log entries when hankeyhteystiedot are given to users

- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/HankeServiceITests.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/logging/PersonalDataLogRepositoryITests.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/Configuration.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/allu/ApplicationService.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/allu/CableReportApplication.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/allu/CableReportServiceAllu.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/logging/DisclosureLogService.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/logging/Persistence.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/logging/YhteystietoLoggingEntryHolder.kt
- services/hanke-service/src/main/resources/db/changelog/changesets/012-add-user-role-to-audit-log.yml
- services/hanke-service/src/main/resources/db/changelog/db.changelog-master.yaml
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/HankeControllerTest.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/allu/ApplicationControllerTest.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/allu/ApplicationServiceTest.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/factory/AuditLogEntryFactory.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/logging/DisclosureLogServiceTest.kt
Add entries to audit logs whenever users read customers and contacts from Allu applications. This is done because we need to know who has accessed personal information and what that information was.
Allu test environment is down at the moment, so this has only been tested with unit tests.
> HAI-1076 Create audit logs when application data is sent to Allu

- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/IntegrationTestConfiguration.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/gdpr/GdprControllerITests.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/gdpr/GdprController.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/logging/DisclosureLogService.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/logging/Persistence.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/factory/AuditLogEntryFactory.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/logging/DisclosureLogServiceTest.kt
Add entries to audit logs whenever we respond to GDPR requests with personal information. This is done because we need to know who has accessed personal information and what that information was.
https://helsinkisolutionoffice.atlassian.net/browse/HAI-1076
> HAI-1076 Create audit log when responsing to GDPR requests

- haitaton_audit_log_mapping.yml
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/HankeServiceITests.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/logging/AuditLogServiceITests.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/Configuration.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/HankeServiceImpl.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/allu/ApplicationService.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/logging/AuditLogEntry.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/logging/AuditLogService.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/logging/DisclosureLogService.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/logging/Persistence.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/logging/YhteystietoLoggingEntryHolder.kt
- services/hanke-service/src/main/resources/db/changelog/changesets/013-recreate-audit-logs-table.yml
- services/hanke-service/src/main/resources/db/changelog/db.changelog-master.yaml
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/allu/ApplicationServiceTest.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/factory/AuditLogEntryFactory.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/logging/DisclosureLogServiceTest.kt
Drop the earlier audit_log table and recreate it as audit_logs with the schema the transfer component uses. The audit logging was never in production, so it's safe to drop the table with it's content.
Transferring audit logs from the local haitaton database to the centralized logging storage will be handled by the reusable log transfer component. The transfer component needs the audit logs to be in a specific database table with a specific schema. These are documented on its [confluence page](https://helsinkisolutionoffice.atlassian.net/wiki/spaces/HELFI/pages/8033697816/Logging+Transferring+log+entries+to+elastic+using+reusable+component).
Opening the "Omat Hankkeet" page should write to the audit_logs table if there are any hankkeet with any contact persons.
Adding or modifying the …
> HAI-1323 Make audit log table compatible with transfer component

- scripts/gis-material-update/README.md
- scripts/gis-material-update/config.yaml
- scripts/gis-material-update/inspect-disk.sh
- scripts/gis-material-update/process/modules/autoliikennemaarat.py
- scripts/gis-material-update/process/process_data.py
- scripts/gis-material-update/process/test/test_autoliikennemaarat.py
- scripts/gis-material-update/process/test/test_configuration.py
- scripts/gis-material-update/process/test/test_hsl.py
Implemented processing of traffic volume polygons.
https://helsinkisolutionoffice.atlassian.net/browse/HAI-1292
Prerequisite: fetch `maka_autoliikennemaarat` source materials, as per instructions in the README
Go to directory: haitaton-backend/scripts/gis-material-update/process
(create and) activate Python virtual environment
run `python -m unittest discover -v`
- [] I have made necessary changes to the documentation, link to confluence
-
> HAI-1292 Prepare traffic volumes GIS material

- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/logging/AuditLogServiceITests.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/logging/Persistence.kt
- services/hanke-service/src/main/resources/db/changelog/changesets/014-add-timezone-to-audit-logs-created-at.sql
- services/hanke-service/src/main/resources/db/changelog/db.changelog-master.yaml
Modify the created_at column in audit_logs table to use timestamp with timezone instead of timezoneless timestamp.
The reusable log transfer component has been giving out warnings when transferring audit logs. It complains that created_at doesn't have timezone information, even though timezones would be supported. The documentation was ambiguous on whether the timestamp should have timezone information or not. The documentation has since been improved.
- https://helsinkisolutionoffice.atlassian.net/wiki/spaces/HELFI/pages/8033697816/Logging+Transferring+log+entries+to+elastic+using+reusable+component?NO_SSR=1#Schema
- https://github.com/City-of-Helsinki/structured-log-transfer#postgresql-create-minimal-table-and-insert-test-data-into-it
I checked that the created_at …
> HAI-1323 Add timestamp to created_at in audit_logs

- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/DatabaseTest.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/HankeServiceITests.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/HanketunnusServiceImplITest.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/geometria/HankeGeometriatDaoImplITest.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/geometria/HankeGeometriatServiceImplITest.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/logging/AuditLogServiceITests.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/tormaystarkastelu/TormaystarkasteluLaskentaServiceImplITest.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/tormaystarkastelu/TormaystarkasteluTormaysServicePGITest.kt
- services/hanke-service/src/integrationTest/resources/clear-db.sql
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/TestExtensions.kt
Move the PostgreSQL container definitions to an abstract class so that they are not repeated in every test class that needs to use the database.
This has the added benefit of reusing the database container for all tests. Even after adding a script to clean the database between each test, this sped up running the integration tests from 2.5 minutes to 50 seconds on my machine. That's 1/3 of the time they used to take.
Some other, smaller, refactoring was done while touching the classes anyway, e.g. fixing the compilation warnings from
`TormaystarkasteluLaskentaServiceImplITest`.
> HAI-1323 Refactor db containers in tests

- scripts/gis-material-update/README.md
- scripts/gis-material-update/config.yaml
- scripts/gis-material-update/copy-files.sh
- scripts/gis-material-update/fetch/fetch_data.sh
- scripts/gis-material-update/osm_vrt_clip.vrt
OSM material download. Limit downloaded line geometries to Helsinki area.
Changed address description in configuration file (`addr`) to contain also method (i.e. `WFS`, `/vsicurl`, ...)
Implemented reprojection and intersection computation with OGR VRT driver.
Implemented SQL quoting in configuration file with separate label, which is delivered as quoted string in fetch shell script: `extra_quoted_args`
https://helsinkisolutionoffice.atlassian.net/browse/HAI-1312
https://helsinkisolutionoffice.atlassian.net/browse/HAI-1313
Prerequisite: fetch `hki` and `osm` source materials, as per instructions in the README
* build containers and copy files, as instructed in README
* Run fetch (processing time around 30 minutes or a bit less): `docker-compose run --rm gis-fetch helsinki_osm_lines`
* …
> HAI-1213/OSM download and limit to Helsinki area

- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/domain/PublicHanke.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/tormaystarkastelu/TormaystarkasteluLaskentaService.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/validation/HankeValidator.kt
Make hanke start and end dates optional.
The UI no longer sends start and end dates for a hanke. The dates will be a part of the new HankeAlue objects when hankkeet get those.
For now, resolve this by making them optional, so creating hankkeet doesn't crash.
> HAI Emergency fix for Hanke dates

- scripts/hel-gis-data-download.sh
- scripts/hel-gis-data-import-to-db.sh
- scripts/hel-gis-data-variables.sh
Tormays GIS material update to local dev script is split to two: download and update.
https://helsinkisolutionoffice.atlassian.net/browse/HAI-1331
* start VPN
* ensure local development database is up and running
* run download script in `scripts` -directory: `bash hel-gis-data-download.sh`
* data is downloaded from haitaton fileshare to separate directory (tormays_polys)
* (you might need to stop VPN at this point)
* run import script: `bash hel-gis-data-import-to-db.sh`
* Geopackage files from `tormays_polys` are imported to local database
With this setup, user is able to download tormays -gis materials to dedicated directory and import materials to local database. Next steps will focus on, how the material is updated to staging environments.
> HAI-1331/update split to download and database update

- scripts/gis-material-update/process/modules/autoliikennemaarat.py
Data type was changed to int32 for `volume` -attribute.
https://helsinkisolutionoffice.atlassian.net/browse/HAI-1384
Run data fetch and data process as instructed here: https://github.com/City-of-Helsinki/haitaton-backend/blob/dev/scripts/gis-material-update/README.md
```
docker-compose run --rm gis-fetch maka_autoliikennemaarat
docker-compose run --rm gis-process maka_autoliikennemaarat
```
Verify by checking output result (at directory gis-material-update):
First, 15m buffered material:
```
ogrinfo haitaton-gis-output/tormays_volumes15_polys.gpkg tormays_volumes15_polys -so | tail -3
FID Column = fid
Geometry Column = geom
volume: Integer (0.0)
```
And same check for 30m buffered material:
```
ogrinfo …
```
> HAI-1384/traffic volume data type fix

- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/HankeServiceITests.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/domain/PublicHankeControllerITests.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/geometria/GeometriatServiceImplITest.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/logging/AuditLogServiceITests.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/Configuration.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/Constants.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/Extensions.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/HankeController.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/HankeService.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/HankeServiceImpl.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/HankeYhteystietoEntity.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/HankealueEntity.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/domain/Hanke.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/domain/HankeYhteystieto.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/domain/Hankealue.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/domain/HasId.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/logging/AuditLogEntry.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/logging/AuditLogService.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/logging/DisclosureLogService.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/logging/HankeLoggingService.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/logging/YhteystietoLoggingEntryHolder.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/tormaystarkastelu/TormaystarkasteluTulos.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/factory/AuditLogEntryFactory.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/factory/HankeFactory.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/factory/HankealueFactory.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/logging/DisclosureLogServiceTest.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/logging/HankeLoggingServiceTest.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/test/TestUtils.kt
Add entries to audit logs whenever users delete a hanke. Log seperate entries for the hanke itself and the yhteystiedot of those.
Refactor some logging code to make adding the rest of the audit logs easier.
1. Create a hanke. Add some yhteystiedot for it.
2. Delete the hanke.
3. Check database audit_logs table for results.
- You can query the DELETE type log messages with:
```select * from audit_logs where message->'audit_event'->>'operation' = 'DELETE';```  
> HAI-1075 Add modify log for deleting hankkeet

- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/HankeServiceITests.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/HankeService.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/HankeServiceImpl.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/logging/AuditLogService.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/logging/HankeLoggingService.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/logging/HankeLoggingServiceTest.kt
Add an entry to audit logs whenever users create a new hanke. Yhteystiedot were already logged, and I didn't mess with those.
It was tempting to refactor the yhteystieto logging, so it wouldn't be quite so entwined with creating the data, and also updating the hanke. But this would've meant rewriting most of the create and update code, so I didn't.
- Create a new hanke.
- Check database audit_logs table has a new entry for the created hanke.
> HAI-1075 Add modify log for creating hankkeet

- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/HankeServiceITests.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/HankeService.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/HankeServiceImpl.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/HankealueEntity.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/domain/Hankealue.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/logging/AuditLogService.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/logging/HankeLoggingService.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/logging/HankeLoggingServiceTest.kt
Add an entry to audit logs whenever users update a new hanke.
Only add the entry, if the content of the hanke has been changed. Currently, the content always changes, since the version field is updated whether there are any other changes or not.
- Make a change to a hanke.
- Check database audit_logs table has a new entry for the updated hanke.
> HAI-1075 Add modify log for updating hankkeet

- scripts/gis-material-update/process/modules/ylre_katuosat.py
Old datatype for ylre_street_area was int64, new int32
Data type was changed to int32 for `ylre_-street_area` -attribute.
https://helsinkisolutionoffice.atlassian.net/browse/HAI-1385
Run data fetch and data process as instructed here: https://github.com/City-of-Helsinki/haitaton-backend/blob/dev/scripts/gis-material-update/README.md
```
docker-compose run --rm gis-fetch ylre_katuosat
docker-compose run --rm gis-process ylre_katuosat
```
Verify by checking output result (at directory gis-material-update):
```
ogrinfo haitaton-gis-output/tormays_ylre_parts_polys.gpkg tormays_ylre_parts_polys -so | tail -3
FID Column = fid
Geometry Column = geom
ylre_street_area: Integer (0.0)
```
-
> HAI-1385 YLRE parts data type change

- services/hanke-service/README.md
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/allu/ApplicationControllerITest.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/allu/ApplicationServiceITest.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/allu/CableReportServiceAlluITests.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/HankeError.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/allu/ApplicationController.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/allu/ApplicationData.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/allu/ApplicationService.kt
Make saving the Allu ID more evident. Changing the value on the entity was buried deep in the call-stack. Instead, use Allu ID was the return value of the methods and set it at the main service methods.
There was a bug with pendingOnClient. When an application was sent to Allu and it was still in PENDING status in Allu, doing any change to the application would set the pendingOnClient parameter to true. This would make Allu set the status to PENDING_CLIENT, stopping any processing of the application in Allu.
This is fixed by stopping application update API from changing the pendingOnClient value at all. There's a separate send application API which sets the pendingOnClient to false, allowing it's processing in Allu. In Haitaton lingo, we would say the application transitions from a draft …
> HAI-1297 Refactor saving Allu ID

- services/hanke-service/README.md
- services/hanke-service/build.gradle.kts
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/configuration/Configuration.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/configuration/OpenApiConfiguration.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/configuration/ResourceServerConfig.kt
- services/hanke-service/src/main/resources/application.properties
Both the UI code and the OpenAPI Json documentation are already accessible from anywhere in the world, but they don't work together, because the UI doesn't know to add `/api` in front of the URLs for Swagger configuration and the OpenAPI documentation.
Fix this by adding the `/api` in front of the URLs by default. This should work both locally with docker compose and on the cloud. Add an environment variable to `bootRun` to drop the `/api` prefix when running the service locally without docker.
> HAI Make OpenAPI documentation accessible from behind reverse proxy

- services/hanke-service/build.gradle.kts
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/HankeServiceITests.kt
- services/hanke-service/src/integrationTest/resources/fi/hel/haitaton/hanke/logging/expectedHankeWithPoints.json.mustache
- services/hanke-service/src/integrationTest/resources/fi/hel/haitaton/hanke/logging/expectedHankeWithPolygon.json.mustache
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/domain/Hankealue.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/geometria/Geometriat.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/logging/HankeLoggingService.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/TestExtensions.kt
When the modify logging for hankkeet was implemented, hankealue and the related geometries were under heavy development. It was decided to leave logging the geometries for later, with the thought it might be smart to log them separately from the main hanke object changes.
However, implementing separate logging for geometries or the hankealueet added a lot of complexity, so I deemed it better to just add them to the log objects of the main hanke object. There are no endpoints to modify the alueet or geometries separately and there no plans to add any. So logically, the hanke is a single resource from the API viewpoint.
[HAI-1342]: https://helsinkisolutionoffice.atlassian.net/browse/HAI-1342?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWN …
> HAI-1342 Add geometries to modify logs for hankkeet

- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/allu/ApplicationServiceITest.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/allu/CableReportServiceAlluITests.kt
- services/hanke-service/src/integrationTest/resources/clear-db.sql
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/allu/AlluStatus.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/allu/AlluUpdateService.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/allu/Application.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/allu/ApplicationEntity.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/allu/ApplicationService.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/allu/CableReportService.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/allu/CableReportServiceAllu.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/configuration/Configuration.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/configuration/SchedulingConfig.kt
- services/hanke-service/src/main/resources/db/changelog/changesets/018-add-status-and-indentifier-for-applications.yml
- services/hanke-service/src/main/resources/db/changelog/changesets/019-create-allustatus-table.yml
- services/hanke-service/src/main/resources/db/changelog/db.changelog-master.yaml
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/TestExtensions.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/allu/AlluUpdateServiceTest.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/allu/ApplicationServiceTest.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/factory/AlluDataFactory.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/factory/ApplicationHistoryFactory.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/gdpr/GdprJsonConverterTest.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/logging/DisclosureLogServiceTest.kt
Add a field to applications for storing the status the application has in Allu. Periodically get the application history from Allu and update the value. The update is done with one minute intervals.
Also add a field for the application identifier and update it from Allu while getting the application history.
1. Create an application (with http://localhost:3001/fi/johtoselvityshakemusvanha).
2. Send the application.
3. Use the temporary feature (#249) to mark the application as a draft. (I used cURL to send the request to haitaton backend.)
4. Wait a minute. The logs should show when the status is updated.
5. Check the database that the status and application identifier has been updated.
6. Send the application from the UI again, and see that the status updates after a minute.
or other …
> HAI-1300 Update application statuses periodically from Allu

- services/hanke-service/build.gradle.kts
- services/hanke-service/src/integrationTest/resources/clear-db.sql
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/allu/AlluUpdateService.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/configuration/LockService.kt
- services/hanke-service/src/main/resources/db/changelog/changesets/020-create-lock-table.yml
- services/hanke-service/src/main/resources/db/changelog/db.changelog-master.yaml
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/allu/AlluUpdateServiceTest.kt
Use Spring's distributed database lock to make sure only one instance / pod of hanke-service tries to update application statuses at any one time.
> HAI-1300 Distributed mutex with database

- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/domain/PublicHankeControllerITests.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/PublicHankeController.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/domain/PublicHanke.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/validation/CompleteHankeValidator.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/TestExtensions.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/factory/HankeFactory.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/validation/CompleteHankeValidatorTest.kt
The public hanke list has been failing when some hanke didn't have a starting date, but had a tormaystarkastustulos. A hanke was deemed public when it had a tormaystarkastustulos, even though it might not have other mandatory fields. This was against the spec.
Implement proper checks if a hanke is a draft. I.e. check individually that all mandatory fields are present and non-empty.
> HAI-1444 Fix public hanke list

- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/IntegrationTestConfiguration.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/allu/CableReportServiceAlluITests.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/application/ApplicationControllerITest.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/application/ApplicationServiceITest.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/gdpr/GdprControllerITests.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/HankeError.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/allu/AlluApplicationData.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/allu/AlluCommonDomain.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/allu/CableReportService.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/allu/CableReportServiceAllu.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/application/AlluUpdateService.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/application/Application.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/application/ApplicationController.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/application/ApplicationData.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/application/ApplicationEntity.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/application/ApplicationService.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/application/CustomerWithContacts.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/configuration/Configuration.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/gdpr/GdprController.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/gdpr/GdprJsonConverter.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/logging/ApplicationLoggingService.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/logging/DisclosureLogService.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/application/AlluUpdateServiceTest.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/application/ApplicationControllerTest.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/application/ApplicationServiceTest.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/factory/AlluDataFactory.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/factory/AuditLogEntryFactory.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/gdpr/GdprJsonConverterTest.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/logging/DisclosureLogServiceTest.kt
Split the representation for application data we use internally within Haitaton from the one we use to communicate with Allu. So far they've been the same, but we need to support hakemusalueet internally, which Allu doesn't support.
1. Split the purely Allu-related classes to their own package, move the rest to application-package.
2. Copy the Application Data and it's child classes to the application package.
3. Rename the Allu-version of ApplicationData as AlluApplicationData.
3. Remove unnecessary fields and methods from the classes in allu-package.
While doing that, change customer type and start / end dates to be optional internally. Add some simple validation while converting the values to Allu classes.
As a slightly unrelated change, stop updating an application in database if it …
> HAI-1397 Split internal and external application data representation

- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/HankeServiceITests.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/geometria/GeometriatDaoImplITest.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/geometria/GeometriatDaoImpl.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/geometria/GeometriatServiceImpl.kt
- services/hanke-service/src/main/resources/db/changelog/changesets/022-add-trigger-for-removing-orphaned-geometriat.sql
- services/hanke-service/src/main/resources/db/changelog/db.changelog-master.yaml
Add a database trigger to delete geometriat of deleted hankealue. This ensures there are no orphaned geometriat left behind after a hankealue is removed.
I tried other ways of tackling this, but they proved ineffective or very complex. The removal of hankealueet is more implicit than explicit, leveraging JPA's orphan removal. The geometriat is not an JPA entity, however, so the orphan removal doesn't reach them.
One of these abandoned ways was changing how geometries are deleted in GeometriatDao(Impl). Deleting is changed to actually delete the geometriat-table row when asked to. It used to make sense to always have a geometria for a hanke, but with the introduction of hankealueet, this no longer feels like the case.
There's also some small refactoring. These were done for abandoned …
> HAI-1376 Prevent orphaned geometriat

- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/application/ApplicationServiceITest.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/allu/CableReportService.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/allu/CableReportServiceAllu.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/application/ApplicationService.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/application/ApplicationServiceTest.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/factory/AlluDataFactory.kt
We need to get the current application status from Allu to know if we can still update an application. Previously, this has been done using the application history query. This has problems, though. It requests more information than we need, since it gets the complete history from Allu. Also, there's a need to deduce the current status from the list of histories. And, perhaps most importantly, the history doesn't return anything after the application has been added for the first time. It only starts returning results after the application has been updated.
Replace the history query with the get application data query. This only returns the current status of the application and it returns the status for all applications, whether or not they've been updated.
This seems like both more …
> HAI-1347 Rewrite getting current application status

- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/application/ApplicationServiceITest.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/application/ApplicationData.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/application/ApplicationServiceTest.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/factory/AlluDataFactory.kt
- services/hanke-service/src/test/resources/fi/hel/haitaton/hanke/application/applicationData.json
Add a field for rock excavation to application data.
If it's set, a row of text is added to the work description of the application: Either 'Louhitaan' or 'Ei louhita'.
If it's not set, it will prevent the application from being sent as it's considere incomplete.
First merge #260 and then this one.
> HAI-1464 Add rock excavation to application data

- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/application/ApplicationServiceITest.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/application/ApplicationController.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/application/ApplicationService.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/application/ApplicationServiceTest.kt
Add check to application update to see if it has actually changed. Do the related actions like updating Allu only when updating.
Only send applications if they are drafts. After the first time it's been marked as non-draft, the sending endpoint doesn't change anything anymore. changes are uploaded with the update endpoint after the application has been uploaded.
Change pages in the cable report form in UI (http://localhost:3001/fi/johtoselvityshakemus?hanke=HAI23-1). This will send update requests. See backend logs to see that nothing much is happening.
Pressing the send button on the last page of the cable report application for a second or a third time shouldn't do much on the backend side.
> HAI-1470 Update applications only if changed

- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/HankeServiceITests.kt
- services/hanke-service/src/integrationTest/resources/fi/hel/haitaton/hanke/geometria/hankeGeometriat.json
- services/hanke-service/src/integrationTest/resources/fi/hel/haitaton/hanke/logging/expectedHankeWithPoints.json.mustache
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/HankeServiceImpl.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/geometria/Geometriat.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/geometria/GeometriatServiceImpl.kt
- services/hanke-service/src/test/resources/fi/hel/haitaton/hanke/geometria/hankeGeometriat.json
Geometriat.featureCollection.features.properties is a map that can pretty much contain anything. Furthermore, hankeTunnus is the only entry we are interested in.
This commit removes unwanted properties by replacing the properties with a new map with hankeTunnus key / value. Everything else is discarded.
P.s. Jira ticket mentions a validation and error throwing as an alternative solution. I chose not to do that as it would be a breaking change in the api.
1. Create a new hanke containing properties that are of no interest (POST http://localhost:3001/api/hankkeet). For example, add this to your payload:
```
{
"geometriat": {
"featureCollection": {
"type": "FeatureCollection",
"features": [
{
"type": "Feature",
"geometry": {
"type": "Polygon",
"coordinates": [
[
[25496070.09, 6679284.13], …
```
> HAI-1399 Add sanitization of incoming geolocation feature data

- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/geometria/GeometriatDaoImplITest.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/application/ApplicationService.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/configuration/Configuration.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/domain/Hanke.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/domain/Hankealue.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/geometria/GeometriatDao.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/geometria/GeometriatDaoImpl.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/application/ApplicationServiceTest.kt
Fix area calculation while forming the application data PDF to Allu by using the application area objects from the new API. the individual areas were already calculated using the new object, but the total area wasn't. Make sure that overlapping polygons in the area are only calculated once.
Remove the `@Bean` for ObjectMapper. I thought it helped with sending the dates to Allu in the correct format, but now after further testing, the dates are sent just fine without it. It broke other things, because the Spring Boot default ObjectMapper ignores unknown fields, but our custom configuration doesn't. The `@JsonIgnoreProperties` annotations that were added as an emergency fix can now be removed.
> HAI-1524 Fix PDF area calculation and JSON deserialization

- githooks/pre-push
- services/hanke-service/README.md
- services/hanke-service/build.gradle.kts
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/application/ApplicationServiceITest.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/application/ApplicationData.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/application/ApplicationDataMapper.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/application/ApplicationService.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/application/ApplicationDataMapperTest.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/application/ApplicationServiceTest.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/factory/AlluDataFactory.kt
- services/hanke-service/src/test/resources/fi/hel/haitaton/hanke/application/applicationData.json
Remove old geometry field from hankealue. This has been replaced by the areas -field. The frontend has been updated, so the geometry-field is now safe to remove.
Also added a gradle command to install a git hook. This is not run automatically, but can be run with `./gradlew installGitHook`
> HAI-1488 Remove old geometry from hankealue

- scripts/gis-material-update/README.md
- scripts/gis-material-update/process/modules/hsl.py
- scripts/gis-material-update/process/test/test_hsl.py
HSL trunk lines are now determined by data, not hard-coded to source code.
https://helsinkisolutionoffice.atlassian.net/browse/HAI-1327
Prerequisite: fetch `hsl` and `hki` source materials, as per instructions in the README
Go to directory: `haitaton-backend/scripts/gis-material-update/process`
(create and) activate Python virtual environment, run:
```
python -m unittest discover -v
```
None
> HAI-1327/HSL bus trunk lines determined by data

- services/hanke-service/src/main/resources/db/changelog/changesets/024-connect-application-to-hanke.yml
- services/hanke-service/src/main/resources/db/changelog/changesets/025-clear-existing-applications.sql
- services/hanke-service/src/main/resources/db/changelog/db.changelog-master.yaml
The previous commit for HAI-1345 deleted all applications because the existing applications are not linked with hankkeet. Unfortunately, they remove deleted only after the migration adding the foreign key from applications to hanke. So if there are applications, the migration will fail with
```
org.postgresql.util.PSQLException: ERROR: column "hanke_id" of relation "applications" contains null values
```
To fix this, do the delete before adding the foreign key.
Modifying migrations afterwards is kind of taboo, but it should be fine in this instance, since the migrations haven't been deployed anywhere yet.
Create an application with commit e5f0f6ca9021c38668626cea5196ca89004bb4c8 (before adding the migrations). Then change to this branch, and starting the application should succeed.
or …
> HAI-1345 Fix for database migrations

- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/HankeControllerITests.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/HankeServiceITests.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/application/ApplicationServiceITest.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/ControllerExceptionHandler.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/HankeController.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/HankeError.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/HankeService.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/HankeServiceImpl.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/application/ApplicationService.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/configuration/Configuration.kt
Hanke can only be deleted if it has not proceeded to being handled in Allu. This commit checks application statuses (and throws exception if they are) before proceeding to hanke deletion. 
> HAI-1406 Prevent deletion of hanke if it is being handled in allu

- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/HankeServiceITests.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/application/ApplicationServiceITest.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/HankeServiceImpl.kt
If hanke deletion has proceeded to post validity check, all pending applications need to be:
- canceled in Allu
- deleted from database
After this, the hanke can be deleted.
Create hanke and add hakemus for it. If hakemus status is suitable (null, pending or pending_client) hanke deletion (along with hakemus) is allowed and successful. If hakemus has proceeded to Allu handling, endpoint will return 409 conflict status.
> HAI-1407 Add functionality to cancel and delete applications in hanke deletion

- scripts/gis-material-update/README.md
- scripts/gis-material-update/config.yaml
- scripts/gis-material-update/process/modules/tram_infra.py
- scripts/gis-material-update/process/process_data.py
- scripts/gis-material-update/process/test/compare_utils.py
- scripts/gis-material-update/process/test/test_hsl.py
- scripts/gis-material-update/process/test/test_tram_infra.py
Implemented tram infra tormays-material processing.
Also implemented following enhancements:
- reading OSM data (speedup obtained by clipping, config.yaml)
- fixed Helsinki municipality area GIS material source (config.yaml)
- implemented default deployment profile (process_data.py)
- fixed HSL test case: don't require pre-existing processed output files (test/test_hsl.py)
[HAI-1314](https://helsinkisolutionoffice.atlassian.net/browse/HAI-1314)
See README for preparing containers (building containers, copying files). After these initial steps, run fetch and process as separate docker runs. See exact details from README:
```
docker-compose run --rm gis-fetch hki osm helsinki_osm_lines
docker-compose run --rm gis-process tram_infra
``` …
> HAI-1314/tram infra processing

- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/HankeControllerITests.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/HankeRepositoryITests.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/HankeServiceITests.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/allu/CableReportServiceAlluITests.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/application/ApplicationControllerITest.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/application/ApplicationServiceITest.kt
- services/hanke-service/src/integrationTest/resources/fi/hel/haitaton/hanke/logging/expectedHankeWithPoints.json.mustache
- services/hanke-service/src/integrationTest/resources/fi/hel/haitaton/hanke/logging/expectedHankeWithPolygon.json.mustache
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/HankeError.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/HankeServiceImpl.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/Persistence.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/Utils.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/allu/AlluCommonDomain.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/application/ApplicationController.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/application/CustomerWithContacts.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/domain/Hanke.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/domain/TypeAliases.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/gdpr/GdprInfo.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/gdpr/GdprJsonConverter.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/validation/ApplicationValidator.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/validation/ValidApplication.kt
- services/hanke-service/src/main/resources/db/changelog/changesets/026-drop-tyomaakoko-from-hanke.yml
- services/hanke-service/src/main/resources/db/changelog/db.changelog-master.yaml
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/UtilsKtTest.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/allu/ApplicationPdfServiceTest.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/factory/AlluDataFactory.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/factory/HankeFactory.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/gdpr/GdprJsonConverterTest.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/logging/DisclosureLogServiceTest.kt
- services/hanke-service/src/test/resources/fi/hel/haitaton/hanke/application/applicationData.json
Changes to hanke / Allu data objects based on Allu requirements.
1. Remove field TyomaaKoko
2. Disallow usage of personal identity code in registryKey. Previously this field was either personal identity code or business identity (y-tunnus). 
3. Remove person related address data.
BusinessId validation is done according to Verohallinto documentation: https://www.vero.fi/globalassets/tietoa-verohallinnosta/ohjelmistokehittajille/yritys--ja-yhteis%C3%B6tunnuksen-ja-henkil%C3%B6tunnuksen-tarkistusmerkin-tarkistuslaskenta.pdf
HAI-1349 needs to be merged before this.
> HAI-1505 Hanke field changes based on Allu

- services/hanke-service/src/main/resources/db/changelog/changesets/027-add-generated-to-hanke.yml
The database migration that adds the generated-column to hanke table didn't work if there are any existing hanke in the table.
It failed with:
```
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'liquibase' defined in class path resource [org/springframework/boot/autoconfigure/liquibase/LiquibaseAutoConfiguration$LiquibaseConfiguration.class]: Invocation of init method failed; nested exception is liquibase.exception.MigrationFailedException: Migration failed for change set db/changelog/changesets/027-add-generated-to-hanke.yml::027-add-generated-to-hanke::admin:
Reason: liquibase.exception.DatabaseException: ERROR: column "generated" of relation "hanke" contains null values [Failed SQL: (0) ALTER TABLE public.hanke ADD generated BOOLEAN NOT NULL]
``` …
> HAI-1571 Fix for database migration

- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/allu/CableReportServiceAlluITests.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/configuration/Configuration.kt
Spring web client can only download about 250kB files to memory by default. Downloading bigger files in memory leads to `org.springframework.core.io.buffer.DataBufferLimitException: Exceeded limit on max bytes to buffer : 262144`.
This could be increased by setting `spring.codec.max-in-memory-size`, but that would affect other parts of Spring as well.
Instead, increase the codec max memory size only for WebClient.
1. Create a johtoselvityshakemus and send it to Allu.
2. In Allu, add a large (>256kB) attachment to the decision and make the decision.
3. Download it from Haitaton.
> HAI-1461 Add support for downloading big files from Allu

- scripts/gis-material-update/README.md
- scripts/gis-material-update/config.yaml
- scripts/gis-material-update/data/README.md
- scripts/gis-material-update/docker-compose.yml
- scripts/gis-material-update/fetch/fetch_data.sh
- scripts/gis-material-update/process/modules/cycling_infra.py
- scripts/gis-material-update/process/process_data.py
- scripts/gis-material-update/process/test/compare_utils.py
- scripts/gis-material-update/process/test/test_cycle_infra.py
Created GIS tormays-materials from cycling routes.
* Combine existing prioritized and main cycling route materials into one
* provide method (directory) for inputting existing materials, not available from public sources
[HAI-1538](https://helsinkisolutionoffice.atlassian.net/browse/HAI-1538)
See README for preparing containers (building containers, copying files). After these initial steps, run fetch and process as separate docker runs. See exact details
* `data/README.md`: for downloading required prerequisite from Sharepoint
* `README.md` : for processing
```
docker-compose run --rm gis-fetch cycle_infra
docker-compose run --rm gis-process cycle_infra
```
Results are in haitaton-gis-output local directory.
Prerequisite: fetch …
> HAI-1538 cycling infra

- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/HankeServiceITests.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/permissions/HankeKayttajaServiceITest.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/HankeServiceImpl.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/HankeYhteystietoEntity.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/configuration/Configuration.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/permissions/HankeKayttajaService.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/permissions/UserContactDto.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/YhteyshenkiloTest.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/factory/HankeFactory.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/factory/HankeYhteystietoFactory.kt
When creating or updating hanke, save users and user tokens for all new contact persons. Note: contact person is Yhteyshenkilo and not HankeYhteystieto.
A contact is new, if there isn't already a user with the same email on the hanke.
The user tokens can be used to invite the user to Haitaton.
Frontend does not yet support the same data model as backend. Hence:
1. In the ui (devtools open), create hakemus and try adding a subcontact (yhteyshenkilo). The request will fail but
-  take take request payload and copy it somewhere
- modify one of the alikontaktit fields as follows:
```
"alikontaktit": [
{
"etunimi": "Matti",
"sukunimi": "Meikäläinen",
"email": "foobar@mail.com",
"puhelinnumero": ""
}
] 
```   
3. Use curl etc PUT http://localhost:3001/api/hankkeet/<HANKE_TUNNUS> with modified …
> HAI-1319 Tokens for new hanke contacts

- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/HankeControllerITests.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/HankeRepositoryITests.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/HankeServiceITests.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/factory/HankeFactory.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/tormaystarkastelu/TormaystarkasteluLaskentaServiceTest.kt
Compiling results to some warnings e.g:
HankeFactory.kt: (63, 13): Parameter 'alkuPvm' is never used
HankeFactory.kt: (64, 13): Parameter 'loppuPvm' is never used
This commit removes the unused variables.
> HAI-XXX Remove unused alkupvm and loppuvm

- docker-compose.yml
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/security/FileScanServiceITest.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/configuration/Configuration.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/security/FileScanService.kt
- services/hanke-service/src/main/resources/application.properties
Add a webclient to make http calls for file virus scanning. 
Associated changes in azure devops:
- https://dev.azure.com/City-of-Helsinki/haitaton/_git/haitaton-hanke-service-pipelines/pullrequest/4475
- Added CLAMAV_BASE_URL = clamav-rest-api.clamav.svc.cluster.local:3000 for development, testing, staging and production in: https://dev.azure.com/City-of-Helsinki/haitaton/_library?itemType=VariableGroups
At this point, there is no direct way to test this (other than unit tests). 
Functionality can however be tested by:
1. Running the whole stack in docker compose
2. shut down the backend
3. run backend via ./gradlew bootRun with the following code inserted to FileScanService:
```
@Scheduled(initialDelay = 1000, fixedDelay = 10000)
fun foo() {
scanFiles(setOf(Pair("testfile.pdf", …
```
> HAI-1533 Add virus scanning client for received files

- services/hanke-service/src/main/resources/db/changelog/changesets/031-add-default-value-for-hankeyhteystieto-yhteyshenkilo.yml
- services/hanke-service/src/main/resources/db/changelog/db.changelog-master.yaml
Add not null constraint with default value of empty list for hankeyhteystiet.yhteyshenkilot.
After deployment, you should be able to view hanke information in cloud environments.
> HAI Add not null constraint with default values for yhteyshenkilot

- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/email/EmailSenderServiceITest.kt
- services/hanke-service/src/test/resources/application-emailtest.properties
Since `EmailSenderServiceITest` is an integration test, Spring starts all services when running that test. But since it isn't a `DatabaseTest`, the database is connected in the default port. This is unacceptable, since tests shouldn't interfere with real environments.
Fix this by making `EmailSenderServiceITest` a `DatabaseTest`, so that a test database is properly used.
Run integration tests without having a database in port 5432. Or look at the test report for this PR.
> HAI-1525 Fix exception at the end of integration tests

- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/application/ApplicationServiceITest.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/permissions/HankeKayttajaServiceITest.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/allu/ApplicationPdfService.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/application/CustomerWithContacts.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/gdpr/GdprJsonConverter.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/permissions/HankeKayttajaService.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/allu/ApplicationPdfServiceTest.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/application/ContactTest.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/factory/AlluDataFactory.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/gdpr/GdprJsonConverterTest.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/logging/DisclosureLogServiceTest.kt
- services/hanke-service/src/test/resources/fi/hel/haitaton/hanke/application/applicationData.json
Application Contact.name is divided into firstName and lastName.
Note. Allu still expects name information to be a single name attribute. Hence, firstName and lastName needs to be mapped into a full name. Full name will be null if first and last names are null.
Note. Previously saved application data jsonb fields will contain the name information as a full name. These cases will have their firstName and lastName null. It should not cause errors but it might be a good idea to delete these rows from the db.
This update requires changes in the front-end too. When both are implemented, just create a cable report application and verify that contact data is handled correctly.
other info that the …
> HAI-1610 Change name to first and last name in Contact

- services/hanke-service/build.gradle.kts
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/HankeControllerITests.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/HankeServiceITests.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/application/ApplicationControllerITest.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/application/ApplicationServiceITest.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/attachment/AttachmentControllerITests.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/attachment/AttachmentServiceITests.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/domain/PublicHankeControllerITests.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/attachment/AttachmentController.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/application/AlluUpdateServiceTest.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/application/ApplicationControllerTest.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/application/ApplicationServiceTest.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/logging/ApplicationLoggingServiceTest.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/logging/DisclosureLogServiceTest.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/logging/HankeLoggingServiceTest.kt
Now that we're on Spring Boot 2.4, we can upgrade MockK and assertk to newer versions. This enables the use of `checkUnnecessaryStub()`, which checks whether all stubs are actually used. Unused stubs can be misleading.
Also, since Spring 5.3 that came with Spring Boot 2.4 enables us to use `@Nested` test classes in more places, use it in one as an example.
> HAI-1556 Upgrade test libraries

- services/hanke-service/build.gradle.kts
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/configuration/Configuration.kt
After upgrading spring boot version, attachment uploads seem to fail.
- MissingServletRequestPartException: Required request part 'liite' is not present
Problem seems to happen due to multipartresolver bean from apache. Spring Boot should work with multipart files without any additional configuration beans.
Removing the mentioned bean seems to solve the upload issue at least locally.
> HAI-1274 Fix multipart request param bug

- services/hanke-service/build.gradle.kts
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/HankeServiceITests.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/application/ApplicationServiceITest.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/attachment/AttachmentServiceITests.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/application/ApplicationService.kt
Upgrade Spring Boot  to 2.5
`getOne` has been deprecated, so replace with `getById`.
> HAI-1557 Spring Boot upgrade to 2.5

- services/hanke-service/build.gradle.kts
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/DatabaseTest.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/HankeServiceITests.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/logging/HankeLoggingServiceTest.kt
The upgrade brought with it a new version of AssertJ, which added an overloaded version of `allSatisfy`, which Kotlin can't separate from the previous one. After looking in to how to circumvent the issue, I found it simplest to replace those with asserts with assertk.
Also upgrade the two dependencies, which were giving security warnings in IDEA: PostgreSQL JDBC Driver and Testcontainers. Not that they would be the most critical, but you have to start somewhere.
Testcontainers had a change in 1.16.0 where they
> Only publish exposed ports (#4122)
This caused issues for us, since it seems like there has been a misundestanding on what exposed ports in Testcontainers mean. We were exposing a non-standard port in the Postgres container, probably to not collide with the database running on the …
> HAI-1558 Upgrade to Spring Boot 2.6

- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/security/OAuth2ResourceServerSecurityConfiguration.kt
The response from the userinfo query was read as a String -> String map, which broke down when the response contains `ad_groups`, which is an array.
Fix this by only reading a String -> Any map instead.
Alternative to #313
> HAI-1562 Fix auth for users with ad groups

- docker-compose.yml
- scripts/nginx/nginx.conf
- services/hanke-service/src/main/resources/application.properties
Increase allowed size of multipart files.
Changes:
1. Increase the allowed size for clamav rest api in docker-compose (local development).
2. Increase the allowed size for nginx (local development).
3. Increase the allowed size in application.properties (all envs.)
Files of size up to 100MB can be uploaded.
> HAI-1626 Increase allowed size of uploaded attachment files.

- services/hanke-service/build.gradle.kts
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/HankeServiceITests.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/HanketunnusServiceImplITest.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/attachment/application/ApplicationAttachmentServiceITest.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/geometria/GeometriatDaoImplITest.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/geometria/GeometriatServiceImplITest.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/logging/AuditLogServiceITests.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/permissions/PermissionServiceITest.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/tormaystarkastelu/TormaystarkasteluTormaysServicePGITest.kt
- services/hanke-service/src/integrationTest/resources/clear-db.sql
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/HankeServiceImpl.kt
- services/hanke-service/src/main/resources/application.properties
- services/hanke-service/src/main/resources/db/changelog/changesets/034-add-delete-cascade-to-hankekayttajat.yml
- services/hanke-service/src/main/resources/db/changelog/db.changelog-master.yaml
Remove `@Transactional` annotations from test classes, except from some single tests.
Having the transactions open for the duration of tests leads to the tests not reaching the database like they should. This means our tests won't test what they're supposed to. One bug avoided detection because of this (HAI-1618).
Dropping the annotations from test classes causes many tests to fail because the service methods don't manage their own transactions. This is because Open Session In View (OSIV) is enabled by default in Spring Boot, so the service methods have an open session when called inside a single dispatch.
Since we need to add `@Transactional` annotations to service methods anyway now, this is a good to disable OSIV and let the service layer manage their database sessions and …
> HAI-1617 Improve transaction handling

- services/hanke-service/build.gradle.kts
I checked with a Gradle plugin, which dependencies can be upgraded. These are only ones that we can upgrade at this time. Some upgrades need a newer Spring, Kotlin, or Java. Some were still in beta, so I didn't use those yet.
> HAI-1559 Miscellaneous dependency upgrades

- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/application/ApplicationServiceITest.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/email/EmailSenderServiceITest.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/application/ApplicationService.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/configuration/Configuration.kt
- services/hanke-service/src/main/resources/email/template/johtoselvitys-valmis.html.mustache
- services/hanke-service/src/main/resources/email/template/johtoselvitys-valmis.text.mustache
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/TestExtensions.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/application/ApplicationServiceTest.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/factory/AlluDataFactory.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/factory/ApplicationHistoryFactory.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/factory/HankeYhteystietoFactory.kt
Send the notification email only to the orderer of the application. That contact is where the applicant has filled in their own information.
This can only be tested in the local environment.
1. Make a johtoselvityshakemus.
2. Create a decision for it in Allu.
3. Check that there's a new email in http://localhost:3003/ 
This uses new test functionality enabled in HAI-1556 (#299, #300), so those PRs should be merged first. They are in turn waiting for HAI-1274 (#292).
> HAI-1601 Send email when johtoselvitys is ready

- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/attachment/application/ApplicationAttachmentServiceITest.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/application/ApplicationService.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/attachment/application/ApplicationAttachmentController.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/attachment/application/ApplicationAttachmentService.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/configuration/Configuration.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/application/ApplicationServiceTest.kt
Part 2/3 of sending attachments to Allu. After initial sending, if another attachment is added, it should be sent to Allu if application status is PENDING.
Note: the prevention of adding / deleting attachments after handling has started in Allu will be implemented in the next pr.
1. Create application, send to allu. Add attachment. Should be sent.
2. Create application, add attachments, should not send.
> HAI-1545 Send added attachment if application PENDING

- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/permissions/HankeKayttajaServiceITest.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/application/ApplicationService.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/permissions/HankeKayttajaService.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/permissions/KayttajaTunniste.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/application/ApplicationServiceTest.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/factory/HankeFactory.kt
Change the algorithm used by SecureRandom to one that doesn't enforce the use of `/dev/random`. The default constructor creates an instance that uses the `NativePRNG` algorithm when `java.security.egd` has been set to `file:/dev/urandom`, like we have in the cloud environments.
Earlier, using `SecureRandom.getInstanceStrong()` and `NativePRNGBlocking` caused generating user tokens to hang for several minutes, while SecureRandom was waiting for more randomness from `/dev/random`.
Improve logging related to sending applications. The slowness was really hard to diagnose because of too little logging.
This can only be tested after merging to dev. The new algorithm was tested already.
> HAI-1633 Change randomness algorithm

- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/IntegrationTestConfiguration.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/application/ApplicationServiceITest.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/gdpr/GdprControllerITests.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/gdpr/GdprServiceITest.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/allu/ApplicationPdfService.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/gdpr/GdprController.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/gdpr/GdprService.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/TestExtensions.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/application/ApplicationServiceTest.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/factory/AlluDataFactory.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/factory/HankeFactory.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/gdpr/GdprServiceTest.kt
If the user has created applications, we delete them if they're still pending. If they've been sent to Allu and have progressed to handling, we refuse to delete them.
Fixed GET endpoint to return 204 instead of 404 when there's no information for a user. Also refactor the GET endpoint to use the GdprService added here.
1. Change haitaton.gdpr.disabled=true to haitaton.gdpr.disabled=false in application.properties.
2. Create some applications.
3. Use Postman or cURL to call http://localhost:3001/api/swagger-ui/index.html#/gdpr-controller/deleteUserInformation with your own userid.
4. It should return 204 No Content and remove the applications.
5. Create some applications.
6. Move one of the to handling in Allu.
7. Repeat step 3.
8. It should return 403 Forbidden with a reason why the …
> HAI-1303 Add endpoint for deleting personal information

- services/hanke-service/src/main/resources/application.properties
Remove username and password from email properties. In cloud environments, they caused the email client to use authentication even though we tell it not to do that.
No environment should use authentication for sending emails, so they are safe to remove.
> HAI Remove email username and password

- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/application/ApplicationServiceITest.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/application/ApplicationData.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/application/ApplicationDataMapper.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/application/ApplicationEntity.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/application/ApplicationService.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/attachment/application/ApplicationAttachmentService.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/application/ApplicationDataMapperTest.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/application/ApplicationServiceTest.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/factory/AlluDataFactory.kt
Remove identificationNumber from applicationdata used in application endpoints. Front-end does not need the value.
Value (hankeTunnus) is set when applicationdata is mapped to alludata.
Additional: similar thing is done with clientApplicationKind. The same value as workDescription field is used here as requested by Allu people (to sort incoming applications by description). 
Send application to Allu and check hanketunnus.
Haitaton:
Allu:
> HAI-1688 Add real hankeTunnus to allu cable report identificationNumber

- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/HankeControllerITests.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/attachment/hanke/HankeAttachmentControllerITests.kt
- services/hanke-service/src/integrationTest/resources/application-test.properties
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/ControllerExceptionHandler.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/HankeController.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/HankeError.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/attachment/hanke/HankeAttachmentController.kt
- services/hanke-service/src/main/resources/application.properties
Add a possibility to disable endpoints in certain environments.
Boolean environment variable HAITATON_FEATURE_HANKE_EDITING can be used to control this. The value should be false (disabled) in production and staging. Default value is true (enabled), so there is no need to set this elsewhere.
Related pr: https://dev.azure.com/City-of-Helsinki/haitaton/_git/haitaton-hanke-service-pipelines/pullrequest/4844
Endpoints described in the jira ticket should work in every environment except production and staging. In production and staging they should respond 404.
> HAI-1621 Disable endpoints that are not yet ready for production

- services/hanke-service/src/main/resources/application.properties
Add the correct sender to email properties.
This is the same in all environments, so it's easier to change the default than to set this to all environments separately.
> HAI Add the correct sender to email properties

- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/HankeServiceITests.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/allu/CableReportServiceAlluITests.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/application/ApplicationServiceITest.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/allu/AlluCommonDomain.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/allu/CableReportService.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/allu/CableReportServiceAllu.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/application/ApplicationService.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/attachment/application/ApplicationAttachmentService.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/application/ApplicationServiceTest.kt
When sending an application to Allu for the first time, we need to send all attachments at the same time. But if one of the uploads fails, the upload fails from Haitaton perspective, so the application is not marked as sent.
From Allu perspective, however, the application was uploaded successfully, and the officer looking at it doesn't know there are attachments missing.
When the user resends the application from Haitaton, a duplicate is created in Allu.
The proper way to fix this would be:
1. Mark the uploaded application as sent to Allu, even if the attachments uploads fail. Set the status to PENDING_CLIENT in both Allu and Haitaton.
2. Mark the attachments that were sent successfully as sent.
3. Tell the user that the sending failed and ask them to retry.
4. When the user tries to …
> HAI-1679 Cancel application if initial attachment upload fails

- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/application/ApplicationControllerITest.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/application/ApplicationData.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/application/CustomerWithContacts.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/validation/ApplicationValidator.kt
Add validation to prevent start time be after end time. Application POST and PUT endpoints should not accept application startTime to be after endTime.
Additional: I refactored the whole application data validation. It is more than likely, that more validation will be implemented in the future, and I think this commit will make that work a bit easier.
Set start time to be after end time. Endpoint should return 400.
> HAI-1704 Add validation to prevent start time be after end time.

- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/attachment/common/AttachmentValidator.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/attachment/AttachmentValidatorTest.kt
Accept filenames in uppercase. 
Try to add an attachment with TXT or PNG or similar as the extension.
> HAI-1737 Accept filenames in uppercase

- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/attachment/hanke/HankeAttachmentService.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/validation/ApplicationValidator.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/validation/HankePublicValidator.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/validation/Validators.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/factory/AlluDataFactory.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/validation/ApplicationValidatorTest.kt
Validations added:
- There is at most one orderer
- Text fields don't have just blanks
- Country has a country code (UI uses constant FI here)
On top of the earlier:
- Registry key (business-id) is valid
- Start date is not after the end date
I ended up rewriting the validation using the same validators used in validating if a hanke is public or not. I refactored that quite a bit, though.
This is easiest to verify with the UI before https://github.com/City-of-Helsinki/haitaton-ui/pull/323 is merged.
> HAI-1748 Add more validation for application data

- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/attachment/application/ApplicationAttachmentControllerITest.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/attachment/application/ApplicationAttachmentServiceITest.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/attachment/hanke/HankeAttachmentServiceITests.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/attachment/application/ApplicationAttachmentService.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/attachment/common/AttachmentEntity.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/attachment/common/AttachmentMetadata.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/attachment/hanke/HankeAttachmentService.kt
- services/hanke-service/src/main/resources/db/changelog/changesets/036-drop-scanstatus-from-attachments.yml
- services/hanke-service/src/main/resources/db/changelog/db.changelog-master.yaml
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/factory/AttachmentFactory.kt
Drop the unused scan status column from both attachment tables. Remove it from the entities and other places that use it.
The frontend seems to except the backend to return the scan status, even though it doesn't use it for anything. Add a constant `"scanStatus": "OK"` to each attachment object returned from the backend.
> HAI-1758 Drop scan status from attachments

- services/hanke-service/README.md
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/allu/CableReportServiceAlluITests.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/application/ApplicationServiceITest.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/attachment/application/ApplicationAttachmentControllerITest.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/attachment/application/ApplicationAttachmentServiceITest.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/attachment/hanke/HankeAttachmentControllerITests.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/attachment/hanke/HankeAttachmentServiceITests.kt
- services/hanke-service/src/integrationTest/resources/clear-db.sql
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/allu/CableReportService.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/allu/CableReportServiceAllu.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/application/ApplicationEntity.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/application/ApplicationService.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/attachment/application/ApplicationAttachmentService.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/attachment/common/AttachmentContentEntity.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/attachment/common/AttachmentContentService.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/attachment/common/AttachmentEntity.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/attachment/common/Exceptions.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/attachment/hanke/HankeAttachmentService.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/configuration/Configuration.kt
- services/hanke-service/src/main/resources/application.properties
- services/hanke-service/src/main/resources/db/changelog/changesets/037-add-delete-cascade-for-attachments.yml
- services/hanke-service/src/main/resources/db/changelog/changesets/038-add-attachment-content-tables.sql
- services/hanke-service/src/main/resources/db/changelog/db.changelog-master.yaml
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/factory/AlluDataFactory.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/factory/AttachmentFactory.kt
Improve the memory use around attachments by separating the binary
content of the attachment files into separate tables and entities. Make
sure to only load the attachment content only when needed, and
separately for each attachment.
Also, remove oneToMany mapping of application and attachments. Add on
delete cascade to allow deletion of the owning entity of attachments.
Limit the concurrency on sending all attachments to Allu. Send at most 4
attachments cconcurrently, hopefully meaning only those 4 need their
content to be loaded into memory.
When testing locally, Allu didn't accept files fast enough when the
concurrency was set at four. Or maybe my connection couldn't transfer
the files fast enough.
There are possibly any number of environment-specific things that affect
how many files …
> HAI-1758 Split attachment content to separate tables

- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/Persistence.kt
The EXTRACT function seems to work slightly differently in PostgreSQL
14. The name of the result column is `extract` instead of the `date_part` it was in PostgreSQL 13. Given an alias to the column to make the query work like it did before.
> HAI Fix hanketunnus generation on Postgresql 14

- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/Persistence.kt
The EXTRACT function seems to work slightly differently in PostgreSQL
14. The name of the result column is `extract` instead of the `date_part` it was in PostgreSQL 13. Given an alias to the column to make the query work like it did before.
> HAI Fix hanketunnus generation on Postgresql 14 (#359)

- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/application/ApplicationControllerITest.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/HankeServiceImpl.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/application/Application.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/application/ApplicationController.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/validation/ApplicationValidator.kt
Add missing validation to hakemushankegeneration endpoint. We have a pretty decent and thorough validation in place for Application instances so I did not want to copypaste the same validation for this special case of hanke generation. Instead, I added an interface HaitatonApplication which is implemented by Application and CableReportWithoutHanke. This way we can use the validator to hanke HaitatonApplications and validate both types of applications.
Additional: replaced toNewApplication extension function as a normal class function. There was no need to use extension function.
POST http://localhost:3001/api/hakemukset/johtoselvitys
```
{
"id": 148,
"alluid": null,
"alluStatus": null,
"applicationIdentifier": null,
"applicationType": "CABLE_REPORT",
"applicationData": { …
```
> HAI-1792 Add validation to hakemus hanke generation endpoint

- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/attachment/AttachmentTestUtil.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/attachment/application/ApplicationAttachmentServiceITest.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/attachment/hanke/HankeAttachmentServiceITests.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/ControllerExceptionHandler.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/HankeError.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/attachment/application/ApplicationAttachmentService.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/attachment/common/AttachmentEntity.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/attachment/common/AttachmentMetadata.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/attachment/common/AttachmentValidator.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/attachment/common/Exceptions.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/attachment/hanke/HankeAttachmentService.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/attachment/AttachmentValidatorTest.kt
Sanitize any special characters (`\/:*?"<>|`) in attachment file names. The special characters are replaced with underscores (`_`).
Change id field in attachment metadata classes to non-nullable. There's no reason to create a metadata presentation of an attachment if it's not saved to database.
1. I created a file with all sorts of special characters, separated by marking characters.
```shell
echo "Hassuja merkkejä" > 'p%a&c:a*q?s b\q"s l<g>p|.txt'
```
2. Then I added it to an application as an attachment through frontend.
3. The summary page shows the sanitized filename: ![image](https://github.com/City-of-Helsinki/haitaton-backend/assets/604238/6221c7f1-ad5c-4112-a1dd-d4e229319a5c)
> HAI-1710 Sanitize special chars in attachment filenames

- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/allu/CableReportServiceAllu.kt
- services/hanke-service/src/main/resources/application.properties
Allu has trouble accepting attachments in a reasonable amount of time. Let's try to mitigate the issue by disabling concurrency and setting a slightly higher timeout value.
Can't be tested, since the problem is with Allu's production environment.
> HAI Increase attachment upload timeout and disable concurrency

- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/application/ApplicationControllerITest.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/application/ApplicationServiceITest.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/HankeError.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/Utils.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/application/ApplicationController.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/application/ApplicationService.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/application/validation/CableReportErrorValidation.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/application/validation/CableReportMissingValidation.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/validation/ApplicationValidator.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/application/ApplicationServiceTest.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/factory/AlluDataFactory.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/gdpr/GdprJsonConverterTest.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/logging/DisclosureLogServiceTest.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/validation/ApplicationDataValidatorTest.kt
- services/hanke-service/src/test/resources/fi/hel/haitaton/hanke/application/applicationData.json
It is ok for a draft application to have missing data that is not yet set.
However, when sending the application, all required fields must be present. This commit adds validation to be performed on application creation and update before sending the data to Allu.
1. Create johtoselvitys, fill for example just the first page. 
2. Save and quit. Take note of the application id.
3. For example with postman: POST http://localhost:3001/api/hakemukset/{application_id}/send-application
4. Expected response from the backend should be similar to (status 400):
```
{
"errorMessage": "Application contains invalid data",
"errorCode": "HAI2008",
"errorPaths": [
"startTime",
"endTime",
"customerWithContacts.customer.type",
"customerWithContacts.customer.name", …
```
> HAI-1756 Add validation for missing data when sending application

- services/hanke-service/build.gradle.kts
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/allu/CableReportServiceAlluITests.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/configuration/SchedulingConfig.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/security/AccessRules.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/security/OAuth2ResourceServerSecurityConfiguration.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/application/ApplicationServiceTest.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/validation/ApplicationDataValidatorTest.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/validation/ApplicationValidatorTest.kt
Update Spring Security to 5.8, which is a transitional version, making the jump to Spring Security 6.0 easier. Update Spring Boot to the latest version in the latest 2.7-branch. Update misc packages that can be updated now, and mark packages that can or need to be updated while upgrading to Spring Boot 3.0.
Assertk has deprecated the `assertThat {}` method that takes a function parameter. It has been replaced with the usual `assertThat()` for success cases and with `assertFailure {}` for cases that throw an exception.
> HAI-1560 Prepare for Spring upgrade

- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/HankeController.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/HankeYhteystietoEntity.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/PublicHankeController.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/StatusController.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/application/ApplicationController.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/attachment/application/ApplicationAttachmentController.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/attachment/hanke/HankeAttachmentController.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/domain/Hanke.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/domain/HankeYhteystieto.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/domain/Hankealue.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/domain/Perustaja.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/geometria/Geometriat.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/tormaystarkastelu/TormaystarkasteluTulos.kt
Documentation added where it was missing. Furthermore, did some fixes on documented error responses. Endpoints will not return the thrown error. They return the error code returned by exceptionhandlers.
Did not implement documentation for organisations and geometry controllers as they are soon deleted.
Run with docker compose and verify openapi: http://localhost:3001/api/swagger-ui/index.html
> HAI-1409 Add missing openapi documentation

- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/IntegrationTestConfiguration.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/permissions/HankeKayttajaControllerITest.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/permissions/HankeKayttajaServiceITest.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/HankeService.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/HankeServiceImpl.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/Persistence.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/logging/AuditLogEntry.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/logging/DisclosureLogService.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/permissions/HankeKayttaja.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/permissions/HankeKayttajaController.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/permissions/HankeKayttajaService.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/permissions/PermissionService.kt
- services/hanke-service/src/main/resources/db/changelog/changesets/042-add-indices-to-hanke-kayttaja.yml
- services/hanke-service/src/main/resources/db/changelog/db.changelog-master.yaml
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/factory/AuditLogEntryFactory.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/factory/HankeKayttajaFactory.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/logging/DisclosureLogServiceTest.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/validation/ApplicationDataValidatorTest.kt
Add endpoint to view hanke kayttajas and their privileges on hanke.
Additional: removed a couple functions from HankeService as they were not used.
Create an application with contact persons and send it to Allu. After that:
- GET http://localhost:3001/api/hankkeet/{createdHanke}/kayttajat
> HAI-1509 Add endpoint to get hanke kayttaja data

- docker-compose.yml
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/IntegrationTestConfiguration.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/testdata/TestDataControllerDisabledITest.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/testdata/TestDataControllerEnabledITest.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/testdata/TestDataServiceITest.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/configuration/OpenApiConfiguration.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/security/AccessRules.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/testdata/TestDataController.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/testdata/TestDataService.kt
- services/hanke-service/src/main/resources/application.properties
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/application/ApplicationControllerTest.kt
Allu removes all of its data in the test environment when it's updated. To mitigate problems this causes to Haitaton dev and test environments, add an endpoint that removes the linking between Haitaton applications and Allu. The links are non-functional after an Allu update anyway.
Make the endpoint callable directly from Swagger UI, so it calling it doesn't require a developer.
The endpoint is only visible and accessible from specific environments, namely dev and test environments. This is accomplished with environment variables.
Create an application and then call the endpoint to unlink it.
or other location: TODO
> HAI-1842 Add endpoint for unlinking applications from Allu in dev and test

- README.md
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/permissions/HankeKayttajaControllerITest.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/permissions/HankeKayttajaServiceITest.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/HankeController.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/HankeError.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/application/ApplicationController.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/attachment/application/ApplicationAttachmentController.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/attachment/hanke/HankeAttachmentController.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/configuration/FeatureFlags.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/configuration/OpenApiConfiguration.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/permissions/HankeKayttaja.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/permissions/HankeKayttajaController.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/permissions/HankeKayttajaService.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/permissions/KayttajaTunniste.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/permissions/PermissionService.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/permissions/PermissionUpdate.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/permissions/Permissions.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/testdata/TestDataController.kt
- services/hanke-service/src/main/resources/application.properties
- services/hanke-service/src/main/resources/db/changelog/changesets/043-add-another-index-to-hanke-kayttaja.yml
- services/hanke-service/src/main/resources/db/changelog/db.changelog-master.yaml
Add API for changing the permissions of hanke kayttajat.
Audit logging will be added in a separate PR.
Add a security scheme to the OpenAPI configuration. This enables the use of the Swagger UI by copying over your bearer token. Reformat some OpenAPI descriptions, since they were shown as code blocks.
You can use Swagger UI to send requests to test the API.
or other location: README for Swagger UI authentication
> HAI-1527 API for changing permissions

- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/HankeControllerITests.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/SpringDocITest.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/application/ApplicationControllerITest.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/attachment/AttachmentTestUtil.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/attachment/application/ApplicationAttachmentControllerITest.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/attachment/hanke/HankeAttachmentControllerITests.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/permissions/HankeKayttajaControllerITest.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/permissions/HankeKayttajaServiceITest.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/permissions/PermissionServiceITest.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/HankeController.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/HankeError.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/PublicHankeController.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/application/ApplicationController.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/permissions/HankeKayttaja.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/permissions/HankeKayttajaController.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/permissions/HankeKayttajaService.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/permissions/KayttajaTunniste.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/permissions/PermissionService.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/security/AccessRules.kt
- services/hanke-service/src/main/resources/application.properties
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/ControllerTest.kt
Add an endpoint that takes a user token in the request body and creates a permission for the user to the hanke the token is associated with.
The token is deleted from DB after use, since it can't be used again anyway.
The motivation is to activate the permissions that have been created for a contact person. When creating a contact person we don't know which user the contact person is, so we create a user token, that's emailed to the contact. The contact can then use this endpoint (through UI) to activate the given permission, i.e. change the token placeholder to an actual permission.
As an unreleated change, configure springdoc to use application/json as the default for all API descriptions. This way, we don't have to specify the media type for every single response, including all the …
> HAI-1873 Add API for identifying a user

- README.md
- githooks/pre-push
- githooks/pre-push.d/build
I want to have a custom pre-push git hook, which isn't useful for other people. If I changed the existing one, it would get overwritten by the gradle script.
Replace the pre-push script with a script that runs all scripts from a folder. Add the maintained pre-push script as one of the files in that folder.
That is,
- `githooks/pre-push` is installed as `.git/hooks/pre-push`
- All files under `githooks/pre-push.d` are copied under `.git/hooks/pre-push.d
- A developer can add custom scripts to `.git/hooks/pre-push.d` and they won't be overwritten by the gradle build script
- `.git/hooks/pre-push` runs all scripts under `.git/hooks/pre-push.d` and fails if any of them fail
With this structure, developers can have custom hooks while still keeping the build-hook maintained in version control. …
> HAI Allow for custom git pre-push hooks

- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/application/ApplicationServiceITest.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/permissions/HankeKayttajaServiceITest.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/permissions/PermissionServiceITest.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/HankeServiceImpl.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/application/ApplicationService.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/logging/HankeKayttajaLoggingService.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/logging/PermissionLoggingService.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/permissions/HankeKayttaja.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/permissions/HankeKayttajaService.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/permissions/Kayttooikeustaso.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/permissions/PermissionService.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/permissions/Permissions.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/TestExtensions.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/application/ApplicationServiceTest.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/factory/AlluDataFactory.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/factory/HankeFactory.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/factory/HankeKayttajaFactory.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/factory/KayttajaTunnisteFactory.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/logging/HankeKayttajaLoggingServiceTest.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/logging/PermissionLoggingServiceTest.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/test/AuditLogEntryAsserts.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/test/AuditLogEntryEntityAsserts.kt
Add logging for creating permissions, hankekayttaja and hanketunniste.
Adding the audit reasonably required some refactoring:
- In PermissionService, make the old setPermission function be explicitly for creating new permisisions, so logging can be added.
- Move updating the kayttooikeustaso of a permission to PermissionService to centralize modifications and logging.
- In HankeKayttajaService, make the saveUser function to handle creating new users explicitly so that logging can be added.
- Rename kayttooikeustaso in PermissionEntity to kayttooikeustasoEntity and add a new getter for the actual kayttooikeustaso, so that `permissionEntity.kayttooikeustaso` is required instead of the old `permissionEntity.kayttooikeustaso.kayttooikeustaso`.
- Change references to …
> HAI-1875 Add audit logging for new users and tokens

- githooks/pre-push
- services/hanke-service/build.gradle.kts
There was an issue with the shebang line, it didn't work for everyone unless it said bash instead of sh. While at it, add some robustness to bash commands and a bit more logging and documentation.
> HAI Fix for githooks

- email/kayttaja-lisatty-hakemus.mjml
- email/kayttaja-lisatty-hanke.mjml
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/HankeControllerITests.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/email/EmailSenderServiceITest.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/permissions/HankeKayttajaServiceITest.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/HankeController.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/email/EmailSenderService.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/permissions/HankeKayttaja.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/permissions/HankeKayttajaService.kt
- services/hanke-service/src/main/resources/email/template/kayttaja-lisatty-hakemus.html.mustache
- services/hanke-service/src/main/resources/email/template/kayttaja-lisatty-hakemus.text.mustache
- services/hanke-service/src/main/resources/email/template/kayttaja-lisatty-hanke.html.mustache
- services/hanke-service/src/main/resources/email/template/kayttaja-lisatty-hanke.text.mustache
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/factory/HankeFactory.kt
Include the email sending feature to creation of new hanke users.
Note: this commit does not include sending of application invitations. It will be implemented on another commit.
Additional: fix a bug in hanke controller where .copy function did not copy fields that are not in the hanke constructor.
Apart from unit tests, there is no easy way of verifying this. Verifying the outgoing email would require a hanke with contact persons. That depends on: https://helsinkisolutionoffice.atlassian.net/browse/HAI-1586 . Furthermore, having a hankekayttaja for hanke creator depends on this: https://helsinkisolutionoffice.atlassian.net/browse/HAI-1348
However, this feature is guarded by a feature flag so it should be safe to have some of this as unused code for now.
Please …
> HAI-1526 Send hanke invitation emails

- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/permissions/KayttooikeustasoEntityITest.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/permissions/Permissions.kt
- services/hanke-service/src/main/resources/db/changelog/changesets/045-add-new-permission-code.sql
- services/hanke-service/src/main/resources/db/changelog/db.changelog-master.yaml
Add a new permission code for resending invitations. This permission code will be checked when the user calls the API for resending.
Resending the invitations doesn't fit any of the existing permissions and the group of kayttooikeustaso who can access it doesn't match any existing permission.
> HAI-1514 Add permission code for resending invitations

- docker-compose.yml
Add REACT_APP_OIDC_CLIENT_ID to docker compose config for Haitaton UI. This enables changing from Helsinki AD login to Suomi.fi login quickly without rebuilding the UI.
Just edit the value in docker-compose.yml and then restart the service without rebuilding:
```sh
docker-compose stop haitaton-ui && docker-compose up -d --no-deps haitaton-ui
```
> HAI Add OIDC client id to docker compose config

- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/application/ApplicationServiceITest.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/permissions/HankeKayttajaServiceITest.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/permissions/HankeKayttajaService.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/permissions/KayttajaTunniste.kt
- services/hanke-service/src/main/resources/db/changelog/changesets/046-remove-sentat-from-tunniste.yml
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/factory/KayttajaTunnisteFactory.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/logging/HankeKayttajaLoggingServiceTest.kt
Remove the sentAt field and column from KayttajaTunniste.
We are recreating the tokens whenever they are sent. So the createdAt and sentAt of the tokens would always be the same value, or at least within a couple of milliseconds from each other.
> HAI-1514 Remove sentAt from KayttajaTunniste

- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/permissions/HankeAuthorizerITest.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/permissions/HankeKayttajaAuthorizerITest.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/permissions/HankeKayttajaControllerITest.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/permissions/HankeKayttajaServiceITest.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/logging/HankeKayttajaLoggingService.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/permissions/HankeKayttaja.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/permissions/HankeKayttajaAuthorizer.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/permissions/HankeKayttajaController.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/permissions/HankeKayttajaService.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/domain/UserContactTest.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/factory/HankeKayttajaFactory.kt
Add an endpoint for resending the invitation emails. The email is identical to the one that was sent the first time the user was added as a contact.
Removes the old invitation token and link and creates a new one. This resets any period of validity for the token. It also means the original and any previous emails will no longer work.
1. Setup a johtoselvitys with contacts.
2. Use [Swagger UI](http://localhost:3001/api/swagger-ui/index.html#/hanke-kayttaja-controller/resendInvitations) to call the endpoint.
3. Check [smtp4dev](http://localhost:3003/) that the email was sent.
or other location: -
> HAI-1514 Add API for resending invitations

- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/HankeServiceITests.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/permissions/HankeKayttajaControllerITest.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/permissions/HankeKayttajaServiceITest.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/HankeService.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/HankeServiceImpl.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/permissions/HankeKayttajaController.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/permissions/HankeKayttajaService.kt
Add a response to identification API with the ID of the activated user and tunnus and name of the associated hanke.
Also add a missing audit log for deleting the tunniste to the identification run.
When identifying, the endpoint should return a response.
or other location: https://helsinkisolutionoffice.atlassian.net/wiki/spaces/HAI/pages/8219721755/K+ytt+oikeuksien+hallinta
> HAI-1940 Add response to identification API

- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/Constants.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/validation/HankeValidator.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/validation/Validators.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/HankeControllerTest.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/factory/HankeFactory.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/validation/HankeValidatorTest.kt
The database is limited to 100 characters for nimi and hankealue. To avoid database errors, limit the length of nimi and hankealue to the same 100 characters in validation.
Also, refactor HankeValidator to reuse some of the code better. Use the Validators-methods for finding the paths with errors. Then map those paths to validator context violations.
Add comprehensive tests for HankeValidator to know the refactoring didn't change behaviour.
Refactor HankeControllerTest to use Mockk instead of Mockito. It was the last place Mockito was used. I thought I needed it for this PR, but I ended up doing a separate test class. I had already refactored it, so I decided to add the changes here anyway.
Try to create hanke with a name of over 100 characters. The error the backend gives should make …
> HAI-1872 Add validation for nimi and hankealue nimi lengths

- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/HankeServiceITests.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/application/ApplicationServiceITest.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/logging/AuditLogServiceITests.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/permissions/HankeKayttajaControllerITest.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/permissions/HankeKayttajaServiceITest.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/permissions/HankeKayttaja.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/permissions/HankeKayttajaController.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/permissions/HankeKayttajaService.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/permissions/KayttajaTunniste.kt
- services/hanke-service/src/main/resources/db/changelog/changesets/047-reverse-tunniste-foreign-key-direction.sql
- services/hanke-service/src/main/resources/db/changelog/db.changelog-master.yaml
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/factory/HankeKayttajaFactory.kt
- services/hanke-service/src/test/resources/application-test.properties
It makes more sense that KayttajaTunniste has a foreign key for HankeKayttaja than the reverse. This way it's impossible to have an orphaned tunniste hanging around.
1. Send a johtoselvityshakemus with various contacts.
2. Check that they have tokens.
3. Cancel the generated hanke.
4. Check that the tokens were deleted.
or other location: https://helsinkisolutionoffice.atlassian.net/wiki/spaces/HAI/pages/8286371894/Tekninen+toteutuskuvaus#K%C3%A4ytt%C3%A4j%C3%A4roolit-ja-oikeudet
This was done on top of #430, since that adds logic for recreating tokens.
> HAI-1852 Reverse foreign key between HankeKayttaja and KayttajaTunniste

- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/Persistence.kt
Remove ykt value from tyomaatyyppi enum. This infromation is handled via boolean onYKTHanke field in Hanke object. Remove it from the enum as redundant.
> HAI-1898 Remove ykt value from tyomaatyyppi enum

- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/HankeServiceITests.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/HankeServiceImpl.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/HankeYhteystietoEntity.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/Utils.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/allu/AlluCommonDomain.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/application/CustomerWithContacts.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/domain/HankeYhteystieto.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/domain/TypeAliases.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/gdpr/GdprInfo.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/validation/HankePublicValidator.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/validation/HankeValidator.kt
- services/hanke-service/src/main/resources/db/changelog/changesets/048-add-y-tunnus-to-hankeyhteystieto.yml
- services/hanke-service/src/main/resources/db/changelog/db.changelog-master.yaml
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/HankeMapperTest.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/UtilsKtTest.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/factory/HankeYhteystietoFactory.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/validation/HankePublicValidatorTest.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/validation/HankeValidatorTest.kt
Add ytunnus for hanke contacts. 
Ytunnus is required for public hanke, if tyyppi is YRITYS or YHDISTYS.
Ytunnus should be saved if it is submitted in the UI. Hanke status will turn public if required fields are present, including y-tunnus.
> HAI-1931 Add ytunnus for hanke contacts

- services/hanke-service/build.gradle.kts
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/Constants.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/logging/Persistence.kt
- services/hanke-service/src/main/resources/application.properties
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/factory/ApplicationHistoryFactory.kt
- Updates Jackson to 2.15, which changes ZonedDateTime deserialization.
- 2021-02-01T19:49:04.051348600Z[UTC] will be just 2021-02-01T19:49:04.051348600Z as Z and UTC mean the same thing.
- I changed TZ_UTC accordingly.
- See: https://github.com/FasterXML/jackson/wiki/Jackson-Release-2.15#changes-behavior-other
- Version specific dialects are removed from hibernate (see spring.jpa.database-platform).
- Changed dialect to PostgreSQLDialect
- See: https://github.com/hibernate/hibernate-orm/blob/6.0/migration-guide.adoc#version-specific-and-spatial-specific-dialects-are-deprecated
> HAI-1898 Update Spring Boot to 3.1.4

- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/HankeControllerITests.kt
- services/hanke-service/src/integrationTest/resources/fi/hel/haitaton/hanke/logging/expectedHankeWithPoints.json.mustache
- services/hanke-service/src/integrationTest/resources/fi/hel/haitaton/hanke/logging/expectedHankeWithPolygon.json.mustache
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/HankeMapper.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/HankeServiceImpl.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/tormaystarkastelu/TormaystarkasteluLaskentaService.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/tormaystarkastelu/TormaystarkasteluTormaysServicePG.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/tormaystarkastelu/TormaystarkasteluTulos.kt
- services/hanke-service/src/main/resources/db/changelog/changesets/049-add-bus-and-tram-indexes.sql
- services/hanke-service/src/main/resources/db/changelog/db.changelog-master.yaml
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/factory/HankeFactory.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/tormaystarkastelu/TormaystarkasteluLaskentaServiceTest.kt
In törmäystarkastelu, save bus and tram indexes separately. Remove the old joukkoliikenneindeksi from the DB.
Also bring the tormaystarkastelutulos table up to match the current entity. Changes to the entity have not been reflected in the table.
Return the new indexes separately from the API. Also return the old joukkoliikenneindeksi for compatibility, but calculate it's value on the fly from the bus and tram indexes.
Also remove `equals` and `hashCode` from `TormaystarkasteluTulosEntity`. The entities are not placed in sets or used as keys in a HashMap, so they are not needed. They were never called, which shows up as an error in test coverage reports.
Add tests for TormaystarkasteluLaskentaService. I perhaps added more tests than strictly necessary. I wanted to get full coverage and - …
> HAI-1876 Separate buses and trams to separate indexes

- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/HankeServiceITests.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/application/ApplicationControllerITest.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/gdpr/GdprControllerITests.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/application/Application.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/application/ApplicationController.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/logging/AuditLogEntry.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/logging/DisclosureLogService.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/TestExtensions.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/logging/DisclosureLogServiceTest.kt
Decisions contain personal information, so we need to log who we give what information to.
We can't read the personal information from inside the PDF decision, but we can log the metadata about the decision, which is the same as metadata about the application. This shows the exact version of the decision (in applicationIdentifier), which can then be (manually) matched against the content of the file if necessary.
Download a decision. The audit log should appear in the audit_logs table.
> HAI-1970 Add decision downloads to audit logs

- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/application/ApplicationServiceITest.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/HankeServiceImpl.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/application/ApplicationService.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/attachment/hanke/HankeAttachmentService.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/configuration/Configuration.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/domain/UserContact.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/gdpr/GdprService.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/permissions/HankeKayttajaService.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/application/ApplicationServiceTest.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/domain/UserContactTest.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/factory/AlluDataFactory.kt
When application is updated after initial send, create tokens for new contacts and send notification emails. A contact with an email address that was not present in the previous application is considered a new contact.
Additional: 
- Change application update operation so that application is saved, and the saved data is then sent to Allu (this feels a bit more logical order of operations at least for me).
- Add feature flags to prevent token creations and related emails on applications in production.
- Fix typo in hanke attachment service.
- Refactor ApplicationServiceTest class to use nested classes / have some structure.
1. Send johtoselvitys to Allu.
2. Modify contacts after send. New email addresses have access to hanke and receive emails about hanke and application.
or other …
> HAI-1896 Create hanke users after allu update and send emails

- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/application/ApplicationData.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/domain/UserContact.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/logging/DisclosureLogService.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/factory/AuditLogEntryFactory.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/logging/DisclosureLogServiceTest.kt
It's potentially useful to have the roles of the application contacts in the audit logs. This needs some extra work since the role is determined by the context, not the actual Customer / Contact objects.
Open an application and check the audit_logs table.
> HAI-1971 Add role information to application contact audit logs

- README.md
- githooks/pre-push.d/build
- services/hanke-service/build.gradle.kts
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/HankeServiceITests.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/application/ApplicationServiceITest.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/permissions/HankeKayttajaServiceITest.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/HankeServiceImpl.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/Persistence.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/application/ApplicationService.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/domain/Hanke.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/domain/PublicHanke.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/permissions/HankeKayttajaController.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/permissions/HankeKayttajaService.kt
- services/hanke-service/src/main/resources/db/changelog/changesets/050-make-nimi-mandatory-in-hanke.yml
- services/hanke-service/src/main/resources/db/changelog/db.changelog-master.yaml
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/application/ApplicationServiceTest.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/factory/HankeFactory.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/validation/HankePublicValidatorTest.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/validation/HankeValidatorTest.kt
Name is one of the few things we require every hanke to have from the first draft. There needs to be a name for the hanke to distinguish it from other hanke.
Since every hanke must have a name, we can make the associated field non-nullable. This simplifies code referring to the name.
Also, make the `check` Gradle task depend on the `integrationTest` task. This way, we can run `./gradlew check` instead of `./gradlew build integrationTest`.
> HAI-1893 Make nimi always mandatory in Hanke

- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/HankeControllerITests.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/HankeServiceITests.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/application/ApplicationServiceITest.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/attachment/hanke/HankeAttachmentServiceITests.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/geometria/GeometriatServiceImplITest.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/permissions/HankeKayttajaServiceITest.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/HankeController.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/HankeService.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/HankeServiceImpl.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/configuration/Configuration.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/domain/BaseHanke.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/domain/CreateHankeRequest.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/domain/Hanke.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/domain/Hankealue.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/tormaystarkastelu/TormaystarkasteluLaskentaService.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/validation/HankeValidator.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/validation/Validators.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/HankeControllerTest.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/HankeMapperTest.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/factory/AlluDataFactory.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/factory/CreateHankeRequestBuilder.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/factory/HankeFactory.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/factory/HankeYhteystietoFactory.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/tormaystarkastelu/TormaystarkasteluLaskentaServiceTest.kt
Add a new DTO class for creating hanke. It only has the fields that the user can decide directly. I.e. the DTO doesn't have any fields that are generated or calculated from other fields. This means there's no need to sanitize its contents or select which fields should be read. It also means the OpenAPI documentation is a lot more relevant.
Using the same request for the creation of the entity enables us to make many fields in the ubiquitous Hanke class non-nullable. This is not done in this PR, however.
1. Create a hanke.
2. It should work.
> HAI-1893 Add a new DTO class for hanke creation

- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/HankeServiceITests.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/application/ApplicationAuthorizerITest.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/application/ApplicationServiceITest.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/permissions/HankeAuthorizerITest.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/permissions/HankeKayttajaAuthorizerITest.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/permissions/HankeKayttajaControllerITest.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/permissions/HankeKayttajaServiceITest.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/permissions/PermissionServiceITest.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/HankeServiceImpl.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/Persistence.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/application/ApplicationService.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/attachment/hanke/HankeAttachmentService.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/domain/Hanke.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/domain/PublicHanke.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/permissions/HankeKayttajaService.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/HankeControllerTest.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/application/ApplicationServiceTest.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/factory/HankeFactory.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/factory/HankeIdentifierFactory.kt
Make id mandatory (non-nullable) in both Hanke and HankeEntity. We give the id a default value in the entity, but it's rewritten during the initial persist. But it still needs to be a var, and not a val.
Also, remove some asserts that can never fail from HankeServiceITest.
> HAI-1893 Make id mandatory in Hanke and HankeEntity

- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/domain/CreateHankeRequest.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/domain/Hanke.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/domain/Hankealue.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/validation/HankeValidator.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/HankeControllerTest.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/validation/HankeValidatorTest.kt
The only required information is hanke name from now on. 
However, fields are validated if they contain information (just like before).
For some reason, front end does not currently save have if it does not contain area information. 
This change can be tested as follows:
POST http://localhost:3001/api/hankkeet
```
{
"nimi": "Kokeilu"
}
```
Should create.
> HAI-1930 Remove redundant validation from Hanke drafts

- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/HankeControllerITests.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/HankeServiceITests.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/HankeServiceImpl.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/domain/BaseHanke.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/domain/CreateHankeRequest.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/domain/Hanke.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/domain/HankeYhteystieto.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/validation/HankeValidator.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/HankeControllerTest.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/factory/CreateHankeRequestBuilder.kt
Add a separate DTO for hanke yhteystieto creation.
Create a hanke with some yhteystiedot. Can't be done from the UI.
There are two commits. The first one has a previous iteration with a different approach. I'd be interested to know if you think that's better, or has parts that would be better.
> HAI-1893 Add a separate DTO for hanke yhteystieto creation

- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/HankeControllerITests.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/HankeServiceITests.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/geometria/GeometriatDaoImplITest.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/geometria/GeometriatServiceImplITest.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/tormaystarkastelu/TormaystarkasteluTormaysServicePGITest.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/HankeMapper.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/HankeServiceImpl.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/domain/BaseHanke.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/domain/CreateHankeRequest.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/domain/SavedHankealue.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/geometria/Geometriat.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/geometria/GeometriatService.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/geometria/GeometriatServiceImpl.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/geometria/GeometriatValidator.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/tormaystarkastelu/TormaystarkasteluLaskentaService.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/tormaystarkastelu/TormaystarkasteluTormaysService.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/tormaystarkastelu/TormaystarkasteluTormaysServicePG.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/HankeMapperTest.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/factory/CreateHankeRequestBuilder.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/factory/GeometriaFactory.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/factory/HankealueFactory.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/geometria/GeometriatServiceImplTest.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/tormaystarkastelu/TormaystarkasteluLaskentaServiceTest.kt
Add a separate geometria-DTO for use in hanke creation
Also:
- refactor Tormaystarkastelu to use a set of geometria IDs, since it was all it needed from the geometries.
- Refactor GeometriaServiceImpl to maybe be a bit more understandable.
- Stop using the geometry ID given by the user when updating hanke
Create a hanke with an alue. Can't be tested with the UI.
> HAI-1893 Add DTO for geometria in new hanke

- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/HankeServiceITests.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/geometria/GeometriatDaoImplITest.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/HankeServiceImpl.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/domain/PublicHanke.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/geometria/GeometriatDaoImpl.kt
Create a new hankealue for each application area in the cable report application. The geometry of the hankealueet is the same as the application area. The start and end times of every hankealue are the same as the application dates.
Also, fix some compiler warnings left over from PR #473.
I tested this by:
- I authenticated to the Swagger UI
- In the UI, I opened a cable report application I had made earlier.
- I copied the response to the application GET request from the network tab.
- I pasted the application JSON to http://localhost:3001/api/swagger-ui/index.html#/application-controller/createWithGeneratedHanke.
- I opened the newly created hanke to see that it had hankealue, and also that the hanke had start and end dates.
This doesn't work from the UI yet, since …
> HAI-2038 Add a hankealue for every application area in generated hanke

- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/permissions/HankeKayttajaControllerITest.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/permissions/HankeKayttajaController.kt
Change /hankkeet/my-permissions to just /my-permissions as we have /hankkeet/{hankeTunnus}.
This is done to have these separated more clearly.
Front end is not implemented, so:
- Create johtoselvitys (it autogenerates a hanke)
- Create hanke via "luo uusi hanke"
- GET http://localhost:3001/api/my-permissions
- Verify response, autogenerated hanke should have an existing hankekayttaja. For normally created hanke, it should be null. Both privileges should be at level KAIKKI_OIKEUDET.
> HAI-2041 Change my-permissions endpoint path

- services/hanke-service/build.gradle.kts
Docker builds are failing because of missing nmp. Turns out, the MJML plugin depends on the gradle node plugin, but that doesn't download node out-of-the-box. We need to instruct it to download node.
Add configuration so that the Gradle node plugin downloads node during build.
1. Build the hanke-service docker service.
2. Do a local operation like `./gradlew test`.
> HAI-1944 Fix Docker builds

- email/johtoselvitys-valmis.mjml
- services/hanke-service/build.gradle.kts
- services/hanke-service/src/main/resources/email/template/johtoselvitys-valmis.html.mustache
Use the new template for cable report emails.
Make a decision for a cable report application.
Or add this to `EmailSenderService` to send one when the application launches:
```
@EventListener(ApplicationReadyEvent::class)
fun sendTestMails() {
sendJohtoselvitysCompleteEmail("haitaton@test.com", 131, "JS2300001")
exitProcess(0)
}
``` 
> HAI-1944 Use the new template for cable report emails

- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/attachment/hanke/HankeAttachmentRepositoryITests.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/attachment/common/AttachmentEntity.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/attachment/hanke/HankeAttachmentService.kt
- services/hanke-service/src/main/resources/db/changelog/changesets/054-add-hanke-attachment-blob-location.yml
- services/hanke-service/src/main/resources/db/changelog/db.changelog-master.yaml
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/factory/AttachmentFactory.kt
HAI-1966 Add column for hanke attachment blob location
For now, blob location is nullable to support files that are still in the db.
Unit test is the only way to verify for now. However this change should create any regressions on adding hanke attachments.
> HAI-1966 Add column for hanke attachment blob location

- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/HankeServiceITests.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/application/ApplicationServiceITest.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/HankealueService.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/application/ApplicationService.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/configuration/Configuration.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/application/ApplicationServiceTest.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/factory/GeometriaFactory.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/test/Asserts.kt
When a cable report application is updated, recreate the hankealueet of the associated hanke, if it's generated.
Also, give every generated hankealue a name. The names follow the same pattern as UI: "Hankealue 1", "Hankealue 2" and so forth. Because the hankealueet are recreated at every update, the indexing always starts at one.
- Start to create a cable report application through the UI.
- After filling in areas on the area page save and suspend. 
- Go to the hanke that was generated for the application
- Check that the hanke has the same areas you gave the application.
- Edit the application areas. Save and suspend again.
- Check that the generated hanke has the same changes in its areas.
> HAI-2039 Recreate hankealue in generated hanke on update

- docker-compose.yml
- services/hanke-service/build.gradle.kts
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/attachment/azure/BlobFileClientITest.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/attachment/azure/AzureContainerServiceClient.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/attachment/azure/BlobFileClient.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/attachment/common/FileClient.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/configuration/Configuration.kt
- services/hanke-service/src/main/resources/application.properties
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/attachment/common/FileClientTest.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/attachment/common/MockFileClient.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/attachment/common/MockFileClientTest.kt
- services/hanke-service/src/test/resources/application-test.properties
Add a client for Azure Blob. The client can upload, download and delete files.
In upload, Content-Type and Content-Disposition headers are set for the files. These might come useful later when we want to download directly from Blob storage.
Download returns a Azure's BinaryData object for the content, because the bytes can be streamed from that object. This might be useful, if we can stream the data directly to the HTTP response. It would reduce the memory footprint of downloads significantly. Content length is also returned separately to facilitate the streaming. If the streaming is not feasible, the data can be easily accessed as a ByteArray.
Ways to connect in different scenarios:
- In the cloud, AZURE_CLIENT_ID etc. environment variables are read in application.properties to form a …
> HAI-1967 Add a client for Azure Blob

- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/DatabaseTest.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/HankeRepositoryITests.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/HankeServiceITests.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/HanketunnusServiceImplITest.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/SpringDocITest.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/application/ApplicationAuthorizerITest.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/application/ApplicationServiceITest.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/attachment/application/ApplicationAttachmentServiceITest.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/attachment/common/FileScanClientITest.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/attachment/hanke/HankeAttachmentRepositoryITests.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/attachment/hanke/HankeAttachmentServiceITests.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/email/EmailSenderServiceITest.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/email/EmailSenderServicePropertiesITest.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/gdpr/GdprServiceITest.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/geometria/GeometriatDaoImplITest.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/geometria/GeometriatServiceImplITest.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/logging/AuditLogServiceITests.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/permissions/HankeAuthorizerITest.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/permissions/HankeKayttajaAuthorizerITest.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/permissions/HankeKayttajaServiceITest.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/permissions/KayttooikeustasoEntityITest.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/permissions/PermissionServiceITest.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/testdata/TestDataServiceITest.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/tormaystarkastelu/TormaystarkasteluTormaysServicePGITest.kt
`@Testcontainers` is an inheritable annotation, so if it's added to DatabaseTest, it doesn't need to be repeated in test classes that inherit DatabaseTest.
`webEnvironment = SpringBootTest.WebEnvironment.RANDOM_PORT` in `@SpringBootTest` doesn't seem to do anything, so those can be removed.
`@TestPropertySource(locations =
["classpath:application-test.properties"])` is no longer needed, since all tests use the test profile, so `application-test.properties` is used automatically.
Also, change the name of the container property in DatabaseTest to something harder to collide with accidentally. Collisions can cause misleading error messages.
Tests still pass.
> HAI-1969 Clean test annotations

- README.md
- scripts/docker-azurite/setup.sh
- services/hanke-service/build.gradle.kts
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/attachment/azure/BlobFileClientITest.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/attachment/azure/AzureContainerServiceClient.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/attachment/azure/BlobFileClient.kt
- services/hanke-service/src/main/resources/application.properties
Blob Storage can't use a connection string to connect to Azure AD (https://stackoverflow.com/questions/67715786/blob-storage-java-sdk-authorize-by-azure-ad).
Use the default credential builder when the connection string is not explicitly defined, i.e. in cloud environments. Also, add some diagnostic logging to startup.
> HAI-1967 Use default credential builder for cloud environments

- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/attachment/application/ApplicationAttachmentControllerITest.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/attachment/application/ApplicationAttachmentServiceITest.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/attachment/azure/BlobFileClientITest.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/attachment/common/AttachmentContentServiceITest.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/attachment/hanke/HankeAttachmentControllerITests.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/attachment/hanke/HankeAttachmentServiceITests.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/attachment/common/AttachmentContentService.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/attachment/hanke/HankeAttachmentController.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/attachment/hanke/HankeAttachmentService.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/attachment/AttachmentTestUtil.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/attachment/common/MockFileClient.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/attachment/common/MockFileClientTest.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/factory/HankeAttachmentFactory.kt
When blob_location is present in the attachment, download the attachment content from Blob Storage instead of the database.
1. Add a file to the haitaton-hankeliitteet-local container in Azurite with Azure Storage Explorer or the CLI. Take a note of the path.
2. Add an attachment to a hanke. You can use the https://github.com/City-of-Helsinki/haitaton-ui/pull/409 branch for this if it's not merged yet.
3. In the DB, update the bloc_location column of the attachment to contain the path of the file you added to Azurite earlier.
4. In the DB, delete the matching hanke_attachment_content row.
5. You should be able to download the attachment through the UI.
> HAI-1969 Download hanke attachments from Blob Storage

- azure-pipelines-hanke-service-pr.yml
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/IntegrationTestConfiguration.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/attachment/hanke/HankeAttachmentAuthorizerITest.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/attachment/hanke/HankeAttachmentControllerITests.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/attachment/hanke/HankeAttachmentServiceITests.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/attachment/hanke/HankeAttachmentAuthorizer.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/attachment/hanke/HankeAttachmentController.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/attachment/hanke/HankeAttachmentService.kt
Authorization and business logic have been intertwined in hanke attachments. Authorization has checked that the user has the correct permission for the hanketunnus in the URL, but checking that the application belongs to that hanke has been done in HankeAttachmentService.
Separate authorization and business logic by adding a new authorizer for hanke attachments. The authorizer checks that the user has the correct permission for the hanke and that the attachment belongs to that hanke. So we don't need to pass the hanketunnus to the service anymore.
Also, enable PR builds also for branches that target any branch starting
with HAI.
Downloading and deleting attachments works like before.
> HAI-1969 Separate authorization and business logic in hanke attachments

- services/hanke-service/build.gradle.kts
The Spring Security version was specified explicitly while preparing for the Spring 3.0 upgrade. A special transitional version of Spring Security made the upgrade easier. When the upgrade to 3.1 was completed, this specification should've been deleted, but the version was updated instead.
Removing the version will make Spring Security follow Spring Boot's recommended version. So it will update as we update Spring Boot.
> HAI Remove explicit Spring Security version

- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/attachment/hanke/HankeAttachmentContentServiceITest.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/attachment/hanke/HankeAttachmentServiceITests.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/attachment/azure/BlobFileClient.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/attachment/hanke/HankeAttachmentContentService.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/attachment/hanke/HankeAttachmentController.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/attachment/hanke/HankeAttachmentService.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/attachment/common/MockFileClient.kt
Delete attachment content from Blob Storage when a single attachment is removed.
Deleting the content when a hanke is removed will be done in a separate task (HAI-2013).
Use the branch from #505 to test this.
1. Add an attachment to a hanke in the UI.
2. Call the temporary endpoint to move the content to Azurite.
3. Check that the file is visible in Azurite with Azure Storage Explorer or CLI.
4. Delete the attachment from the Haitaton UI.
5. Check that the file is longer in Azurite with Azure Storage Explorer or CLI.
> HAI-1994 Delete attachments from Blob Storage

- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/attachment/hanke/HankeAttachmentContentService.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/attachment/hanke/HankeAttachmentService.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/testdata/TestDataController.kt
Add a temporary endpoint for moving attachment content to Blob Storage. The endpoint will take an attachment ID as its parameter and move the content of that attachment to the cloud.
The motivation is to make testing Blob functionality easier. Adding a single attachment to the cloud required 4 steps earlier, now it needs 2 and the steps are easier.
At least some of the service implementation can be used later for the background migration process (HAI-1964).
After using the UI to upload an attachment, look up its ID from the network tab, and use the Swagger UI to call http://localhost:3001/api/swagger-ui/index.html#/test-data-controller/replaceContent. Authorization is needed as usual. The attachment will be uploaded to Blob Storage and the content will be removed from the database.
> HAI-1994 Temp endpoint for moving attachment content to Blob

- services/hanke-service/build.gradle.kts
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/HankeServiceITests.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/attachment/hanke/HankeAttachmentAuthorizerITest.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/attachment/hanke/HankeAttachmentContentServiceITest.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/attachment/hanke/HankeAttachmentRepositoryITests.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/attachment/hanke/HankeAttachmentServiceITests.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/HankeService.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/Persistence.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/attachment/azure/BlobFileClient.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/attachment/common/FileClient.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/attachment/hanke/HankeAttachmentContentService.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/attachment/hanke/HankeAttachmentService.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/domain/Hanke.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/logging/HankeLoggingService.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/logging/YhteystietoLoggingEntryHolder.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/application/AlluUpdateServiceTest.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/attachment/common/FileClientTest.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/attachment/common/MockFileClient.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/attachment/common/MockFileClientExtension.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/attachment/common/MockFileClientTest.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/factory/AttachmentFactory.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/factory/HankeAttachmentBuilder.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/factory/HankeAttachmentFactory.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/factory/HankeFactory.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/test/Asserts.kt
Use a batch operation to delete all the attachment Blobs of a hanke when the hanke is removed. The operation removes all Blobs matching the directory the hanke attachments are in, so it also removes any that might have been orphaned earlier. It can't handle subdirectories, though, since we don't have a use case for them. Implementing deleting objects from subdirectories seemed to require a recursive search for them.
Refactor HankeAttachmentFactory. It was confusing to have it as an interface with default functions. To enable the use of a fluid interface for creating content for the attachments, use a builder that stores the required dependencies and the saved entity. Remove functionality related to hanke attachments from AttachmentFactory and use HankeAttachmentFactory instead.
Mark Hanke …
> HAI-2013 Delete Blobs when hanke is deleted

- docker-compose.yml
- services/hanke-service/Dockerfile-local
Implement layered multistage build adhering to best practices: https://spring.io/guides/topicals/spring-boot-docker/
Should speed up consecutive build times. I did some testing:
- Scenario: You have haitaton stack running in docker compose, you edit the source code.
- Command:  docker compose up -d --force-recreate --build haitaton-hanke 
- Results: 
- old way: 84 seconds 
- new way: 23 seconds
On the very first build, the caching mechanism cannot (of course) be used, so there is not much of a difference there.
> HAI Improve Dockerfile-local

- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/HankeServiceITests.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/application/ApplicationServiceITest.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/attachment/application/ApplicationAttachmentServiceITest.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/attachment/common/AttachmentUploadServiceITest.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/attachment/hanke/HankeAttachmentContentServiceITest.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/attachment/hanke/HankeAttachmentServiceITests.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/configuration/MockCableReportService.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/permissions/HankeKayttajaServiceITest.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/testdata/TestDataServiceITest.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/configuration/Configuration.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/email/EmailSenderService.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/email/EmailSenderServiceTest.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/factory/AlluDataFactory.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/factory/UserContactFactory.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/test/Asserts.kt
- services/hanke-service/src/test/resources/application-test.properties
Configure the Spring Context in integration tests to use a mockk instance of CableReportService so the mock can be `@Autowired`. CableReportService was defined in several integration tests as a `@MockkBean` dependency. The actual implementation was only used in `CableReportServiceITests`, which constructs a custom instance.
The other class that was injected with `@MockkBean` was `EmailSenderService`. Since there's an easy-to-use extension for mocking an actual email server, it felt better to use that instead of mocking the service universally. Also, unlike `CableReportServiceITests`, `EmailSenderServiceITest` uses the Spring context, so a context with the actual implementation is needed anyway.
Each unique combination of `@MockkBeans` and `@SpykBeans` (or the Mockito equivalents) makes …
> HAI Remove @MockkBean and @SpykBean annotations

- scripts/gis-material-update/README.md
- scripts/gis-material-update/config.yaml
- scripts/gis-material-update/fetch/fetch_data.sh
- scripts/gis-material-update/process/modules/central_business_area.py
- scripts/gis-material-update/process/process_data.py
- scripts/gis-material-update/process/test/test_central_business_area.py
* Compute central business area tormays materials base on named attributes
* Implemeted test mixin method for multiple geometries
* Document updated for central business areas processing
* Update scripts/gis-material-update/data/README.md
https://helsinkisolutionoffice.atlassian.net/browse/HAI-2116
Check instructions from scripts/gis-material-update/readme to process central_business_area data. 
Then check data (=tormays_central_business_areas.gpkg) with QGIS:
* current feature count: 123 (this amount might be changed over time)
* geometries are looking ok (=areas)
* objects are having following attributes: 
"fid",
"central_business_area",
"tunnus",
"osaalue_tunnus",
"osaalue_nimi_fi",
"osaalue_nimi_se",
"peruspiiri_nimi_fi",
"peruspiiri_nimi_se",
"suurpiiri_nimi_fi",
"suurpiiri_nimi_se" …
> HAI-2116 Added central business area tormays material

- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/allu/CableReportServiceITests.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/application/ApplicationServiceITest.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/attachment/application/ApplicationAttachmentControllerITest.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/attachment/application/ApplicationAttachmentRepositoryITests.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/attachment/application/ApplicationAttachmentServiceITest.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/attachment/hanke/HankeAttachmentControllerITests.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/attachment/hanke/HankeAttachmentMigratorITest.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/attachment/hanke/HankeAttachmentRepositoryITests.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/attachment/hanke/HankeAttachmentServiceITests.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/attachment/application/ApplicationAttachmentService.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/attachment/common/AttachmentEntity.kt
- services/hanke-service/src/main/resources/db/changelog/changesets/058-add-blob-location-to-application-attachment.yml
- services/hanke-service/src/main/resources/db/changelog/db.changelog-master.yaml
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/attachment/AttachmentTestUtil.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/attachment/hanke/HankeAttachmentMigrationSchedulerTest.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/factory/ApplicationAttachmentFactory.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/factory/HankeAttachmentFactory.kt
Add a column to the application attachment table to store the file's location in Azure Blob.
Also, move the remaining HankeAttachment-related functions from AttachmentFactory to HankeAttachmentFactory. Rename AttachmentFactory to ApplicationAttachmentFactory.
1. Start hanke-service
2. Check that the database has a new column.
> HAI-1984 Add blobLocation to application attachment

- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/attachment/hanke/HankeAttachmentContentService.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/attachment/hanke/HankeAttachmentService.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/testdata/TestDataController.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/factory/HankeAttachmentBuilder.kt
Hanke attachments are uploaded to the cloud now, so we no longer need this test data controller method.
> HAI-1987 Remove temp method for moving hanke attachments to cloud

- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/attachment/application/ApplicationAttachmentContentServiceITest.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/attachment/application/ApplicationAttachmentServiceITest.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/allu/CableReportService.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/attachment/application/ApplicationAttachmentContentService.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/attachment/application/ApplicationAttachmentService.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/factory/AlluDataFactory.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/factory/ApplicationAttachmentBuilder.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/factory/ApplicationAttachmentFactory.kt
When blob_location is present in the attachment, download the attachment content from Blob Storage instead of the database.
The download is done inside a DB transaction for now. This will be changed in another PR for this same story.
1. Upload a file to Azurite with Azure Storage Explorer.
2. In DB, change an application attachment's `blob_location` to match the uploaded file name.
3. Download the attachment through UI.
> HAI-1987 Download application attachments from blob

- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/IntegrationTestConfiguration.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/allu/CableReportServiceITests.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/attachment/application/ApplicationAttachmentContentServiceITest.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/attachment/application/ApplicationAttachmentControllerITest.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/attachment/application/ApplicationAttachmentServiceITest.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/attachment/common/AttachmentUploadServiceITest.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/attachment/hanke/HankeAttachmentControllerITests.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/allu/CableReportService.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/attachment/application/ApplicationAttachmentContentService.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/attachment/application/ApplicationAttachmentController.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/attachment/application/ApplicationAttachmentMetadataService.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/attachment/application/ApplicationAttachmentService.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/attachment/common/AttachmentEntity.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/attachment/common/AttachmentUploadService.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/attachment/common/Domain.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/attachment/common/Dto.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/attachment/hanke/HankeAttachmentController.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/attachment/hanke/HankeAttachmentService.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/factory/ApplicationAttachmentFactory.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/factory/HankeAttachmentFactory.kt
Split DB operations from ApplicationAttachmentService to a new service, ApplicationAttachmentMetadataService. This allows us to do Allu and Blob operations without having a DB transaction running.
ApplicationAttachmentMetadataService is only called from ApplicationAttachmentService, so other services don't have to know the difference between the two.
Nothing should change.
> HAI-1987 Refactor application attachment services

- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/attachment/application/ApplicationAttachmentContentServiceITest.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/attachment/application/ApplicationAttachmentServiceITest.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/attachment/application/ApplicationAttachmentContentService.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/attachment/application/ApplicationAttachmentController.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/attachment/application/ApplicationAttachmentService.kt
Add logic to delete application attachment blobs if the blob location is defined.
The blob upload functionality for applications is not yet implemented. Hence, there is no blobs to delete. The attachment deletion should however work as before from the UI perspective.
> HAI-1996 Delete application attachment blobs

- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/HankeRepositoryITests.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/Persistence.kt
- services/hanke-service/src/main/resources/db/changelog/changesets/063-drop-haitta-columns-from-hanke.yml
- services/hanke-service/src/main/resources/db/changelog/db.changelog-master.yaml
Removed unnecessary haitta columns from hanke:
```
- dropColumn:
tableName: hanke
columnName: kaistahaitta
- dropColumn:
tableName: hanke
columnName: kaistapituushaitta
- dropColumn:
tableName: hanke
columnName: meluhaitta
- dropColumn:
tableName: hanke
columnName: polyhaitta
- dropColumn:
tableName: hanke
columnName: tarinahaitta
```
When backend is started the columns are deleted in database without errors.
> HAI-2209 Removed haitta columns from hanke

- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/permissions/HankeKayttajaControllerITest.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/permissions/HankeKayttajaServiceITest.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/permissions/KayttooikeustasoEntityITest.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/HankeError.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/permissions/HankeKayttaja.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/permissions/HankeKayttajaController.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/permissions/HankeKayttajaService.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/permissions/PermissionUpdate.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/permissions/Permissions.kt
- services/hanke-service/src/main/resources/db/changelog/changesets/064-add-create-user-permission-code.sql
- services/hanke-service/src/main/resources/db/changelog/db.changelog-master.yaml
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/factory/HankeKayttajaFactory.kt
- services/hanke-service/src/test/resources/application-test.yml
Add an endpoint for adding a new user. The endpoint adds a hankekäyttäjä and a käyttäjäkutsu for the user and sends an invitation email to the hanke. The request is declined if a user already has the same email.
The invitation email is only sent if the caller has a hankekäyttäjä, and not just a permission. This limitation will not matter with a new hanke created with the kortisto-model.
Add first and last names as new fields to HankeKayttajaDto. With this, the response fields match the request fields. Keep the full name field in the DTO for compatibility.
Add a new permission code for adding a new user. The existing codes weren't a good match. The only one with the correct käyttöoikeustaso is RESEND_INVITATION, which is not descriptive of this task.
Override Sentry DSN to empty value in …
> HAI-2159 Add endpoint for adding a new user

- scripts/gis-material-update/README.md
- scripts/gis-material-update/process/modules/tram_lines.py
Adding high speed objects to tram lines:
Added new route_type value which will be included in tram_lines.
Added clipping by Helsinki area because some tram_lines are going outside of Helsinki.
Update scripts/gis-material-update/data/README.md
https://helsinkisolutionoffice.atlassian.net/browse/HAI-2131
Check instructions from scripts/gis-material-update/readme to process tram_lines data.
Then check data file (tormays_tram_lines_polys.gpkg) with QGIS:
* current feature count: 89 (this amount might be changed over time)
* geometries are looking ok (=areas)
* objects are having following attributes:
"fid",
"lines"
scripts/gis-material-update/data/README.md
other info that the tester/user needs to …
> Hai 2131/tram line high speed

- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/attachment/application/ApplicationAttachmentContentServiceITest.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/attachment/application/ApplicationAttachmentServiceITest.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/attachment/application/ApplicationAttachmentContentService.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/attachment/application/ApplicationAttachmentMetadataService.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/attachment/application/ApplicationAttachmentService.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/attachment/azure/BlobFileClient.kt
Application attachments are stored in Azure blob storage instead of database.
1. Add an attachment for an application
2. Check blob storage with e.g. MS Azure Storage Explorer - the attachment should be there under `haitaton-hakemusliitteet-local` in path `<applicationId>/<uuid>`
3. Check the database - there should not be a new row in `application_attachment_content` table
4. Check the database - there should be a new row in `application_attachment` table with `blob_location` set to `<applicationId>/<uuid>` which is the path of the file in blob storage.
5. [OPTIONAL] Check that deletion of the attachment works as expected
> HAI-1983 Add application attachments to blob storage instead of database

- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/permissions/HankeKayttajaControllerITest.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/permissions/HankeKayttajaServiceITest.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/permissions/HankeKayttaja.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/factory/HankeKayttajaFactory.kt
Add phone number to user list response. The full name was left to the response since the front end still uses it. Mark it as deprecated instead of removing it.
Call the API. Either with the Swagger UI or check the dev tools after opening the Käyttöoikeuksien hallinta page.
or other location: OpenAPI docs
> HAI-2157 Add phone number to user list API

- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/permissions/HankeKayttajaAuthorizerITest.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/permissions/HankeKayttajaControllerITest.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/permissions/HankeKayttajaServiceITest.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/ControllerExceptionHandler.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/logging/DisclosureLogService.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/permissions/HankeKayttajaController.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/permissions/HankeKayttajaService.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/permissions/Permissions.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/factory/AuditLogEntryFactory.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/factory/HankeKayttajaFactory.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/logging/DisclosureLogServiceTest.kt
Add a new API for getting a single kayttaja at `GET /kayttajat/{kayttajaId}`.
The API writes each operation to the audit log.
Also, add an exception handler for `MethodArgumentTypeMismatchException` so that invalid path parameters return 400 Bad Request instead of 500 Internal Server Error.
Also, add a new permission for modifying users. This is given only to
KAIKKI_OIKEUDET users. (HAI-2265)
Call the API with Swagger UI (http://localhost:3001/api/swagger-ui/index.html#/hanke-kayttaja-controller/getHankeKayttaja).
Merge #571 before this one.
> HAI-2263 Add API for getting a single kayttaja

- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/HankeControllerITests.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/HankeServiceITests.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/HankeService.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/HankeYhteyshenkiloEntity.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/HankeYhteystietoEntity.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/domain/HankeYhteystieto.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/HankeMapperTest.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/TestExtensions.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/factory/HankeBuilder.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/factory/HankeFactory.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/factory/HankeKayttajaFactory.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/factory/HankeYhteyshenkiloFactory.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/factory/HankeYhteystietoFactory.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/logging/DisclosureLogServiceTest.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/validation/HankeValidatorTest.kt
Add contacts to hanke read APIs.
Add test factories to make adding yhteyshenkilöt to hanke easier.
The only way to test the new API is by adding the new type of contact from DB.
> HAI-2166 Add contacts to hanke read APIs

- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/permissions/KayttooikeustasoEntityITest.kt
- services/hanke-service/src/main/resources/db/changelog/changesets/068-grant-modify-user-permission-to-kayttooikeustasot.sql
- services/hanke-service/src/main/resources/db/changelog/db.changelog-master.yaml
All users except users with just view permissions should be able to modify the contact information of contact people. Grant the permission to these groups.
> HAI-2265 Grant MODIFY_USERS to correct käyttäoikeustasot

- scripts/gis-material-update/process/modules/tram_infra.py
HAI-2130 Adding light rail objects to tram infra.
Added new tag value "light_rail" which will be included in tram_infra.
Also changed code so that it is easier to add tag values later on.
Added clipping by Helsinki area because some tram_infra objects are going outside of Helsinki.
https://helsinkisolutionoffice.atlassian.net/browse/HAI-2130
Check instructions from scripts/gis-material-update/readme to process tram_infra data (check also preparing part from instructions).
Then check data file (tormays_tram_infra_polys.gpkg) with QGIS:
* current feature count: 1848 (this amount might be changed over time)
* geometries are looking ok (=areas)
* objects are having following attributes:
"fid",
"infra"
Please describe here if there is e.g. some requirements for this change …
> Hai 2130/tram infra high speed

- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/attachment/azure/BlobFileClient.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/attachment/common/FileClient.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/attachment/common/FileClientTest.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/attachment/common/MockFileClient.kt
Fixes errors with attachment filanames with e.g. scandic letters or €.
Attachments work with filanames containing e.g. scandic letters or €
> HAI-2283 Fixed invalid characters in ContentDisposition header (filename)

- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/HankeServiceITests.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/permissions/HankeKayttajaControllerITest.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/permissions/HankeKayttajaServiceITest.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/permissions/HankeKayttaja.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/factory/HankeBuilder.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/factory/HankeKayttajaFactory.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/logging/DisclosureLogServiceTest.kt
`GET /hankkeet/{hankeTunnus}/kayttajat` returns user roles as in
```
{
"kayttajat": [
{
"id": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
"etunimi": "Pekka",
"sukunimi": "Perustaja",
"sahkoposti": "pekka@perustukset.example",
"puhelinnumero": "0501234567",
"kayttooikeustaso": "KAIKKI_OIKEUDET",
"roolit": ["OMISTAJA", "RAKENNUTTAJA"],
"tunnistautunut": true
}
]
}
```
Not sure if this can be tested with Swagger UI or Haitaton UI yet because in Haitaton UI one cannot currently add contacts or contact persons.
> HAI-2260 Add user roles in user list api response

- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/permissions/HankeKayttajaControllerITest.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/permissions/HankeKayttajaServiceITest.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/permissions/ContactUpdate.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/permissions/HankeKayttaja.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/permissions/HankeKayttajaController.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/permissions/HankeKayttajaService.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/factory/HankeKayttajaFactory.kt
Add an endpoint that allows the user to change their contact information on the hanke.
Also, add missing fields to the HankeKayttaja domain object. This enables the DTO to be derived from the domain object and adds the missing fields to change audit logs.
1. Create a hanke
2. Use the Swagger-UI to change your contact information
3. They should be changed in the Käyttäjähallinta page
> HAI-2223 Add API for changing own contact information

- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/application/ApplicationControllerITest.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/application/ApplicationServiceITest.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/application/ApplicationController.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/application/ApplicationService.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/application/ApplicationServiceTest.kt
Forbid application update if the application has been sent to Allu.
1. Create new cable report application
2. Fill the application and send it
3. Try to modify the application (atm UI still allows this but that will change soon) - there should be a 409 HTTP error
> HAI-2305 Do not allow modify application after send

- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/permissions/HankeKayttajaControllerITest.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/permissions/HankeKayttajaServiceITest.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/HankeError.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/permissions/HankeKayttaja.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/permissions/HankeKayttajaController.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/permissions/HankeKayttajaService.kt
When user logs in via the invitation link, retrieve user's verified name from Profiili and if it differs from original name, update the name. Use given name as firstname. Do not alter names used in invitation.
1. Using an access login of logged in Hanke user with `CREATE_USER` rights, create a new user ` POST /hankkeet/{hankeTunnus}/kayttajat` for Hanke. Take note of the data you provide, e.g. 
`{
"etunimi": "Jaska",
"sukunimi": "Jokunen",
"sahkoposti": "jaska.jokunen@gmail.com",
"puhelinnumero": "1234567"
}`
2. Log in with the invitation link. Use Suomi.fi test user that is not yet used in Hanke. 
3. Using the access token of this new log in, check that the user name is updated with Profiili data `GET /hankkeet/{hankeTunnus}/kayttajat` (There should also be an INFO log message starting …
> HAI-2168 Update user's name from Profiili

- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/attachment/application/ApplicationAttachmentControllerITest.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/attachment/application/ApplicationAttachmentServiceITest.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/attachment/application/ApplicationAttachmentController.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/attachment/application/ApplicationAttachmentService.kt
After sending application to Allu no attachments can be added to it.
1. Create new cable report application, fill it and send it
2. Try to add new attachment to the application - it should return HTTP 409 error
> HAI-2306 Do not allow adding application attachments after send

- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/permissions/HankeKayttajaControllerITest.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/ControllerExceptionHandler.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/permissions/ContactUpdate.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/permissions/HankeKayttajaController.kt
Add validation that user can't change their own phone number or email to be empty or blank.
Try to update sahkoposti or email to "" or " " in Swagger UI.
> HAI-2223 Add validation for changing own contact info

- scripts/gis-material-update/README.md
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/tormaystarkastelu/TormaystarkasteluTormaysService.kt
The street classes have changed somewhat. These changes should be reflected in our code. The old, replaced value was left in place as deprecated to give backwards compatibility.
1. Before update the local törmäys-data, check that the car traffic index is calculated correctly.
2. Recreate the tormays_street_classes_polys table data according to the instructions. (Fileshare has been updated)
3. Check that the index calculations are calculated correctly.
> HAI-2227 Update index calculations for street classes

- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/HankeControllerITests.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/domain/ModifyHankealueRequest.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/factory/HankeBuilder.kt
There is a bug with saving hanke areas. Json deserializer doesn't know how to create an instance of HasFeatures, since it's an interface.
Change the type of `ModifyHankealueRequest.geometriat` to `ModifyGeometriaRequest`, which is was probably meant to be in the first place.
Add a test that reproduces the bug without the fix.
1. Create a hanke.
2. Add an area to it.
3. Saving the hanke succeeds after pressing the next button.
> HAI-2336 Fix saving hanke geometries

- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/HankeServiceITests.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/application/ApplicationServiceITest.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/gdpr/GdprServiceITest.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/permissions/HankeKayttajaServiceITest.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/gdpr/GdprInfo.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/gdpr/GdprJsonConverter.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/application/ContactTest.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/factory/ApplicationFactory.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/factory/HankeYhteystietoFactory.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/gdpr/GdprJsonConverterTest.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/logging/DisclosureLogServiceTest.kt
First and last names are tracked separately everywhere in Haitaton now, so we should return them separately from the GDPR API.
Also, add constants for the names and phone number of TEPPO_TESTI and use those constants where ever applicable.
The story itself will be implemented in a later PR.
> HAI-2337 Return first and last names separately from GDPR API

- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/HankeControllerHankeEditingDisabledITests.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/HankeControllerITests.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/HankeServiceITests.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/application/ApplicationControllerITest.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/hakemus/HakemusControllerITest.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/hakemus/HakemusServiceITest.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/HankeController.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/application/ApplicationController.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/hakemus/HakemusController.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/hakemus/HakemusService.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/hakemus/HankkeenHakemuksetResponse.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/factory/ApplicationFactory.kt
Move API endpoint `/hankkeet/<hankeid>/hakemukset` from HankeController to new HakemusController.
Endpoint `/hankkeet/<hankeid>/hakemukset` should work as before.
> HAI-2243 New API for getting hakemukset for hanke

- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/allu/ApplicationHistory.kt
Allu has an undocumented status that it sends when a comment has been sent to the client system. If such a message is added, this will break fetching the application history, i.e. all application updates.
Staging logs have constant errors of this.
> HAI Add COMMENT_ADDED application status

- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/gdpr/GdprControllerITests.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/gdpr/KortistoGdprServiceITest.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/gdpr/OldGdprServiceITest.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/gdpr/GdprController.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/gdpr/GdprService.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/factory/ApplicationBuilder.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/gdpr/OldGdprServiceTest.kt
Refactor the GDPR service dry-run to not return a list of applications. Instead, return true if the information can be deleted and throw an exception if it can't. This also means that the delete call needs to be refactored to not receive a list of applications, but fetch them from the DB again.
Besides supporting both the old and Kortisto model of GDPR service, this also has the added benefit of loading the information to be deleted in the same transaction as they are deleted in, so there's no chance of the information changing between the loading and deleting.
Implement the canDelete method for `KortistoGdprService`. This checks that the user is not on any active applications, and is not the only admin user (user with KAIKKI_OIKEUDET privileges) in the hanke. If the user shouldn't be …
> HAI-2338 Implement gdpr delete dry-run for kortisto

- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/HankeServiceITests.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/application/ApplicationServiceITest.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/permissions/HankeKayttajaControllerITest.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/permissions/HankeKayttajaServiceITest.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/permissions/HankeKayttaja.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/factory/HankeKayttajaFactory.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/test/Asserts.kt
Add the date and time the latest invitation to a user was sent. If the invitation is resent, the date and time will reset as well.
Also, remove the deprecated `nimi` field from HankeKayttaja and the DTO. The frontend doesn't use that field anymore, so it's safe to delete it now.
> HAI-2377 Add invitation date to hankekayttaja response

- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/HankeServiceITests.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/gdpr/KortistoGdprServiceITest.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/Persistence.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/gdpr/GdprController.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/gdpr/GdprService.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/hakemus/HakemusyhteystietoEntity.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/factory/HankeBuilder.kt
Follow the procedure described in https://helsinkisolutionoffice.atlassian.net/wiki/spaces/HAI/pages/8075476993/GDPR+API to delete either the hankekayttaja or the whole hanke when the user asks for their information to be removed.
Add cascade and orphan removal for
`HakemusyhteystietoEntity.yhteyshenkilot`. This fixes a bug when removing a hanke with an application with yhteyshenkilot.
Can be tested with the profile-gdpr-api-tester.
or other location: https://helsinkisolutionoffice.atlassian.net/wiki/spaces/HAI/pages/8075476993/GDPR+API
> HAI-2338 Implement GDRP delete API for kortisto

- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/gdpr/KortistoGdprServiceITest.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/hakemus/HakemusServiceITest.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/permissions/HankeKayttajaControllerITest.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/permissions/HankeKayttajaServiceITest.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/permissions/KayttooikeustasoEntityITest.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/application/ApplicationData.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/application/ApplicationEntity.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/hakemus/Hakemus.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/hakemus/HakemusService.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/hakemus/Hakemusyhteystieto.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/hakemus/HakemusyhteystietoEntity.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/permissions/HankeKayttajaController.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/permissions/HankeKayttajaService.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/permissions/Permissions.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/validation/HankeValidator.kt
- services/hanke-service/src/main/resources/db/changelog/changesets/071-grant-delete-user-permission-to-kayttooikeustasot.sql
- services/hanke-service/src/main/resources/db/changelog/db.changelog-master.yaml
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/factory/HakemusFactory.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/factory/HakemusyhteystietoFactory.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/factory/HankeBuilder.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/factory/HankeFactory.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/factory/HankeKayttajaFactory.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/factory/HankeYhteyshenkiloFactory.kt
The API returns names, identifiers and statuses of all applications the hankekayttaja is a contact in, partitioned to active applications and drafts. It also returns a boolean that's true when the hankekayttaja is the only contact in one of the omistaja customers.
Add domain classes for Hakemus and HakemusData. The classes and methods for creating them from entities and in factories are loaned from #637.
Add a new permission code for deleting users. It's given to KAIKKI_OIKEUDET and KAIKKIEN_MUOKKAUS privileges.
The endpoint can be called from e.g. Swagger UI, but there's no method yet 
or other location: https://helsinkisolutionoffice.atlassian.net/wiki/spaces/HAI/pages/8417968152/Uusi+malli+yhteystietoihin+ja+k+ytt+oikeuksiin#Henkil%C3%B6iden-poistaminen-kortistosta
> HAI-2392 Add an API for checking if a hankekayttaja can be deleted

- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/DatabaseTest.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/HankeServiceITests.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/IntegrationTestConfiguration.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/gdpr/KortistoGdprServiceITest.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/hakemus/HakemusServiceITest.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/hakemus/HankekayttajaDeleteServiceITest.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/permissions/HankeKayttajaControllerITest.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/HankeService.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/hakemus/HakemusService.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/permissions/HankeKayttajaController.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/permissions/HankekayttajaDeleteService.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/factory/HakemusBuilder.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/factory/HakemusFactory.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/factory/HankeBuilder.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/factory/HankeFactory.kt
Move the logic behind `checkForDelete` from the controller to a new service. This will make it easier to reuse the logic for the actual delete endpoint. The service needs to be a new one because adding the logic in HankeKayttajaService would result in a circular dependency.
Rethink creating yhteyshenkilot in HankeYhteystietoBuilder. Implement a new approach for the `omistaja()` method. The others will be implemented later.
More PRs are coming.
> HAI-2393 Move checkForDelete logic to new service

- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/HankeServiceITests.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/gdpr/KortistoGdprServiceITest.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/hakemus/HankekayttajaDeleteServiceITest.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/permissions/HankeKayttajaControllerITest.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/permissions/HankeKayttajaServiceITest.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/permissions/HankeKayttajaController.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/permissions/HankekayttajaDeleteService.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/factory/HankeBuilder.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/factory/HankeFactory.kt
The delete endpoint will check the same things as the `checkForDelete` endpoint and that there will be an admin user left on the hanke after the delete (a user with Kaikki Oikeudet privileges). If any of the checks fail, 409 will be returned.
In test data factories, add new methods for getting a yhteystieto builder for a hanke. Hanke creation can be split between creating the hanke and creating the yhteystiedot, so there's no need to save entities from inside the builder function call anymore.
> HAI-2393 Add delete endpoint for hankekayttaja

- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/HankeServiceITests.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/HanketunnusServiceITest.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/IntegrationTest.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/SpringDocITest.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/application/ApplicationAuthorizerITest.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/application/ApplicationServiceITest.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/attachment/application/ApplicationAttachmentContentServiceITest.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/attachment/application/ApplicationAttachmentServiceITest.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/attachment/common/FileScanClientITest.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/attachment/hanke/HankeAttachmentAuthorizerITest.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/attachment/hanke/HankeAttachmentContentServiceITest.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/attachment/hanke/HankeAttachmentMetadataServiceITests.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/attachment/hanke/HankeAttachmentRepositoryITests.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/attachment/hanke/HankeAttachmentServiceITest.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/email/EmailSenderServiceITest.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/email/FilteredEmailSenderServiceITest.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/gdpr/KortistoGdprServiceITest.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/gdpr/OldGdprServiceITest.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/geometria/GeometriatDaoITest.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/geometria/GeometriatServiceITest.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/hakemus/HakemusServiceITest.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/hakemus/HankekayttajaDeleteServiceITest.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/logging/AuditLogServiceITests.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/permissions/HankeAuthorizerITest.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/permissions/HankeKayttajaAuthorizerITest.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/permissions/HankeKayttajaServiceITest.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/permissions/KayttooikeustasoEntityITest.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/permissions/PermissionServiceITest.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/testdata/TestDataServiceITest.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/tormaystarkastelu/TormaystarkasteluTormaysServiceITest.kt
Add the annotations shared by integration tests to DatabaseTest and rename it to IntegrationTest. The annotations can be removed from the test classes since IntegrationTest adds them. Leave the `@SpringBootTest` annotation to the class, if it modifies system properties. The class-specific annotation overrides the one from the abstract class.
Also, add MockFileClientExtension to IntegrationTest, so the file client is always available. Remove the extension annotation from other places.
> HAI-2393 Refactor DatabaseTest to IntegrationTest

- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/allu/ApplicationPdfService.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/application/ApplicationData.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/application/ApplicationDataMapper.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/application/validation/CableReportErrorValidation.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/application/validation/CableReportMissingValidation.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/hakemus/HakemusService.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/validation/HankeValidator.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/validation/Validators.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/application/ApplicationDataMapperTest.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/application/ApplicationServiceTest.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/factory/ApplicationFactory.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/logging/DisclosureLogServiceTest.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/validation/ApplicationDataValidatorTest.kt
Customer and contractor have been mandatory in applications. However, they have not been added until the 4th page of the johtoselvityshakemus form. The frontend is using a customer with nothing but nulls and empty strings as a placeholder. This doesn't make much sense, when the two other roles have been nullable.
Change the `customerWithContacts` and `contractorWithContacts` to be nullable in `ApplicationData`. Add validation so they can't be null when sending the data to Allu.
> HAI-2275 Make customer and contractor optional in applications

- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/HankeServiceITests.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/hakemus/HakemusControllerITest.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/hakemus/HakemusServiceITest.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/HankeService.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/application/ApplicationData.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/application/ApplicationEntity.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/hakemus/Hakemus.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/hakemus/HakemusController.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/hakemus/HakemusResponse.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/hakemus/HakemusService.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/hakemus/Hakemusyhteystieto.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/permissions/HankekayttajaDeleteService.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/factory/HakemusFactory.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/factory/HakemusResponseFactory.kt
The API takes in a name for the hakemus (and the generated hanke) and the founders contact info (email and phone number). It creates a hanke with the given name, adds the founder as a Kaikki Oikeudet level hankekayttaja and creates a new johtoselvityshakemus for the hanke with the same name as the hanke.
It should be possible to create a johtoselvityshakemus from the Swagger UI now.
Audit logging is added in the next PR (#656).
> HAI-2275 Add a new API for creating a stand-alone johtoselvityshakemus

- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/HankeServiceITests.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/IntegrationTest.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/hakemus/HakemusServiceITest.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/hakemus/HakemusService.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/logging/AuditLogEntry.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/logging/HakemusLoggingService.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/ControllerTest.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/hakemus/HakemusDeserializer.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/test/JacksonTestExtension.kt
Add audit logging for hakemus creation.
Also, make hakemus updates use the Hakemus type for audit logging updates.
Add a custom deserializer for Hakemus for test use. This allows Jackson to deserialize Hakemus correctly, by using the `applicationType` field to deduce which kind of `applicationData` field it should have. Deserializing wouldn't be very useful for production code, but in tests, we will encounter situations where we want to deserialize a response for inspections.
After creating a new johtoselvityshakemus, the audit log table should have a HAKEMUS type log entry.
> HAI-2275 Add audit logging for hakemus creation

- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/hakemus/HakemusControllerITest.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/hakemus/HakemusServiceITest.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/hakemus/HankekayttajaDeleteServiceITest.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/hakemus/HakemusController.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/hakemus/HakemusService.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/factory/HakemusBuilder.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/factory/HakemusFactory.kt
HakemusController is missing an exception handler for `ApplicationGeometryNotInsideHankeException`. Add the missing handler.
Clean up HakemusControllerITest a bit while adding a test for the new exception handler.
Rename `save()` to `saveEntity()` in HankeBuilder to match the naming conventions elsewhere. Add a new `save()` that returns Hakemus instead of the entity. Use the new `save()` wherever it doesn't cause problems.
Add `getById()` to HakemusService, which returns a Hakemus domain object. Use it in the `HakemusResponse` method. Replace the `hakemusResponseWithYhteystiedot()` by converting the entity to Hakemus first and then calling `Hakemus.toResponse()`.
> HAI-2301 Add a missing exception handler

- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/application/ApplicationControllerITest.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/application/ApplicationServiceITest.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/hakemus/HakemusControllerITest.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/hakemus/HakemusServiceITest.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/HankeError.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/application/ApplicationService.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/hakemus/HakemusController.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/hakemus/HakemusDataMapper.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/hakemus/HakemusDataValidator.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/hakemus/HakemusService.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/hakemus/HakemusUpdateRequest.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/hakemus/Hakemusyhteystieto.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/hakemus/JohtoselvityshakemusErrorValidation.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/hakemus/JohtoselvityshakemusMissingValidation.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/validation/Validators.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/TestExtensions.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/application/ApplicationServiceTest.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/factory/ApplicationFactory.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/factory/HakemusBuilder.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/factory/HakemusFactory.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/factory/HakemusResponseFactory.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/factory/HakemusUpdateRequestFactory.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/factory/HankeBuilder.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/factory/HankeFactory.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/factory/HankeKayttajaFactory.kt
Send the hakemus to Allu like before, except use Kortisto to get the customers and contacts. Also, set the orderer to be the user who does the sending. This means they have to be a contact on the application.
Disclosure logging and sending the form data PDF will be added in later PRs.
> HAI-2301 API for sending hakemus to Allu

- email/kayttaja-poistettu-hanke.mjml
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/email/EmailSenderServiceITest.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/permissions/HankeKayttajaControllerITest.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/permissions/HankekayttajaDeleteServiceITest.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/email/EmailSenderService.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/permissions/HankeKayttajaController.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/permissions/HankekayttajaDeleteService.kt
- services/hanke-service/src/main/resources/email/template/kayttaja-poistettu-hanke.html.mustache
- services/hanke-service/src/main/resources/email/template/kayttaja-poistettu-hanke.subject.mustache
- services/hanke-service/src/main/resources/email/template/kayttaja-poistettu-hanke.text.mustache
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/email/EmailSenderServiceTest.kt
Send an email notification when the user is removed from Hanke.
Create a new Hanke or add some (deletable) user on existing Hanke. Use Swagger UI or Haitaton UI (in branch of this PR: https://github.com/City-of-Helsinki/haitaton-ui/pull/605). When deleting a user it should receive an email notification about deletion.
> HAI-2411 Send an email notification when the user is removed from Hanke

- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/hakemus/HakemusServiceITest.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/allu/AlluApplicationData.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/allu/AlluCommonDomain.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/application/ApplicationService.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/hakemus/HakemusService.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/hakemus/HakemusyhteystietoValidation.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/logging/DisclosureLogService.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/application/ApplicationServiceTest.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/factory/AuditLogEntryFactory.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/factory/HakemusyhteyshenkiloFactory.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/hakemus/HakemusServiceTest.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/logging/DisclosureLogServiceTest.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/test/AuditLogEntryAsserts.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/test/AuditLogEntryEntityAsserts.kt
Use the Allu types when logging data sent to Allu, so we log the actual data being sent, not any Haitaton data representation.
There's a lot of duplication in DisclosureLogService in sending AlluApplicationData instead of ApplicationData. The methods handling ApplicationData can be removed soon when we remove ApplicationController.
> HAI-2301 Add disclosure logging to sending a hakemus to Allu

- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/application/ApplicationServiceITest.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/hakemus/HakemusServiceITest.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/allu/CableReportService.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/hakemus/HakemusPdfService.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/hakemus/HakemusService.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/application/ApplicationServiceTest.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/factory/HakemusFactory.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/factory/HakemusyhteyshenkiloFactory.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/factory/HakemusyhteystietoFactory.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/hakemus/HakemusPdfServiceTest.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/hakemus/HakemusServiceTest.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/test/TestUtils.kt
Add creating a PDF from the hakemus form data. The created PDF is identical to how it looked before Kortisto.
Create a separate HakemusPdfService for generating the PDF. It's very similar to ApplicationPdfService, but it can be removed soon when purging the old Application package.
> HAI-2301 Add PDF generation

- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/logging/DisclosureLogService.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/factory/ApplicationFactory.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/logging/DisclosureLogServiceTest.kt
If the invoicing customer is a person, their information should be logged in disclosure logs when the application information is sent to Allu.
I'm afraid we'll forget to add this later, so I'm adding it now.
> HAI-2301 Add disclosure logging for invoicing customer

- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/hakemus/HakemusControllerITest.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/hakemus/HakemusServiceITest.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/hakemus/Hakemus.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/hakemus/HakemusController.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/hakemus/HakemusService.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/factory/HakemusBuilder.kt
Copy the decision endpoint from ApplicationController to HakemusController, along with the service implementation. There are no changes in how downloading the decision from Allu works with kortisto, so only some factory calls and such needed to be modified.
Rename `cableReportService` to `alluClient` in `HakemusServiceITest` to match the naming in the service itself.
Make a decision in Allu for an application. Download it from Haitaton.
> HAI-2376 Copy decision download functionality to hakemus side

- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/hakemus/HakemusControllerITest.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/hakemus/HakemusServiceITest.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/application/ApplicationService.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/attachment/application/ApplicationAttachmentService.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/hakemus/HakemusController.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/hakemus/HakemusService.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/hakemus/HakemusServiceTest.kt
Copy the application cancellation and deletion endpoint from ApplicationController to HakemusController, along with the service implementation. Modify some method boundaries to make the code easier to test.
Create a johtoselvityshakemus and then cancel it.
> HAI-2375 Copy application cancellation / deletion endpoint to hakemus

- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/application/ApplicationAuthorizerITest.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/application/ApplicationControllerITest.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/application/ApplicationServiceITest.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/attachment/application/ApplicationAttachmentServiceITest.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/hakemus/HakemusControllerITest.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/hakemus/HakemusServiceITest.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/HankeService.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/application/Application.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/application/ApplicationEntity.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/application/ApplicationService.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/attachment/application/ApplicationAttachmentContentService.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/attachment/application/ApplicationAttachmentMetadataService.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/attachment/application/ApplicationAttachmentService.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/gdpr/GdprService.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/hakemus/Hakemus.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/hakemus/HakemusService.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/hakemus/HankkeenHakemuksetResponse.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/logging/DisclosureLogService.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/permissions/HankeKayttajaService.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/testdata/TestDataService.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/application/ApplicationControllerTest.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/application/ApplicationServiceTest.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/factory/ApplicationAttachmentFactory.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/factory/ApplicationFactory.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/factory/HakemusBuilder.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/factory/HakemusFactory.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/logging/DisclosureLogServiceTest.kt
We have three different IDs for a hakemus: there's our database ID (`id`), Allu's ID (`alluid`) and the official identifier of the hakemus (`applicationIdentifier`). When logging application events, different combinations of these have been arbitrarily added to log rows. There has also been some variance in the formatting of the ID fields.
Add a new interface that groups these three values, and different views of applications can implement that. The interface provides a way to log all three IDs uniformly. It also provides a simple way of passing all the values needed for logging them in a single value.
Implement the interface for Hakemus and ApplicationEntity. Change all the logging where the logging parameter was calling the `id` field directly to use the new identifier. Just the ID is …
> HAI-2375 Improve logging of hakemus ID's

- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/permissions/HankekayttajaDeleteServiceITest.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/permissions/HankekayttajaDeleteService.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/factory/HakemusBuilder.kt
Currently, when the hankekayttaja is a contact in several roles of the same application, the delete info endpoint returns copies of those applications. This is not correct, and shows up as duplicates to the user.
Return each distinct application just once.
1. When making johtoselvityshakemus, create a new contact and add it to several roles.
2. Save and go to user management.
3. Click on remove user for the user you created earlier.
4. See that the application is mentioned only once in the confirmation popup.
> HAI-2370 Make kayttaja/deleteInfo return every hakemus just once

- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/permissions/HankekayttajaDeleteServiceITest.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/permissions/HankeKayttaja.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/permissions/HankekayttajaDeleteService.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/factory/HankeKayttajaFactory.kt
Kutsuja ID field is set to be the ID of the hankekayttaja that invited the user. When a user is deleted, this ID isn't cleared, which blocks the deletion of the user because of database constraints.
When deleting a user, set the kutsuja ID to null for all hankekayttaja with the user as their kutsuja.
Create a hanke and add people as contacts. Set one of them as a contact for the owner and give them KAIKKI_OIKEUDET. Try to delete yourself from the hanke.
> HAI-2483 Clear kutsuja id when deleting user

- docker-compose.yml
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/hakemus/HakemusMigrationServiceITest.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/Persistence.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/hakemus/HakemusMigrationScheduler.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/hakemus/HakemusMigrationService.kt
- services/hanke-service/src/main/resources/application.yml
Add a startup trigger for migrating hakemus customers and contacts to separate tables. Also, add logging for tracking the migration progress.
There are no customers in hankkeet in production, so those are not migrated.
To test this, the database needs to be consistent, i.e. each application should have either customers in application data or in the separate table.
To see it working, create some johtoselvityshakemus with the old system:
1. Set `HAITATON_FEATURE_HANKE_EDITING` and `HAITATON_FEATURE_USER_MANAGEMENT` to false in either `docker-compose.yml` or `.env`.
2. Set `REACT_APP_FEATURE_HANKE` and `REACT_APP_FEATURE_ACCESS_RIGHTS` to 0 in `docker-compose.yml`.
3. Restart hanke-service and UI containers.
4. Create some johtoselvityshakemus from the Haitaton UI.
5. Re-enable the features …
> HAI-2231 Add startup trigger for the migration

- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/permissions/HankekayttajaDeleteServiceITest.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/logging/HankeKayttajaLoggingService.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/logging/PermissionLoggingService.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/permissions/HankekayttajaDeleteService.kt
Delete the associated permission entry when deleting a hankekayttaja. Otherwise, the user will still have access to the hanke after deleting, but they will not show up in the user management view.
Also add audit logging to deleting hankekayttaja. Log deletions of both the hankekayttaja and permission.
Delete your own permissions. You shouldn't be able to access the hanke anymore.
> HAI-2486 Remove permission when deleting hankekayttaja

- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/application/ApplicationAuthorizerITest.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/application/ApplicationControllerITest.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/hakemus/HakemusControllerITest.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/hakemus/HakemusServiceITest.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/application/ApplicationAuthorizer.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/hakemus/CreateHakemusRequest.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/hakemus/CreateHakemusRequestValidator.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/hakemus/HakemusController.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/hakemus/HakemusService.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/hakemus/HakemusUpdateRequestValidator.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/factory/CreateHakemusRequestFactory.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/hakemus/CreateHakemusRequestValidatorsTest.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/hakemus/HakemusResponseDeserializer.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/test/Asserts.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/test/JacksonTestExtension.kt
Implement creating a new hakemus in HakemusController. This has a couple of key differences from the previous implementation in ApplicationController:
- The endpoint supports kaivuilmoitus.
- The endpoint only accepts hakemusdata from the application form's first page.
Can be tested with Swagger UI.
> HAI-2374 copy POST /hakemukset to hakemus controller

- email/kayttaja-lisatty-hakemus.mjml
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/application/ApplicationServiceITest.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/email/EmailSenderServiceITest.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/email/FilteredEmailSenderServiceITest.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/hakemus/HakemusServiceITest.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/application/ApplicationEntity.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/application/ApplicationService.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/email/EmailSenderService.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/hakemus/HakemusService.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/permissions/HankeKayttaja.kt
- services/hanke-service/src/main/resources/email/template/kayttaja-lisatty-hakemus.html.mustache
- services/hanke-service/src/main/resources/email/template/kayttaja-lisatty-hakemus.subject.mustache
- services/hanke-service/src/main/resources/email/template/kayttaja-lisatty-hakemus.text.mustache
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/email/EmailSenderServiceTest.kt
Send a notification email when a user is added on the application as a contact person. Since the email subject and text changed a bit they will need a translation (information about this was added in translation issue: https://helsinkisolutionoffice.atlassian.net/browse/HAI-2446).
Create a new Johtoselvityshakemus, fill it up until Yhteystiedot, add a new contact person. It should receive an email notification.
or other location: https://helsinkisolutionoffice.atlassian.net/wiki/spaces/HAI/pages/8189902867/S+hk+posti-ilmoitukset+k+ytt+j+lle
> HAI-2456 Send a notification email when a user is added on the application as a contact person

- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/ApiBlockingFilter.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/hakemus/HakemusMigrationScheduler.kt
@ConditionalOnProperty.havingValue is by-default '' and this empty string is used for environments when the actual value is not yet used. This caused the API to be disabled when it should not have been.
This error affected both `haitaton.api.disabled` and `haitaton.migration.enabled` environment variables.
> HAI-2468 Bugfix for not-enabling API blocking when the environment variable is not set

- email/kayttaja-lisatty-hakemus.mjml
- email/kayttaja-poistettu-hanke.mjml
- email/kayttooikeustason-muutos.mjml
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/email/EmailSenderServiceITest.kt
- services/hanke-service/src/main/resources/email/template/kayttaja-lisatty-hakemus.html.mustache
- services/hanke-service/src/main/resources/email/template/kayttaja-lisatty-hakemus.text.mustache
- services/hanke-service/src/main/resources/email/template/kayttaja-poistettu-hanke.html.mustache
- services/hanke-service/src/main/resources/email/template/kayttaja-poistettu-hanke.subject.mustache
- services/hanke-service/src/main/resources/email/template/kayttaja-poistettu-hanke.text.mustache
- services/hanke-service/src/main/resources/email/template/kayttooikeustason-muutos.html.mustache
- services/hanke-service/src/main/resources/email/template/kayttooikeustason-muutos.subject.mustache
- services/hanke-service/src/main/resources/email/template/kayttooikeustason-muutos.text.mustache
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/email/EmailSenderServiceTest.kt
Added translations for email messages. Still missing one though: adding a new user to the application (text has been slightly changed and translations are still missing).
> New translations for email messages

- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/permissions/HankeKayttajaControllerITest.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/permissions/HankeKayttajaServiceITest.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/permissions/HankeKayttajaController.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/permissions/HankeKayttajaService.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/factory/HankeKayttajaFactory.kt
Return the updated hankekayttaja after resending an invitation to a hanke. This enables the frontend to read the new invitation date from the response, so they don't have to request it separately.
Resend an invitation from the UI and check the response from the network tab of the development tools.
> HAI-2537 Return hankekayttaja after resending the invitation

- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/application/ApplicationServiceITest.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/hakemus/HakemusServiceITest.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/permissions/HankeKayttajaServiceITest.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/application/ApplicationArea.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/application/ApplicationData.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/hakemus/Hakemus.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/hakemus/HakemusResponse.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/hakemus/HakemusUpdateRequest.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/allu/ApplicationPdfServiceTest.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/application/ApplicationDataMapperTest.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/factory/ApplicationFactory.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/factory/HakemusBuilder.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/factory/HakemusFactory.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/factory/HakemusResponseFactory.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/factory/HakemusUpdateRequestFactory.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/hakemus/HakemusPdfServiceTest.kt
First PR for creating a separate application area data structure for excavation notifcation. In this PR the current `ApplicationArea` data class is refactored as a sealed interface and identical two implementation data classes have been made, one for cable report and other for excavation notification. In later PR the data needed for excavation notification application area is added.
> HAI-1542 Separate ApplicationArea for cable report and excavation notification

- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/attachment/application/ApplicationAttachmentControllerITest.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/attachment/application/ApplicationAttachmentServiceITest.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/attachment/application/ApplicationAttachmentController.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/attachment/application/ApplicationAttachmentMetadataService.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/attachment/application/ApplicationAttachmentService.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/hakemus/HakemusPdfService.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/hakemus/HakemusService.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/factory/ApplicationAttachmentFactory.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/hakemus/HakemusPdfServiceTest.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/hakemus/HakemusServiceTest.kt
Add attachment names to the application-form-data.pdf that's sent to Allu alongside the application.
Add attachments to a johtoselvityshakemus and send it to Allu. Check Allu that the form data PDF has the attachment names in it.
> HAI-2535 Add attachment names to application-form-data.pdf

- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/permissions/HankekayttajaDeleteServiceITest.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/permissions/HankekayttajaDeleteService.kt
Only allow the user to be deleted if no other identified users have KAIKKI_OIKEUDET permissions. So far, the check has included unidentified users.
The check is tightened to make it less likely the hanke gets stuck without anyone who can manage it.
1. Create a johtoselvityshakemus (or a hanke in dev).
2. Add a contact person.
3. Give them KAIKKI_OIKEUDET.
4. Try to remove yourself from the project.
5. The backend should refuse.
> HAI-2542 Tighten the user deletion check

- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/hakemus/HakemusServiceITest.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/hakemus/HakemusService.kt
Don't send application notification emails when the recipient email would be the same as the inviter email. Effectively, this means that the user adding themselves as a new contact to an application won't receive an email about it.
Add yourself as a contact on a new application. Check [smtp4dev](http://localhost:3003/) that there are no notifications sent.
> HAI-2552 Exclude inviter from hakemus emails

- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/hakemus/HakemusServiceITest.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/attachment/application/ApplicationAttachmentService.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/attachment/common/MockFileClient.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/attachment/common/MockFileClientExtension.kt
When deleting application, all its attachments are also deleted. If for some reason Azure Blob Storage cannot be reached the deletion of attachment content fails but the application is already cancelled in Allu. This leads to an inconsistency between Haitaton and Allu. 
This PR proposes a fix that allows running the deletion process through even if the content cannot be deleted due to an error in accessing Azure Blob Storage. This leaves the attachment content undeleted in blob storage but the attachment metadata in database is deleted.
This PR does not try to fix the other problem concering the allowance of deleting applications in CANCELLED state. There will be other PR for that fix.
Please describe …
> HAI-2553 Allow deleting the application even when deleting the content of the application attachments fails

- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/hakemus/HakemusServiceITest.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/attachment/application/ApplicationAttachmentService.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/hakemus/HakemusService.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/attachment/common/MockFileClient.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/attachment/common/MockFileClientExtension.kt
When an application is cancelled in Haitaton, it should be able to be deleted. Normally, when application gets cancelled it is automatically deleted but if there is an error in e.g. removing attachment content from Azure Blob Storage, the application might get cancelled (first the application is cancelled in Allu and from there the status will transfer back to Haitaton) but not deleted. This PR will fix this by allowing the deletion of cancelled application.
UI will need changes too in order to show the "Peru hakemus" button when application is already cancelled.
This can be tested with [Swagger UI](http://localhost:3001/api/swagger-ui/index.html#/hakemus-controller/delete_1) after manually setting the proper status for an application:
```
update
applications
set
alluid=85, …
```
> HAI-2553 Allow deleting a cancelled application

- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/HankeServiceITests.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/HankeService.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/hakemus/HakemusService.kt
Deleting a Hanke that has cancelled applications is allowed.
This can be tested in similar manner as deleting cancelled applications: https://github.com/City-of-Helsinki/haitaton-backend/pull/717
> HAI-2553 Allow deleting hanke with cancelled applications

- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/hakemus/HakemusServiceITest.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/application/ApplicationData.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/factory/HakemusUpdateRequestFactory.kt
Fixed bug when kaivuilmoitus application data was loaded and transformed into a domain object. It did not set `requiredCompetence` field.
* With UI: create/open a kaivuilmoitus, check required competence, save and check the result - required competence should be checked
* With Swagger: call PUT /hakemukset/{id} with data that has `requiredComperence: true`. Check the response.
> Fixed setting required competence value

- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/attachment/application/ApplicationAttachmentControllerITest.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/attachment/application/ApplicationAttachmentServiceITest.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/HankeError.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/attachment/application/ApplicationAttachmentController.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/attachment/application/ApplicationAttachmentService.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/attachment/common/Exceptions.kt
Disallow requests for attachment content when the attachment is of the `VALTAKIRJA` type. Return 403 Forbidden when such a request is made. This is done because of privacy reasons.
Using [Swagger UI](http://localhost:3001/api/swagger-ui/index.html#/), add a valtakirja to hakemus and then try to download the content.
> HAI-2346 Disallow getting valtakirja content

- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/attachment/application/ApplicationAttachmentServiceITest.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/attachment/application/ApplicationAttachmentController.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/attachment/application/ApplicationAttachmentService.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/attachment/common/AttachmentValidator.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/attachment/hanke/HankeAttachmentController.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/attachment/AttachmentValidatorTest.kt
Only accept PDF attachments for `LIIKENNEJARJESTELY` and `VALTAKIRJA` type attachments. Traffic arrangements need to be PDFs since they are attached to the decision in Allu. The valtakirja needs to be a PDF since it needs to be signed.
Change the consumes parameters for the attachment controllers. This enables attachment uploading in SwaggerUI.
http://localhost:3001/api/swagger-ui/index.html#/application-attachment-controller/postAttachment_1
> HAI-2345 Only allow PDFs for attachments other than MUU

- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/HankeControllerITests.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/HankeServiceITests.kt
- services/hanke-service/src/integrationTest/resources/fi/hel/haitaton/hanke/logging/expectedHankeWithPolygon.json.mustache
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/HankealueEntity.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/tormaystarkastelu/TormaystarkasteluLuokittelu.kt
- services/hanke-service/src/main/resources/db/changelog/changesets/073-change-haitat-to-enum-names.sql
- services/hanke-service/src/main/resources/db/changelog/db.changelog-master.yaml
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/domain/HankeTest.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/factory/ApplicationFactory.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/factory/HankealueFactory.kt
- Save all haitat as enum names instead of index numbers. This is kinder for maintenance and allows adding new values without shuffling the values around.
- Migrate the existing database rows to use the columns.
- Give the melu, pöly and tärinä -haitat index values, which might be needed later.
- Rename the melu/pöly/tärinä values to match the current UI design.
- Add a value for "Ei haittaa" for each of melu, pöly and tärinä with an index value of 0.
UI will be broken until a matching change has been made.
> HAI-2463 Add indexes to haitat

- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/HankeServiceITests.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/UpdateHankeITests.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/test/AuditLogEntryEntityAsserts.kt
HankeServiceITests has been a bit unwieldy. It's been really long, and more than half of the tests have been for `updateHanke`. They have been sprinkled around the test class between blocks of tests for other methods.
Move the tests for `updateHanke` to a separate test class. This consolidates them in a single place and makes them easier to manage.
> HAI-1378 Move updateHanke tests to a separate test class

- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/HankeControllerITests.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/HankeServiceITests.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/UpdateHankeITests.kt
- services/hanke-service/src/integrationTest/resources/fi/hel/haitaton/hanke/logging/expectedHankeWithPolygon.json.mustache
- services/hanke-service/src/integrationTest/resources/fi/hel/haitaton/hanke/logging/expectedNewHanke.json.mustache
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/HankeMapper.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/HankeService.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/HankealueEntity.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/HankealueService.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/Persistence.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/domain/Hanke.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/domain/SavedHankealue.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/tormaystarkastelu/TormaystarkasteluLaskentaService.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/tormaystarkastelu/TormaystarkasteluTulos.kt
- services/hanke-service/src/main/resources/db/changelog/changesets/075-change-tormaystarkastelutulos-to-refer-to-hankealue.sql
- services/hanke-service/src/main/resources/db/changelog/db.changelog-master.yaml
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/domain/HankeTest.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/factory/HankeFactory.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/factory/HankealueFactory.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/tormaystarkastelu/TormaystarkasteluLaskentaServiceTest.kt
The calculated tormaystarkastelu results are saved and returned with each hankealue. One tormaystarkastelu is also returned for the whole hanke, for backwards compatibility. That's calculated by taking the worst cases from all of the areas.
Wipe all existing tormaystarkastelu, because they're not used in production and they can't be converted.
1. Add several hankealue to a hanke.
2. Check the response from the browser's network tab to see that there are tormaystarkastelu under the hankealueet.
3. Check that the tormaystarkastelu are saved in DB.
> HAI-1378 Calculate haittaindeksi separately for each hankealue

- docker-compose.yml
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/HankeControllerITests.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/HankeServiceITests.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/UpdateHankeITests.kt
- services/hanke-service/src/integrationTest/resources/clear-db.sql
- services/hanke-service/src/integrationTest/resources/fi/hel/haitaton/hanke/logging/expectedHankeWithPolygon.json.mustache
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/HankeMapper.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/HankealueEntity.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/HankealueService.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/domain/BaseHanke.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/domain/CreateHankeRequest.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/domain/ModifyHankealueRequest.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/domain/SavedHankealue.kt
- services/hanke-service/src/main/resources/db/changelog/changesets/076-create-hankkeen-haittojenhallintasuunnitelma-table.sql
- services/hanke-service/src/main/resources/db/changelog/db.changelog-master.yaml
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/HankeMapperTest.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/factory/HankeBuilder.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/factory/HankealueFactory.kt
Project areas can have nuisance management plans for different nuisance types.
Also, unrelated, added quotes in port definitions in `docker-compose.yml`.
1. Start the backend
2. Create a new project or use an existing one and update its data via API: http://localhost:3001/api/swagger-ui/index.html#/hanke-controller/updateHanke. Add nuisance management plan in the data:
```
{
"id": 10,
"hankeTunnus": "HAI24-10",
...
"alueet": [
{
"id": 56,
"hankeId": 10,
...
"haittojenhallintasuunnitelma": {
"YLEINEN": "Yleinen haittojenhallinta",
"PYORALIIKENNE": "Pyöräliikenteelle koituvien haittojen hallinta",
"AUTOLIIKENNE": "Autoliikenteelle koituvien haittojen hallinta",
"RAITIOLIIKENNE": "Raitioliikenteelle koituvien haittojen hallinta",
"LINJAAUTOLIIKENNE": "Linja-autoliikenteelle koituvien …
```
> HAI-1383 Add nuisance management plan for project area

- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/security/OAuth2ResourceServerSecurityConfiguration.kt
- services/hanke-service/src/main/resources/application.yml
- services/hanke-service/src/test/resources/application-test.yml
Set GDPR API active by default. It has been active in all cloud environments for over a year now.
Removing the option of disabling the API was considered, but tests broke down when attempting it. Spring Security tries to contact the issuer at startup, but the value is filled with a placeholder. We don't want it to contact any actual cloud service, because that would make the tests very unreliable.
It might be possible to solve this by starting a correct test container that runs some kind of OAuth authenticator. It didn't feel worth the effort at this point. We might need to return to this in the fall when we move to a JWT-based authentication.
> HAI-2356 Set GDPR API active by default

- docker-compose.yml
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/UpdateHankeITests.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/validation/HankePublicValidator.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/validation/HankePublicValidatorTest.kt
The nuisance control plan is always required for the YLEINEN and MUUT categories. For the transport categories (AUTOLIIKENNE, LINJAAUTOLIIKENNE, RAITIOLIIKENNE and PYORAILYLIIKENNE) it's required if the matching nuisance index in tormaystarkastelu is higher than zero. Currently, the car traffic index is always higher than zero if the index has been calculated, but it's checked the same way regardless.
If the tormaystarkastelu is not yet calculated, the transport categories are not checked because we don't know which categories are required. It's always calculated when all necessary information has been given, so either the validation will fail somewhere else or the tormaystarkastelu will be calculated.
Check that the project is not public until the nuisance control plan has been filled …
> HAI-2385 Require nuisance control plan for public hanke

- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/tormaystarkastelu/TormaystarkasteluControllerITest.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/tormaystarkastelu/TormaystarkasteluTormaysServiceITest.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/geometria/GeometriatDao.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/geometria/GeometriatValidator.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/tormaystarkastelu/TormaystarkasteluController.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/tormaystarkastelu/TormaystarkasteluLaskentaService.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/tormaystarkastelu/TormaystarkasteluRequest.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/tormaystarkastelu/TormaystarkasteluTormaysService.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/tormaystarkastelu/TormaystarkasteluLaskentaServiceTest.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/tormaystarkastelu/TormaystarkasteluLaskentaServiceWithGeometryTest.kt
The API takes the hankealue geometry, start date, end date and lane obstruction information. This is intended to be used with the hanke form, so the geometry is read as a FeatureCollection.
The underlying calculation needed to be duplicated down to the database level, since the existing calculations expect the geometries to be stored in the hankegeometria table. The transient geometries are not, of course.
The new calculations use GeoJsonObject as geometries after the first call, so it should be easy to adapt these for applications.
http://localhost:3001/api/swagger-ui/index.html#/tormaystarkastelu-controller/calculate
The body can be copied from a hankealue response JSON.
> HAI-2389 Add API for calculating nuisance indexes

- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/attachment/common/AttachmentValidator.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/attachment/AttachmentValidatorTest.kt
Change the file name sanitazion to split the filename to base and extension and sanitize those separately. Then rejoin them and add a dot if extension is not empty.
This way, dot can be added as an invalid character and all other dots except the extension separator will be replaced with the underscore `_`. File names with path traversal will have their `../` segments changed to `___`.
Handle null filenames separately to make this process easier.
1. Create a file with a name like `testi luon..txt`.
2. Add it to a hanke or hakemus.
3. After saving its filename should be shown as `testi luon_.txt`.
> HAI-2601 Accept filename that ends in a dot

- services/hanke-service/build.gradle.kts
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/permissions/HankeKayttajaServiceITest.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/tormaystarkastelu/TormaystarkasteluTormaysService.kt
- Restyle the older methods in TormaystarkasteluTormaysService.kt to match the newer ones.
- For `getIntersectingBusRoutes`
- Implement the DISTINCT ON (route_id, direction_id)
- Select only the columns that are used in the row mapper.
- Share the row mapper with the GeoJSON version
- Remove unused methods from `HankeKayttajaServiceITest`.
- In the build script, replace the deprecated `kotlinOptions` with the newer `compilerOptions`.
> HAI Refactor TormaysService and remove unused test methods

- services/hanke-service/build.gradle.kts
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/allu/CableReportServiceITests.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/allu/CableReportService.kt
Refactor cable report service to reuse query code. Extract common parts of query building to separate functions to reuse those.
Add Allu login token reuse. Reuse the Allu login token until it expires. Renew it 5 minutes before expiration, so it doesn't expire while e.g. uploading a set of attachments.
The login token reuse can be checked by searching the logs for the phrase `Renewed Allu login token with expiration date`. It should happen only once every two hours.
The actual tests for sending a kaivuilmoitus will be added later in a separate PR.
> HAI-2417 Refactor cable report service

- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/HankeServiceITests.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/allu/AlluClientITests.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/attachment/application/ApplicationAttachmentServiceITest.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/configuration/MockAlluClient.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/hakemus/HakemusServiceITest.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/allu/AlluClient.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/attachment/application/ApplicationAttachmentService.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/configuration/Configuration.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/hakemus/AlluUpdateService.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/hakemus/HakemusService.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/hakemus/AlluUpdateServiceTest.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/hakemus/HakemusServiceTest.kt
CablereportService now handles other applications as well, not just cable reports. Rename it to AlluClient so it's more accurate.
> HAI-1373 Rename cable report service

- email/johtoselvitys-valmis.mjml
- email/kayttaja-lisatty-hakemus.mjml
- email/kayttaja-lisatty-hanke.mjml
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/email/EmailSenderServiceITest.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/permissions/HankeKayttajaServiceITest.kt
- services/hanke-service/src/main/resources/email/template/johtoselvitys-valmis.html.mustache
- services/hanke-service/src/main/resources/email/template/kayttaja-lisatty-hakemus.html.mustache
- services/hanke-service/src/main/resources/email/template/kayttaja-lisatty-hakemus.text.mustache
- services/hanke-service/src/main/resources/email/template/kayttaja-lisatty-hanke.html.mustache
- services/hanke-service/src/main/resources/email/template/kayttaja-lisatty-hanke.subject.mustache
- services/hanke-service/src/main/resources/email/template/kayttaja-lisatty-hanke.text.mustache
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/email/EmailSenderServiceTest.kt
Changed invitation email texts.
* Add a new contact person to a project and see that he/she gets a correct email according to specs (see below)
* Add a new contact person to an application and see that he/she gets correct emails (one for inviting to the project, another for adding to the application)
* Resend an invitation email to a contact person and see that he/she gets a correct email
or other location: https://helsinkisolutionoffice.atlassian.net/wiki/spaces/HAI/pages/8189902867/S+hk+posti-ilmoitukset+k+ytt+j+lle
> HAI-2583 Changed invitation emails - translations pending

- services/hanke-service/build.gradle.kts
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/ControllerExceptionHandler.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/configuration/LockService.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/hakemus/AlluUpdateService.kt
- services/hanke-service/src/test/resources/application-test.yml
Some fixes were needed to get the upgrade to work:
- Add an exception handler for NoResourceFoundException. After the
update, TestDataController endpoints started to return 500 Internal
error when they were called with the controller disabled by environment
variables. Before the update, they returned 404 Not Found. The added
exception handler returns the expected behaviour.
- Disable AlluUpdateService and LockService in tests. They're not
used, but they cause problems when the test context is shutting down.
There's a problem with TestContainer and Spring lifetimes, where the
test container is shutdown before the application context, causing the
database connections to time out. The thing trying to call the
database at shutdown is the JdbcLockRegistry.
- Use reusable containers. This is an …
> HAI Upgrade Spring Boot to 3.2.8

- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/paatos/PaatosServiceITest.kt
- services/hanke-service/src/integrationTest/resources/clear-db.sql
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/paatos/Enums.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/paatos/Paatos.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/paatos/PaatosEntity.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/paatos/PaatosRepository.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/paatos/PaatosService.kt
- services/hanke-service/src/main/resources/db/changelog/changesets/078-create-paatos-table.sql
- services/hanke-service/src/main/resources/db/changelog/db.changelog-master.yaml
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/factory/PaatosFactory.kt
The decisions for a excavation notification can be replaced several times over. We need to store the history of those decisions.
Add a table for storing the decision history.
or other location: DB comments
> HAI-2610 Create a db table for decisions

- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/attachment/application/ApplicationAttachmentContentServiceITest.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/attachment/application/ApplicationAttachmentServiceITest.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/attachment/hanke/HankeAttachmentContentServiceITest.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/attachment/hanke/HankeAttachmentServiceITest.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/hakemus/HakemusControllerITest.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/hakemus/HakemusServiceITest.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/paatos/PaatosServiceITest.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/hakemus/HakemusController.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/hakemus/HakemusService.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/paatos/PaatosService.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/attachment/AttachmentTestUtil.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/factory/AlluFactory.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/factory/ApplicationAttachmentBuilder.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/factory/ApplicationAttachmentFactory.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/factory/HakemusFactory.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/factory/HankeAttachmentBuilder.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/factory/HankeAttachmentFactory.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/hakemus/HakemusServiceTest.kt
When an excavation notification gets a status update to DECISION:
- Download the decision PDF
- Upload the PDF to blob storage
- Read the name and start/end dates from Allu
- Save a new Paatos row to DB with information on the uploaded PDF and the current application information from Allu.
Also, drop the unused username parameter from
`HakemusService.downloadDecision`. This enables it to be reused in the background updates.
1. Create an excavation notification and send it to Allu.
2. In Allu, create a decision for it.
3. After a minute, the decision should be downloaded:
- The decision has been saved to the local blob storage (can be checked with Azure Storage Explorer)
- The information on the decision has been saved to the `paatos` database table.
> HAI-2606 Save the decision when an excavation notification gets one

- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/allu/AlluClientITests.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/hakemus/HakemusServiceITest.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/paatos/PaatosServiceITest.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/allu/AlluClient.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/hakemus/HakemusService.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/paatos/PaatosService.kt
When an excavation notification gets a status update to OPERATIONAL_CONDITION:
- Download the operational condition PDF
- Upload the PDF to blob storage
- Read the name and start/end dates from Allu
- Save a new Paatos row to DB with information on the uploaded PDF and the current application information from Allu.
1. Create an excavation notification and send it to Allu.
- The excavation notification (and the hanke) needs to be in the past to make this work. It's easier if the dates are in the winter before 15.4., so Allu will suggest adding the operational condition date to it.
2. In Allu, create a decision for it and set it to operational condition.
- Before making a decision, edit the application in Allu and click on the warning sign under `Kaivuilmoituksen voimassaolo
`. This will …
> HAI-2607 Save decisions for operational condition

- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/allu/AlluClientITests.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/hakemus/HakemusServiceITest.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/paatos/PaatosServiceITest.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/allu/AlluClient.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/hakemus/HakemusService.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/paatos/PaatosService.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/factory/ApplicationHistoryFactory.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/hakemus/HakemusServiceTest.kt
When an excavation notification gets a status update to FINISHED:
- Download the work finished PDF
- Upload the PDF to blob storage
- Read the name and start/end dates from Allu
- Save a new Paatos row to DB with information on the uploaded PDF and the current application information from Allu.
Also, refactor PaatosServiceITest to reduce duplication.
After following the instructions in #777, accept the "Loppuvalvonta" task for the application in Allu. This will move the application to finished status.
> HAI-2608 Save decisions for work finished

- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/hakemus/HakemusServiceITest.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/paatos/PaatosServiceITest.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/hakemus/HakemusService.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/paatos/PaatosRepository.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/paatos/PaatosService.kt
- services/hanke-service/src/main/resources/db/changelog/changesets/079-add-hakemustunnus-index-to-paatos.sql
- services/hanke-service/src/main/resources/db/changelog/db.changelog-master.yaml
Add handling of `REPLACED` status updates. Don't update the application status or identifier when we receive one. Instead, update all decisions in the `paatos` table with the same hakemustunnus as the update and set their status to `KORVATTU`.
Whenever Allu marks a decision as `REPLACED`, there should be a matching `DECISION` update with a new identifier.
1. Create an application and create a decision for it in Allu. You can also add an operational condition decision if you want.
2. Create a korvaava päätös in Allu and accept it.
3. Check that the `paatos` table has rows for both the replaced and the new decision and that their statuses are `KORVATTU` and `NYKYINEN`, respectively.
4. Check that Azure Storage Explorer shows files for both decisions.
> HAI-2609 Mark replaced decisions as `KORVATTU`

- services/hanke-service/Dockerfile-local
- services/hanke-service/Dockerfile-platta
The official Docker registry is declining pull requests for images because of rate limits.
As a temporary workaround, use AWS ECR images, which have a limit of one per second.
> HAI Use AWS ECR Docker images

- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/hakemus/HakemusService.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/pdf/Formatters.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/pdf/JohtoselvityshakemusPdfEncoder.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/pdf/PdfHelpers.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/pdf/JohtoselvityshakemusPdfEncoderTest.kt
- Move HakemusPdfService to a separate package for managing PDF stuff.
- Rename it to JohtoselvityshakemusPdfEncoder
- Split the reusable functions to separate files
> HAI-1549 Move PDF stuff to separate package

- services/hanke-service/build.gradle.kts
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/hakemus/HakemusServiceITest.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/hakemus/HakemusService.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/pdf/EnrichedKaivuilmoitusalue.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/pdf/Formatters.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/pdf/JohtoselvityshakemusPdfEncoder.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/pdf/KaivuilmoitusPdfEncoder.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/pdf/PdfHelpers.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/pdf/Translations.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/factory/HakemusFactory.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/hakemus/HakemusServiceTest.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/pdf/JohtoselvityshakemusPdfEncoderTest.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/pdf/KaivuilmoitusPdfEncoderTest.kt
When sending a kaivuilmoitus to Allu, create a PDF with the form content
and upload it to Allu. This way the Allu handlers can see the
information as it was entered into Haitaton before it was converted to
Allu data format.
Change the johtoselvityshakemus PDF to use Finnish formatting for decimal numbers while implementing that for kaivuilmoitus.
Refactor `Document.section` in `PdfHelpers` to take a receiver function as a parameter. This makes using it easier because the caller can call `row()` directly in the function body.
Also, upgrade ktfmt to latest version. This adds some formatting changes to
edited files, especially with trailing parentheses.
Send a kaivuilmoitus to Allu. The form data can be found from Allu UI under attachments.
For quickly testing just the PDF generation:
- …
> HAI-1549 Add PDF creation and uploading for kaivuilmoitus

- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/IntegrationTestConfiguration.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/banners/BannerControllerITest.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/banners/BannerFactory.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/banners/BannerServiceITest.kt
- services/hanke-service/src/integrationTest/resources/clear-db.sql
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/banners/BannerController.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/banners/BannerEntity.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/banners/BannerRepository.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/banners/BannerService.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/banners/BannerType.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/banners/BannersResponse.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/security/AccessRules.kt
- services/hanke-service/src/main/resources/db/changelog/changesets/080-create-ui-banners-table.sql
- services/hanke-service/src/main/resources/db/changelog/db.changelog-master.yaml
Add an API for serving notification banners for the UI. The UI will
fetch and display the banners. At this time, the banners need to be
manually added to the DB.
Also alphabetically sort the integration test configuration and clear-db
script.
- Follow the maintenance guide instructions for adding and removing banners.
- Use Swagger UI to see how it affects the API: http://localhost:3001/api/swagger-ui/index.html#/banner-controller/listBanners
or other location: https://helsinkisolutionoffice.atlassian.net/wiki/spaces/HAI/pages/8297807895/Yll+pito-ohje+maintenance+guide (Under expandable "Uudet ohjeet")
> HAI-2568 API for serving banner texts

- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/hakemus/HakemusServiceITest.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/attachment/application/ApplicationAttachmentService.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/hakemus/HakemusDataMapper.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/hakemus/HakemusEntityData.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/hakemus/HakemusService.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/hakemus/HakemusUpdateRequest.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/hakemus/Hakemusalue.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/hakemus/HakemusyhteystietoEntity.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/factory/AlluFactory.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/factory/ApplicationFactory.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/factory/HakemusBuilder.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/hakemus/HakemusServiceTest.kt
If the user chooses to create a new johtoselvityshakemus in kaivuilmoitus, it is created and sent to Allu before kaivuilmoitus is sent.
Changes include:
* Application data is validated at the beginning of the send process - before it was done later in the process
* In data-mapping there is no need to throw an exception if there is no address (there is no areas with address) because the address is not mandatory in Allu and the existence of areas is validated when they are mapped
* It is possible to create a johtoselvityshakemus from kaivuilmoitus with `KaivuilmoitusEntityData.toJohtoselvityshakemusEntityData()`
* There is a "shortcut" for saving attachments without running all the validations on it. This is more suitable for this use case when an existing attachment is copied from one …
> HAI-2398 Create and send johtoselvityshakemus when kaivuilmoitus is sent

- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/hakemus/HakemusControllerITest.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/hakemus/HakemusServiceITest.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/hakemus/HakemusController.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/hakemus/HakemusService.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/hakemus/HakemusWithPaatokset.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/paatos/PaatosResponse.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/factory/HakemusFactory.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/factory/PaatosFactory.kt
Add any decisions the application might have to the response when requesting a single decision. The decisions are returned under `paatokset`. Otherwise, the response remains the same.
1. Find an application that has decisions in DB.
2. Use Swagger UI to call the API: http://localhost:3001/api/swagger-ui/index.html#/hakemus-controller/getById
or other location: API docs
> HAI-2620 Add decisions to application response

- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/HankeServiceITests.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/hakemus/HakemusServiceITest.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/permissions/HankeKayttajaServiceITest.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/permissions/HankekayttajaDeleteServiceITest.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/permissions/PermissionServiceITest.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/hakemus/HakemusService.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/test/AuditLogEntryEntityAsserts.kt
When an accompanying johtoselvityshakemus is created, write the creation to the audit logs.
Create a new entity for the johtoselvityshakemus instead of copying one from the excavation notification. Set the founder to the current user instead of the excavation notification founder.
Also, introduce convenience methods for asserting that the object before or after is null. Adopt their use wherever it was done manually.
- Send an accompanying johtoselvityshakemus.
- Check the audit_logs database table for the CREATE entry.
> HAI-2398 Add audit logging to accompanying johtoselvityshakemus

- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/IntegrationTestConfiguration.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/hakemus/HakemusControllerITest.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/hakemus/HakemusServiceITest.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/paatos/PaatosAuthorizerITest.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/paatos/PaatosControllerITest.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/paatos/PaatosServiceITest.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/HankeError.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/logging/AuditLogEntry.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/logging/DisclosureLogService.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/paatos/Paatos.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/paatos/PaatosAuthorizer.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/paatos/PaatosController.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/paatos/PaatosMetadata.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/paatos/PaatosNotFoundException.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/paatos/PaatosService.kt
- services/hanke-service/src/main/resources/application.yml
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/factory/HakemusBuilder.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/factory/PaatosFactory.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/logging/DisclosureLogServiceTest.kt
Add an API for downloading decision and approval documents for operational conditions and work finished. Downloads are allowed to anyone with view access to the hanke.
Write the decision downloads to audit logs. The decisions contain personal information, so accessing them needs to be logged. Log paatos metadata, since we can't know what personal information is on the decisions.
Also, remove `APPLICATION` from audit log object types. It was only used in tests, and incorrectly in those. The tests were fixed as well.
Enable a recently added feature in Springdoc that trims indentation from Kotlin's multiline strings. Long descriptions and descriptions with markdown formatting can be written with natural indentations.
- Find out the decisions for an application with decisions with get single …
> HAI-1504 Add an API for downloading kaivuilmoitus decisions

- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/allu/AlluClientITests.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/allu/AlluClient.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/attachment/common/AttachmentEntity.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/attachment/common/Domain.kt
There's no field in Allu that would say which kind of attachment we're sending there. For the handlers looking at the application, it's useful knowledge so they don't have to open each one to see which one it is. So we include the type in the description field of the attachment.
1. Add attachments to an application
2. Send it to Allu
3. Look at the application in Allu and check that the attachments have descriptions with the attachment type
- The generated form data PDF has a different description which doesn't include the type
> HAI-2657 Send attachment type to Allu in description

- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/email/EmailSenderServiceITest.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/email/FilteredEmailSenderServiceITest.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/hakemus/HakemusServiceITest.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/email/EmailSenderService.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/hakemus/HakemusService.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/hakemus/HakemusServiceTest.kt
A bug has occurred a couple of times in dev environment where Haitaton starts spamming emails to the contacts of a hanke. This has happened because the database changes have been rolled back because of a key conflict. The emails were sent during the transaction before we were sure they could be completed successfully.
Fix this by using `@TransactionalEvenListener`, which listens to events sent through `ApplicationEventPublisher`, but waits (by default) for the database transaction to commit successfully before handling the event. If the commit fails, the event is not handled. This ensures that the changes have been committed to the database before we send the email, so we don't send the same email several times.
It's not really possible to test the case where the database commit fails, …
> HAI-2674 Send johtoselvitys complete emails after commit

- README.md
- docker-compose.yml
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/profiili/ProfiiliClientITest.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/profiili/ProfiiliClient.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/profiili/ProfiiliProperties.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/security/OAuth2ResourceServerSecurityConfiguration.kt
- services/hanke-service/src/main/resources/application.yml
Use the default JWT flow in Spring Security, since the default is Authorization Code with PKCE, which is what's used for the new Keycloak authorization.
Update the authentication to the Profiili API. With keycloak, getting the API token needs a different kind of request than before.
The address for the API token request can be fetched from the OpenID configuration endpoint. Getting it from there means we have one less environment-specific thing to configure.
- Start UI from the https://github.com/City-of-Helsinki/haitaton-ui/pull/828 branch.
- Login.
- See that you get the verified name on the header bar and the everything is working as it should.
> HAI-2651 Configure Haitaton for Keycloak instead of tunnistamo

- README.md
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/gdpr/GdprControllerITests.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/ControllerExceptionHandler.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/gdpr/GdprController.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/gdpr/GdprProperties.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/profiili/ProfiiliClient.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/security/OAuth2ResourceServerSecurityConfiguration.kt
- services/hanke-service/src/main/resources/application.yml
Fix authentication when GDPR API is enabled. Tunnistamo used a different authentication flow for regular API calls and GDPR API calls. Only the GDPR API used JWT, so we had a JWT decoder bean that handled that GDPR API authentication. After adopting the new Tunnistus (Keycloak) authentication, it would break when GDPR API was enabled since all incoming tokens would be decoded with the GDPR decoder. Fix this by making the GDPR flow call the proper function instead of relying on a special registered bean.
With Keycloak, the GDPR API authentication has a lot less environment-specific variables compared to Tunnistamo. The scope structure is always as same as the scopes themselves. The issuer and audience of the token are the same as the general purpose API, so the environment variables can be …
> HAI-2655 GDPR-API changes for new Tunnistus

- email/kaivuilmoitus-paatos.mjml
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/email/EmailSenderServiceITest.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/hakemus/HakemusServiceITest.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/email/EmailSenderService.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/hakemus/HakemusService.kt
- services/hanke-service/src/main/resources/email/template/kaivuilmoitus-paatos.html.mustache
- services/hanke-service/src/main/resources/email/template/kaivuilmoitus-paatos.subject.mustache
- services/hanke-service/src/main/resources/email/template/kaivuilmoitus-paatos.text.mustache
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/hakemus/HakemusServiceTest.kt
When email to all contacts of a kaivuilmoitus when it gets a decision.
The email needs translations.
1. Send a kaivuilmoitus to Allu
2. Create a decision in Allu
3. Check smtp4dev (http://localhost:3003) for the email
> HAI-2636 Send email when kaivuilmoitus gets a decision

- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/tormaystarkastelu/TormaystarkasteluTormaysServiceITest.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/tormaystarkastelu/TormaystarkasteluLaskentaService.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/tormaystarkastelu/TormaystarkasteluTormaysService.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/tormaystarkastelu/TormaystarkasteluLaskentaServiceTest.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/tormaystarkastelu/TormaystarkasteluLaskentaServiceWithGeometryTest.kt
Only use the `tormays_street_classes_polys` for calculating the street class of an area. Ylre data will be merged into that table as needed.
It's hard to find a place where this makes a difference. One such place is in Kalasatama / Suvilahti.
In dev, this shows green for a class 1 road because the planned Kaasutehtaankatu is in the YLRE material:
With this change, it's not recognized, because Liikenneväylät only have existing roads:
> HAI-2600 Use only table for street class calculation

- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/email/EmailSenderServiceITest.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/hakemus/HakemusServiceITest.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/email/EmailEvent.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/email/EmailSenderService.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/hakemus/HakemusService.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/permissions/HankeKayttajaService.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/permissions/HankekayttajaDeleteService.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/TestExtensions.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/email/EmailSenderServiceTest.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/hakemus/HakemusServiceTest.kt
Use `TransactionalEventListener` in all emails to send them after the database transaction has been closed. Sending the emails seems to be taking a while in production, so keeping the transaction active while the email is being sent can lead to problems.
There were cases in production where two application updates were sent back-to-back - probably because the user skipped the attachments page instinctively - which caused errors because the second update didn't see the database changes the first one had made, so it tried to create a second version of the same user.
This isn't a perfect solution for that problem, but keeping the transaction short should mitigate the problem.
One of the side effects of the problem was that the notification email for being added to an application was sent …
> HAI-2697 Send all emails after transactions

- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/HankeServiceITests.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/hakemus/HakemusServiceITest.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/HankeService.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/hakemus/HakemusService.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/factory/HankeBuilder.kt
When creating a new johtoselvitys without existing hanke, the phase of generated hanke is set to RAKENTAMINEN. Also, when creating new johtoselvityshakemus or kaivuilmoitus for an existing hanke, the phase of the hanke is set to RAKENTAMINEN if not already set.
For generated hanke:
* Create a new johtoselvityshakemus (without existing hanke)
* Fill enough data for johtoselvityshakemus in order to be able to save it
* Go to the hanke page of the generated hanke and see that its phase is Rakentaminen
* Check audit log rows that should be created for hanke updates
For other hanke:
* Create a new hanke and fill enough data for it in order it to public (ie. allow applications to be created for it) - also, SET THE PHASE TO SOMETHING ELSE THAN RAKENTAMINEN
* Create a new application for the …
> HAI-2661 Hanke into RAKENTAMINEN phase when new application is created

- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/hakemus/HakemusServiceITest.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/hakemus/HakemusService.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/hakemus/HakemusServiceTest.kt
When kaivuilmoitus is approved in operational condition an email is sent to all contact persons. The email is identical to the decision email.
* Create a kaivuilmoitus, fill it and send it to Allu
* Create a decision for it in Allu
* Announce it in operational condition in Haitaton
* Create an operational condition decision in Allu
* An identical email should come for both the decision and the operational condition decision
> HAI-2324 Send kaivuilmoitus operational condition approval email

- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/hakemus/HakemusServiceITest.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/hakemus/HakemusService.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/hakemus/HakemusServiceTest.kt
When kaivuilmoitus work is finished an email is sent to all contact persons. The email is identical to the decision email.
* Create a kaivuilmoitus, fill it and send it to Allu
* Create a decision for it in Allu
* Mark it as finished in Allu (Valvonta - Loppuvalvonta)
* An identical email should come for both the decision and "työ valmis" decision
> Hai 2325/email notification for kaivuilmoitus finished

- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/hakemus/HakemusControllerITest.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/hakemus/HakemusResponse.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/hakemus/HakemusUpdateRequest.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/hakemus/Hakemusyhteystieto.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/factory/HakemusResponseFactory.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/factory/HakemusUpdateRequestFactory.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/logging/DisclosureLogServiceTest.kt
Add the `registryKeyHidden` field to all hakemus responses where customer information is available. The value is true when the customer is of type person or other and has a non-null `registryKey`. When registryKeyHidden is true, overwrite the registry key with a null value.
> HAI-2625 Add registryKeyHidden to hakemus responses

- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/hakemus/HakemusControllerITest.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/hakemus/HakemusServiceITest.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/hakemus/HakemusController.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/hakemus/HakemusService.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/factory/HakemusUpdateRequestFactory.kt
Don't update registry key when it's hidden.
Also, refactor hakemus tests to use `HakemusBuilder.save()` instead of `.saveEntity()` and a separate load.
1. Create and modify a kaivuilmoitus so there's a person as the customer (hakija). The customer needs to be created with Swagger UI, since the frontend doesn't allow person customers to have registry IDs.
2. Make an update with Swagger UI. Set `registryKeyHidden` to true and `registryKey` to null for the customer.
3. Check that the registry key didn't change.
> HAI-2625 Don't update registry key when it's hidden

- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/gdpr/GdprServiceITest.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/gdpr/GdprService.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/factory/HankeKayttajaFactory.kt
When receiving a valid GDPR request to delete a user, clear the `kutsujaId` column of any users the deleted user so the foreign key reference doesn't stop the deletion.
Do this separately for the two cases:
- There are only unidentified users in a hanke besides the deleted user, so the whole hanke is deleted.
- There are identified and/or unidentified users in the hanke, so only the requested user is removed.
When a user requests their information should be deleted from Haitaton, being an inviter to another user is not a valid reason to stop the information from getting deleted.
From the bug report:
1. Uudella käyttäjällä luo hanke
2. Kutsu sinne muita käyttäjiä, älä käy hyväksymässä kutsuja
3. Pyydä Profiilin UI:sta (tai paikallisesti profiile-gdpr-api-testerillä) käyttäjän tietojen …
> HAI-2684 Clear inviter when removing a user for a GDPR request

- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/allu/AlluClientITests.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/hakemus/HakemusControllerITest.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/hakemus/HakemusServiceITest.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/allu/AlluClient.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/hakemus/HakemusController.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/hakemus/HakemusService.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/valmistumisilmoitus/ValmistumisilmoitusType.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/hakemus/HakemusServiceTest.kt
Add an API for reporting the date the work on an excavation is finished. The date is passed on to Allu. The report event is also stored in the local database.
Since the functionalities of reporting the work being in operational condition and reporting work finished are so similar, the new API uses a lot of the same implementation, refactored to take the type of completion (operational condition or work finished) as a parameter.
> HAI-2558 Add API for reporting work finished

- services/hanke-service/Dockerfile-local
- services/hanke-service/Dockerfile-platta
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/hakemus/HakemusControllerITest.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/hakemus/HakemusServiceITest.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/allu/AlluClient.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/hakemus/HakemusService.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/pdf/Formatters.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/pdf/JohtoselvityshakemusPdfEncoder.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/pdf/KaivuilmoitusPdfEncoder.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/factory/HakemusFactory.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/pdf/JohtoselvityshakemusPdfEncoderTest.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/pdf/KaivuilmoitusPdfEncoderTest.kt
When the orderer asks for a paper of the decision to be sent to an address, send that address to Allu. The address is added to the form data PDF that's sent to Allu after every application.
To make the information easy to notice, add a system comment saying that a paper copy has been requested and that the address can be found in the PDF.
Also,
- Change the customer headers in johtoselvityshakemus PDF to singular, since there can be only one customer for each role.
- Fix the `as` keyword in the Dockerfiles. It should be capitalized.
Create and send an application. Check Allu for the new comment and addition to the form-data PDF.
> HAI-2792 Send paper decision receiver to Allu

- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/hakemus/KaivuilmoitusValidation.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/hakemus/KaivuilmoitusSendValidationTest.kt
Implement new validation rules for registry keys when sending a kaivuilmoitus. I.e., a registry key is required for all customers (työstä vastaava) and customers invoicing. For companies and associations, it needs to be a y-tunnus, for persons, a henkilötunnus, and for others, any non-blank string.
1. Add a person as the customer and the invoicing customer in an excavation notification.
2. Send the application to Allu.
3. It should go as long as the henkilötunnus are valid.
> HAI-2812 Fix registry key validation at send

- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/hakemus/HakemusServiceITest.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/hakemus/Hakemus.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/hakemus/HakemusEntity.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/hakemus/HakemusService.kt
When a kaivuilmoitus has a person customer, henkilotunnus is mandatory for them. When an accompanying johtoselvityshakemus is created, the henkilotunnus has been copied to the created application. This causes problems when sending the application to Allu, because johtoselvityshakemus doesn't support registry keys for person customers.
Solve this dilemma by removing the registry keys from any person customers.
Johtoselvityshakemus isn't invoiced and doesn't have invoicing information, so we don't have to care about the registry key there.
1. Create a kaivuilmoitus with the apply for cable report set on.
2. For the customer (työstä vastaava) select a person and give them a henkilötunnus.
3. Send the application to Allu.
4. The send should succeed.
5. The created johtoselvityshakemus doesn't …
> HAI-2812 Remove henkilotunnus from accompanying johtoselvitys

- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/allu/AlluClientITests.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/hakemus/HakemusServiceITest.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/taydennys/TaydennysServiceITest.kt
- services/hanke-service/src/integrationTest/resources/clear-db.sql
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/allu/AlluApplicationData.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/allu/AlluClient.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/hakemus/HakemusService.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/taydennys/TaydennysService.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/taydennys/TaydennyspyyntoEntity.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/taydennys/TaydennyspyyntoRepository.kt
- services/hanke-service/src/main/resources/db/changelog/changesets/083-create-tables-for-taydennyspyynto.sql
- services/hanke-service/src/main/resources/db/changelog/db.changelog-master.yaml
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/factory/AlluFactory.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/hakemus/HakemusServiceTest.kt
When the application status changes to WAITING_INFORMATION, get the information request from Allu and save it to Haitaton.
Create tables for storing the information requests. Change `getInformationRequest` to return a single request instead of a list. Add tests for it.
Also, refactor `AlluClient.respondToInformationRequest` to handle both cable reports and excavation notifications. This isn't used yet, but I needed it while experimenting.
1. Send a hakemus to Allu.
2. Create an information request for the application in Allu.
3. After a minute, the database should have the information request info in the `taydennyspyynto` and `taydennyspyynnon_kentta` tables.
> HAI-2703 Save a new information request to Haitaton

- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/HankeServiceITests.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/HankeService.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/HankeYhteystietoEntity.kt
- services/hanke-service/src/main/resources/db/changelog/changesets/084-remove-datalock-from-hankeyhteystieto.sql
- services/hanke-service/src/main/resources/db/changelog/db.changelog-master.yaml
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/factory/HankeYhteystietoFactory.kt
There's an old system for disabling edits to hankeyhteystieto. There's a `datalocked` boolean flag in the hankeyhteystieto database table. When it's set to true (by someone manually editing the database), updates to the hanke are refused if they try to change that yhteystieto.
It seems like this system has been born out of a misunderstanding of what data processing restrictions mean in GDPR. It's been interpreted that it means that personal information cannot be edited. In reality, it's a broader concept. If someone asks us to restrict the processing of their personal data, we can't even store it without a valid reason. The GDPR API and the Profiili UI handle this, if someone wants to remove their information, we remove it unless we have a reason why we can't do so.
Since the system is …
> HAI Remove archaic hankeyhteystieto locking system

- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/logging/ChangeLoggingService.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/logging/HakemusLoggingService.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/logging/HankeKayttajaLoggingService.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/logging/HankeLoggingService.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/logging/PermissionLoggingService.kt
Create an abstract class for the change logging services. They have very similar methods with just a couple of changed parameters, so implementing them only once makes sense. Some have extra methods, so they are left in place. HankeLoggingService has a differing implementation for logging deletes, so it overrides the default.
> HAI-2748 Refactor logging services

- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/hakemus/HakemusControllerITest.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/hakemus/HakemusServiceITest.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/taydennys/TaydennysServiceITest.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/hakemus/HakemusController.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/hakemus/HakemusService.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/hakemus/HakemusWithExtras.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/factory/HakemusFactory.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/factory/TaydennysFactory.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/factory/TaydennyspyyntoFactory.kt
If a hakemus has a täydennys draft, return it with the hakemus data when querying for a single hakemus.
Add tests for `TaydennysService.findTaydennys()`, which was previously only needed in tests.
1. Create a täydennys like in #848 
2. Check the return value of the single hakemus API, easiest with browser developer tools. It should have `taydennys` object with the created täydennys.
> HAI-2770 Add täydennys to hakemus response

- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/HankeControllerITests.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/IntegrationTestConfiguration.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/gdpr/GdprControllerITests.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/hakemus/HakemusControllerITest.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/paatos/PaatosControllerITest.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/permissions/HankeKayttajaControllerITest.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/profiili/ProfiiliControllerITest.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/taydennys/TaydennysControllerITest.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/HankeController.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/configuration/AspectConfig.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/gdpr/GdprController.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/hakemus/HakemusController.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/hakemus/HakemusService.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/logging/DisclosureLogService.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/logging/DisclosureLoggingAspect.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/paatos/PaatosController.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/permissions/HankeKayttajaController.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/profiili/ProfiiliController.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/taydennys/TaydennysController.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/HankeControllerTest.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/hakemus/HakemusServiceTest.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/logging/DisclosureLogServiceTest.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/logging/DisclosureLoggingAspectTest.kt
Use an `@Aspect` to handle disclosure logging instead of calling it explicitly from controller methods.
I'm worried we haven't always remembered to save the disclosure logs when writing new APIs. It's easy to forget since we need to add an explicit call to `disclosureService` to the controller method. There's also a lot of deduction involved, e.g. we don't run the logging for the return value of create hakemus endpoint, because the endpoint doesn't accept any personal information, so the response can't have any either. But if this assumption changes in the future, it's easy to miss the need to add the logging.
This PR adds an aspect to returning from controller methods to make it implicit. After returning, the return value is checked, and if it's a type that can contain personal …
> HAI-2770 Refactor disclosure logging using an aspect

- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/hakemus/HakemusControllerITest.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/hakemus/HakemusController.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/hakemus/HankkeenHakemuksetResponse.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/hakemus/HankkeenHakemuksetResponseDeserializer.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/hakemus/HankkeenHakemusResponseDeserializer.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/test/JacksonTestExtension.kt
Add query param 'areas=true/false' for retrieving application areas for all project applications.
With Swagger UI call GET `/hankkeet/{hankeTunnus}/hakemukset` with and without new query parameter `areas`
> HAI-2820 Add query param for retrieving application areas

- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/hakemus/HakemusService.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/hakemus/HakemusUpdateRequest.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/hakemus/Hakemusyhteystieto.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/factory/HakemusyhteyshenkiloFactory.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/factory/HakemusyhteystietoFactory.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/hakemus/HakemusUpdateRequestTest.kt
Compare the hakemus update to a ` HakemusData` instead of an `ApplicationEntity` when checking if the update has any changes.
This allows the same method to be used to check if a täydennys has any changes over the original hakemus or the previously saved täydennys.
Should work like before.
> HAI-2749 Use data instead of entity for hakemus update change check

- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/hakemus/HakemusHistoryServiceITest.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/hakemus/HakemusHistoryService.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/taydennys/TaydennysService.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/hakemus/HakemusHistoryServiceTest.kt
When the hakemus moves to a status of handling, check if it has a täydennyspyyntö. If it does, delete it. This will also delete any täydennys the user might have started drafting.
If the hakemus moves to a status of handling from an unexpected status and the hakemus has a täydennyspyyntö, something has gone wrong so log an error. This won't stop the deletion of the hakemus or updating the status.
1. Make a täydennyspyyntö for a hakemus in Allu.
2. Wait until you see it in Haitaton.
3. Cancel the täydennyspyyntö in Allu.
4. It disappears in Haitaton.
> HAI-2699 Remove täydennyspyyntö when cancelled in Allu

- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/hakemus/HakemusControllerITest.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/hakemus/HakemusServiceITest.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/hakemus/UpdateHakemusITest.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/ControllerExceptionHandler.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/HankeError.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/gdpr/GdprController.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/hakemus/HakemusController.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/hakemus/HakemusService.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/hakemus/HakemusUpdateRequest.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/HankeErrorResultMatcher.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/HankeErrorTest.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/factory/HakemusFactory.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/factory/HakemusUpdateRequestFactory.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/hakemus/HakemusServiceTest.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/hakemus/KaivuilmoitusSendValidationTest.kt
Make several methods in HankeService public and change their parameters from hakemus-specific objects to more generic data, but only the data they need. E.g., take `HakemusEntityData` instead of a `HakemusEntity`. Or use the generic interface `YhteystietoEntity<H>` to handle customer updates in a compatible way.
These changes allow us to reuse the same methods for validating and executing updates for täydennykset and hopefully for muutosilmoitukset.
Simplify exceptions in hakemus update. Don't worry about passing a hakemusIdentfier through the validating functions. Info about the hakemus we're updating is logged as an info-level log, so it doesn't need to be logged every time there's an error. When examining a problem, the reader can look at the previous lines to find the identifying info …
> HAI-2749 Refactor hakemus service for reusability

- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/IntegrationTestConfiguration.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/taydennys/TaydennysControllerITest.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/taydennys/TaydennysServiceITest.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/taydennys/UpdateTaydennysITest.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/taydennys/TaydennysAuthorizer.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/taydennys/TaydennysController.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/taydennys/TaydennysEntity.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/taydennys/TaydennysIdentifier.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/taydennys/TaydennysService.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/factory/TaydennysFactory.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/factory/TaydennyspyyntoFactory.kt
Add API for updating a täydennys. The API has most of the same checks and functionalities as the hakemus update. I tried to reuse as much of the code in HakemusService as I could. However, some methods that alter the database entities have to access a specific entity, so they can't be shared easily.
One check removed from the täydennys update is checking if the hakemus has been sent to Allu. It always has. We don't check the hakemus status at all, since the täydennys shouldn't exist unless the hakemus is in a compatible state. Even if it's not due to a bug, there's no harm in updating the täydennys. When sending the täydennys and merging the data back to the hakemus we need to be more careful with the status.
Updating the name of a generated hanke will be done when the täydennys is sent …
> HAI-2749 Add API for updating täydennys

- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/hakemus/HakemusControllerITest.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/hakemus/HakemusServiceITest.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/taydennys/UpdateTaydennysITest.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/HankeError.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/hakemus/Hakemus.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/hakemus/HakemusService.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/hakemus/HakemusWithExtras.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/logging/DisclosureLoggingAspect.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/taydennys/Taydennys.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/HankeErrorResultMatcher.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/HankeErrorTest.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/factory/HakemusFactory.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/factory/TaydennysFactory.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/hakemus/HakemusDataTest.kt
If there are changes in the täydennys when compared to the original hakemus, return the changed fields. The changes are only checked at the top level so any change in e.g. an yhteystieto or in any of it's yhteyshenkilot will tag the yhteystieto as having changed.
1. Create a täydennys and make changes to it.
2. Check that the response for the GET /hakemukset/:id endpoint contains the changed fields.
> HAI-2759 Add changes in täydennys to hakemus response

- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/hakemus/HakemusServiceITest.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/taydennys/Taydennys.kt
When adding the changes from the application to the täydennys, the application data is accidentally copied over the täydennys data. Fix this by using a different name for the application data parameter.
Try to edit a täydennys. It will fail without this fix.
> HAI-2759 Fix täydennys data

- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/HankeControllerITests.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/UpdateHankeITests.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/hakemus/UpdateHakemusITest.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/taydennys/UpdateTaydennysITest.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/tormaystarkastelu/TormaystarkasteluControllerITest.kt
- services/hanke-service/src/integrationTest/resources/fi/hel/haitaton/hanke/logging/expectedHankeWithPolygon.json.mustache
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/pdf/Translations.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/tormaystarkastelu/TormaystarkasteluLuokittelu.kt
- services/hanke-service/src/main/resources/db/changelog/changesets/086-change-car-lane-nuisance-enum.sql
- services/hanke-service/src/main/resources/db/changelog/db.changelog-master.yaml
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/domain/HankeTest.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/factory/ApplicationFactory.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/factory/HankealueFactory.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/tormaystarkastelu/TormaystarkasteluLaskentaServiceTest.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/tormaystarkastelu/TormaystarkasteluLaskentaServiceWithGeometryTest.kt
Adjust enum values for kaistahaitta and kaistapituushaitta. Migrate old values into new ones in database. Does not recalculate the whole tormaystarkastelu in database with new values. Calculation happens when hanke or hakemus is updated.
1. Use branch `HAI-2816/update-car-lane-nuisance-indices` of UI (see https://github.com/City-of-Helsinki/haitaton-ui/pull/963)
2. Check the "Alueet" form page of both hanke and kaivuilmoitus - there should be new values in the dropdowns for kaistahaitta and kaistapituushaitta
3. Saving new values work as well as loading them
4. Törmäystarkastelu calculation works and new 0 values for both types have gray color
> HAI-2815 Adjust enum values for kaistahaitta and kaistapituushaitta.

- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/allu/AlluClientITests.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/hakemus/HakemusHistoryServiceITest.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/taydennys/TaydennysControllerITest.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/taydennys/TaydennysServiceITest.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/taydennys/UpdateTaydennysITest.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/HankeError.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/allu/AlluApplicationData.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/allu/AlluClient.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/allu/InformationRequest.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/hakemus/Hakemus.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/hakemus/HakemusService.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/logging/AuditLogEntry.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/logging/DisclosureLogService.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/logging/TaydennyspyyntoLoggingService.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/taydennys/TaydennysAuthorizer.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/taydennys/TaydennysController.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/taydennys/TaydennysService.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/taydennys/Taydennyspyynto.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/factory/HakemusyhteystietoFactory.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/factory/TaydennysFactory.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/hakemus/HakemusDataTest.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/test/Asserts.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/test/AuditLogEntryEntityAsserts.kt
Add an API endpoint for sending the täydennys to Allu. The täydennys is validated like a hakemus before it's sent to make sure it has all mandatory fields. It also needs at least one change compared to the hakemus and the status of the hakemus needs to be WAITING_INFORMATION.
The täydennys and täydennyspyyntö will be removed after sending.
The data will be merged with the hakemus in the next PR.
1. Create a hakemus with a täydennys.
2. Use the Swagger UI (http://localhost:3001/api/swagger-ui/index.html#/taydennys-controller/send) to send it.
> HAI-2761 API for sending täydennys

- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/taydennys/TaydennysServiceITest.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/taydennys/TaydennysService.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/factory/HakemusyhteystietoFactory.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/factory/TaydennysFactory.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/taydennys/TaydennysServiceTest.kt
Copy the data from täydennys to hakemus after sending the täydennys to Allu as a response to the original täydennyspyyntö.
For customers and contacts, use the existing entities in the hakemus whenever possible.
1. Create a täydennys and update some values. Change some contacts around.
2. Send it to Allu with Swagger UI (http://localhost:3001/api/swagger-ui/index.html#/taydennys-controller/send)
3. Check that the hakemus was updated with the changed values. Pay attention that the contacts were handled correctly.
> HAI-2761 Merge täydennys data to hakemus after sending

- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/taydennys/TaydennysServiceITest.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/hakemus/HakemusService.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/logging/DisclosureLogService.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/taydennys/TaydennysService.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/hakemus/HakemusServiceTest.kt
When sending the täydennys to Allu, create a PDF of the form data. The PDF should be identical to the one generated for a hakemus, except with a different filename and description.
Also, remove the `withDisclosureLogging` implementation from HakemusService. It's identical to the one in DisclosureLogService.
Create and send a täydennys to Allu. Check Allu for the PDF attachment.
> HAI-2776 Send form data PDF to Allu

- services/hanke-service/src/main/resources/db/changelog/changesets/086-change-car-lane-nuisance-enum.sql
Correctly updates applications.applicationData.areas without accidently deleting applicationData or applicationData.areas or other applicationData fields
In order to verify that the migration works correctly with "production data" (data before the buggy 086 migration script was run) do the following:
1. Checkout version before the buggy migration script: `git checkout 6a06e84d025ad7dc9e6fe5fac46e52134b81a7ed`
2. Manually run `delete from databasechangelog where id='086-change-car-lane-nuisance-enum';` into database
3. Manually revert old values of the enums in database:
```
UPDATE hankealue
SET kaistahaitta =
CASE
WHEN kaistahaitta = 'YKSI_KAISTA_VAHENEE' THEN 'VAHENTAA_KAISTAN_YHDELLA_AJOSUUNNALLA'
WHEN kaistahaitta = 'YKSI_KAISTA_VAHENEE_KAHDELLA_AJOSUUNNALLA' THEN …
```
> HAI-2871 Correctly updates applications.applicationData.areas

- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/HankeServiceITests.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/IntegrationTestConfiguration.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/hakemus/HakemusServiceITest.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/permissions/HankeKayttajaServiceITest.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/profiili/ProfiiliClientITest.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/profiili/ProfiiliControllerITest.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/Utils.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/permissions/HankeKayttajaService.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/profiili/ProfiiliClient.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/profiili/ProfiiliController.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/profiili/ProfiiliService.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/factory/HankeBuilder.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/profiili/ProfiiliServiceTest.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/test/AuthenticationMocks.kt
Modify the verified name API to handle users who are logged in through Helsinki AD. They don't have a full profile in Helsinki Profiili, so can't call the Profiili API to get a verified name for them. The name we get in the token is reliable, however. It's read from AD, so it's the official the person is known as an employee.
ProfiiliService was created between the controller and the ProfiiliClient to decide how we should get the name of that particular user. We can see from the AMR (Authentication method reference) claim whether the user was authenticated through Suomi.fi or Helsinki AD. The claim is technically an array, but in Profiili there's always a single value. If for some reason the user has both, we default to Suomi.fi method.
Getting a token from the SecurityContext was moved …
> HAI-2888 Read verified name form the token for AD users

- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/allu/AlluClientITests.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/hakemus/HakemusHistoryServiceITest.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/taydennys/TaydennysServiceITest.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/hakemus/HakemusHistoryService.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/taydennys/TaydennysService.kt
- services/hanke-service/src/main/resources/email/template/taydennyspyynto.text.mustache
Currently, if the handler in Allu creates a täydennyspyyntö and cancels it before Haitaton can read it during the next history update, we don't save the täydennyspyyntö, but we still send an email that a täydennyspyyntö was created.
Fix this by only sending the email when the täydennyspyyntö has been found and saved.
1. Create a johtoselvityshakemus and send it to Allu.
2. In Allu, start to handle the application.
3. Wait for Haitaton to update the application statuses in the background.
4. Create a täydennyspyyntö in Allu and then immediately cancel it.
5. Check [smtp4dev](http://localhost:3003/) that no email was sent about the täydennyspyyntö.
> HAI-2794 Don't send an email if täydennyspyyntö not found in Allu

- scripts/nginx/nginx.conf
- services/hanke-service/src/main/resources/application.yml
The Helsinki staff JWTs are fairly long because they belong to a bunch of AD groups. The default allowed header size is 8kB, but the example login token I received was almost 12kB on its own.
From
https://docs.spring.io/spring-boot/appendix/application-properties/index.html#application-properties.server.server.max-http-request-header-size:
> Tomcat applies the limit to the combined size of the request line and
all of the header names and values in the request.
So I'm setting the max value to 64kB, so all GET parameters and other headers fit inside the limit.
Also, increase the local nginx header limit.
This can be tested using a query with a completely random 10kB bearer token.
```
curl -i 'http://localhost:3001/api/profiili/verified-name' \
-H 'Accept: application/json, text/plain, */*' …
```
> HAI-1009 Increase header size to accommodate AD tokens

- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/testdata/TestDataServiceITest.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/testdata/TestDataService.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/factory/HakemusBuilder.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/factory/TaydennysAttachmentBuilder.kt
When unlinking hakemukset from Allu, they return to the draft state. It doesn't make any sense to have täydennyspyyntö or päätös for a hakemus that's a draft. So we can delete the related objects.
For täydennyspyyntö, it's also important because Allu reuses their ID after a reset so they might cause conflicts.
Also, delete the täydennys attachments and päätökset from Blob Storage.
1. With a local database after a full day of testing, write down some of the attachments the täydennykset and decisions the current applications have.
2. Call the [unlinking tool](http://localhost:3001/api/swagger-ui/index.html#/test-data-controller/unlinkApplicationsFromAllu).
3. Check that the täydennykset, täydennyspyynnöt and päätökset are all gone.
4. Check with Azure Storage Explorer that the files you …
> HAI-1302 Delete täydennyspyyntö and päätös when unlinking applications

- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/taydennys/TaydennysControllerITest.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/taydennys/TaydennysServiceITest.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/attachment/common/AttachmentEntity.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/attachment/taydennys/TaydennysAttachmentMetadataService.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/attachment/taydennys/TaydennysAttachmentService.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/taydennys/TaydennysController.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/taydennys/TaydennysService.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/taydennys/TaydennysyhteyshenkiloRepository.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/taydennys/TaydennysyhteystietoRepository.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/attachment/common/MockFileClient.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/factory/TaydennysBuilder.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/factory/TaydennysFactory.kt
API for deleting täydennys incl. its attachments and contacts.
1. Create täydennys (with some new contacts, attachments cannot yet be added)
2. Delete täydennys: http://localhost:3001/api/swagger-ui/index.html#/taydennys-controller/delete
3. Check database that there is no `taydennys` row or `taydennysyhteystieto` or `taydennysyhteyshenkilo` for the deleted täydennys any more
4. In UI the application is reverted back to where there is "Täydennä" button for it
> HAI-780 Delete taydennys API

- email/taydennyspyynto-peruttu.mjml
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/allu/AlluClientITests.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/hakemus/HakemusHistoryServiceITest.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/email/EmailEvent.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/email/EmailSenderService.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/taydennys/TaydennysService.kt
- services/hanke-service/src/main/resources/email/template/taydennyspyynto-peruttu.html.mustache
- services/hanke-service/src/main/resources/email/template/taydennyspyynto-peruttu.subject.mustache
- services/hanke-service/src/main/resources/email/template/taydennyspyynto-peruttu.text.mustache
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/factory/ApplicationHistoryFactory.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/hakemus/AlluUpdateServiceTest.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/hakemus/HakemusHistoryServiceTest.kt
Send emails when a täydennyspyyntö is cancelled. The emails are sent to the hakemus contacts with edit permissions for the hakemus.
Also, refactor the factory methods for ApplicationHistory for easier use.
1. Create a täydennyspyyntö in Allu for a hakemus.
2. Wait a minute for Haitaton to get the status update.
3. Cancel the täydennyspyyntö in Allu.
4. Check [Smtp4dev](http://localhost:3003/) for the email.
> HAI-2794 Send email when a täydennyspyyntö is canceled

- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/attachment/taydennys/TaydennysAttachmentControllerITest.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/attachment/taydennys/TaydennysAttachmentServiceITest.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/taydennys/TaydennysAuthorizerITest.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/attachment/application/ApplicationAttachmentContentService.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/attachment/taydennys/TaydennysAttachmentController.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/attachment/taydennys/TaydennysAttachmentMetadataService.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/attachment/taydennys/TaydennysAttachmentService.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/taydennys/TaydennysAuthorizer.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/factory/TaydennysAttachmentFactory.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/factory/TaydennysFactory.kt
API for getting täydennys attachments.
1. Add some attachments for a täydennys: http://localhost:3001/api/swagger-ui/index.html#/taydennys-attachment-controller/postAttachment
2. Get attachment by calling the API: http://localhost:3001/api/swagger-ui/index.html#/taydennys-attachment-controller/getApplicationAttachmentContent
> HAI-751 Get täydennys attachments API

- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/taydennys/TaydennysServiceITest.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/logging/AuditLogService.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/logging/ChangeLoggingService.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/taydennys/TaydennysService.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/taydennys/Taydennyspyynto.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/taydennys/TaydennyspyyntoEntity.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/factory/TaydennyspyyntoFactory.kt
When a täydennyspyyntö is cancelled in Allu, remove any täydennys attachment contents from Blob storage.
Also, add missing audit logging for the removal of the täydennys and täydennyspyyntö when they are deleted after the täydennyspyyntö is cancelled in Allu.  Allu is marked as the actor. Even though technically the data is deleted by Haitaton itself, Allu initiates the process by cancelling the täydennyspyyntö.
Add hakemus ID to the täydennyspyyntö domain class so that it's logged as well.
1. Create a täydennys and add attachments to it.
2. Cancel the täydennyspyyntö in Allu.
3. Check that Haitaton removed the attachments with Azure Storage Explorer.
4. Check that the audit log table in the database has entries for the deletion.
> HAI-1331 Remove attachments when täydennyspyyntö is canceled

- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/attachment/taydennys/TaydennysAttachmentControllerITest.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/attachment/taydennys/TaydennysAttachmentServiceITest.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/attachment/taydennys/TaydennysAttachmentController.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/attachment/taydennys/TaydennysAttachmentMetadataService.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/attachment/taydennys/TaydennysAttachmentService.kt
API for deleting täydennys attachments.
1. Add some attachment(s) to a täydennys: http://localhost:3001/api/swagger-ui/index.html#/taydennys-attachment-controller/postAttachment
2. Delete attachment(s) from täydennys: http://localhost:3001/api/swagger-ui/index.html#/taydennys-attachment-controller/deleteAttachment
3. Check blob storage and database that the attachment content and metadata is deleted
> HAI-752 API for deleting täydennys attachments

- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/attachment/taydennys/TaydennysAttachmentServiceITest.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/hakemus/HakemusServiceITest.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/taydennys/TaydennysAuthorizerITest.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/taydennys/TaydennysServiceITest.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/taydennys/UpdateTaydennysITest.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/testdata/TestDataServiceITest.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/factory/HakemusBuilder.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/factory/TaydennysBuilder.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/factory/TaydennysFactory.kt
There are now several methods of creating a täydennys for test purposes. There's some overlap between them, so using fewer methods is better.
Replace the TaydennysFactory save methods with the builder pattern since it's the most versatile.
> HAI-3326 Use builder pattern for saving test täydennys

- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/hakemus/HakemusControllerITest.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/hakemus/HakemusServiceITest.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/hakemus/HakemusService.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/hakemus/HakemusWithExtras.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/taydennys/Taydennys.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/factory/HakemusFactory.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/factory/TaydennysFactory.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/hakemus/HakemusServiceTest.kt
When getting a single hakemus, add liitteet to the taydennys object of the hakemus. Return the information for any existing attachments.
1. Create a täydennys for a johtoselvityshakemus.
2. The hakemus API should return an empty list for `liitteet`.
3. Add some attachments to the täydennys.
4. Check that the API returns the metadata of the added attachments in the `liitteet` field.
> HAI-3326 Add täydennys liitteet to hakemus API

- email/taydennyspyynto.mjml
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/email/EmailSenderServiceITest.kt
- services/hanke-service/src/main/resources/email/template/taydennyspyynto.html.mustache
Use the hakemus ID in the hakemus links in the täydennyspyyntö notification email. The Swedish and English links used the application identifier instead, so they didn't work.
You can create a täydennyspyyntö and check the email, but the fix is pretty obvious.
> HAI-3329 Fix täydennyspyyntö email links

- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/hakemus/Hakemusalue.kt
Give the haittojenhallintasuunnitelma a default value of an empty map, so that missing values in JSON are deserialized to the empty map.
Also, add the `@JsonSetter(nulls = Nulls.AS_EMPTY)` annotation, so that explicit nulls are also deserialized to an empty map.
Open an old kaivuilmoitus.
> HAI-876 Fix haittojenhallintasuunnitelma for existing kaivuilmoitus

- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/HankeControllerITests.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/HankeServiceITests.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/UpdateHankeITests.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/hakemus/HakemusControllerITest.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/hakemus/UpdateHakemusITest.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/tormaystarkastelu/TormaystarkasteluControllerITest.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/hakemus/Hakemusalue.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/hakemus/KaivuilmoitusValidation.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/HankeMapperTest.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/factory/ApplicationFactory.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/factory/HaittaFactory.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/factory/HankeFactory.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/factory/HankealueFactory.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/hakemus/HakemusUpdateRequestTest.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/hakemus/KaivuilmoitusSendValidationTest.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/validation/HankePublicValidatorTest.kt
Add validation that checks that the haittojenhallintasuunnitelma is filled in when sending the hakemus to Allu. It uses the same validation function as validation of the haittojenhallintasuunnitelma in a hanke.
Also, move haittojenhallintasuunnitelma and tormaystarkastelutulos stuff from `HankealueFactory` to a new `HaittaFactory`. These classes are also used in Kaivuilmoitus, so having the factories on "neutral ground" makes sense.
I didn't test this manually. It would require adding a haittojenhallintasuunnitelma through Swagger UI. The haittojenhallintasuunnitelma should have a missing value for one of the traffic methods where the area of the application has an index. And then sending the application to Allu.
> HAI-876 Add validation for haittojenhallintasuunnitelma in kaivuilmoitus

- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/configuration/Configuration.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/profiili/ProfiiliService.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/security/AdFilterProperties.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/security/JwtClaims.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/security/OAuth2ResourceServerSecurityConfiguration.kt
- services/hanke-service/src/main/resources/application.yml
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/profiili/ProfiiliServiceTest.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/security/AdGroupValidatorTest.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/test/AuthenticationMocks.kt
When a user has authenticated with the Helsinki AD, check that they are in at least one of the groups allowed to access Haitaton. This is done mainly to stop consultants and other non-employees who happen to have access to the Helsinki AD from using Haitaton with that AD login. They should use Suomi.fi instead.
The AD groups are configurable and there's an option to disable the group checks. The disabling is needed, because developers are consultants who don't have the correct AD groups. We can disable the group checks from e.g. the dev environment so we can still test the AD login process.
The constants describing JWT claims and their values were moved from under ProfiiliService to shared objects.
1. Login to Haitaton with Helsinki AD.
2. If your name shows up at the user icon in the top …
> HAI-1008 AD group checks for authentication

- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/hakemus/HakemusServiceITest.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/hakemus/HakemusService.kt
When sending kaivuilmoitus, set `cableReportDone=true` for kaivuilmoitus with accompanying johtoselvityshakemus.
1. Create and fill kaivuilmoitus with "Hae uusi johtoselvitys" selected
2. Send kaivuilmoitus
3. Check that in response (or in database) `cableReportDone` is `true`
> HAI-3327 Set cableReportDone=true for kaivuilmoitus with accompanying johtoselvityshakemus

- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/pdf/Fonts.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/pdf/HaittojenhallintasuunnitelmaPdfEncoder.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/pdf/MapGenerator.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/pdf/NuisanceColor.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/pdf/PdfHelpers.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/factory/HaittaFactory.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/factory/HankeFactory.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/pdf/HaittojenhallintasuunnitelmaPdfEncoderTest.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/pdf/HhsManualTest.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/pdf/MapGeneratorTest.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/pdf/NuisanceColorTest.kt
- services/hanke-service/src/test/resources/fi/hel/haitaton/hanke/pdf-test-data/many-hankealue.json
Add the actual haittojenhallintasuunnitelma from the application when creating a new haittojenhallintasuunnitelma PDF. Add a map for each transport mode, colored according to the haitta it causes.
Send a kaivuilmoitus to Allu and check the attachment in Allu. There's also a temporary test that creates example PDFs.
> HAI-3354 Add haittojenhallintasuunnitelma info to the PDF

- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/pdf/HaittojenhallintasuunnitelmaPdfEncoder.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/pdf/PdfHelpers.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/pdf/WmsConfiguration.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/pdf/HaittojenhallintasuunnitelmaPdfEncoderTest.kt
- services/hanke-service/src/test/resources/fi/hel/haitaton/hanke/pdf-test-data/hankealueet.json
Add haittojenhallintasuunnitelma from hankealue to the PDF
Send a kaivuilmoitus to Allu and check the attachment in Allu. There's also a temporary test that creates example PDFs.
> HAI-3355 Add haittojenhallintasuunnitelma from hankealue to the PDF

- services/hanke-service/Dockerfile-local
- services/hanke-service/Dockerfile-platta
Use the recommended Red Hat Universal Base Image 9 -based images from the Red Hat registry as base images for building the hanke-service images.
> HAI-3369 Use UBI9 baseimages

- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/Utils.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/hakemus/Hakemus.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/hakemus/Hakemusalue.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/hakemus/HakemusDataTest.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/hakemus/HakemusalueTest.kt
1. Use `checkChangeInYhteystieto` for `KaivuilmoitusData` contacts
2. New implementation of `checkChangesInAreas` - it will check changes inside areas, not just do `equals` comparison
3. Implementations of `Hakemusalue.listChanges`: `equals` check for other than `KaivuilmoitusAlue` and field-by-field comparison for `KaivuilmoitusAlue`
4. Implementation of `Tyoalue.listChanges`
5. Implementation of checking changes in haittojenhallintasuunnitelma
6. Tests for all
1. Create a kaivuilmoitus and a täydennyspyyntö for it
2. Create täydennys, do changes especially in work areas, haittojenhallintasuunnitelma and contacts
3. Check the returned `muutokset` value when the form is saved
other info that the …
> HAI-3321 Complete return values of kaivuilmoitus taydennys

- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/taydennys/TaydennysServiceITest.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/hakemus/HakemusService.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/taydennys/TaydennysService.kt
When cancelling a täydennys on a stand-alone johtoselvityshakemus (so the hanke is generated based on the application), reset the geometries of the hanke to match the original application. The hanke geometries are automatically changed if the user makes changes to the täydennys geometries, so they should be returned to the previous state if the täydennys is then cancelled.
Do this whether the täydennys is cancelled by the user or by Allu.
1. Create a täydennyspyyntö on a stand-alone johtoselvityshakemus with a generated hanke.
2. Edit the täydennys and add some new work areas.
3. The hanke should be updated with these areas.
4. Cancel the täydennys.
5. The hanke should be showing the original areas, and not the ones added in the täydennys.
> HAI-3365 Reset generated hankealueet when cancelling a täydennys

- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/taydennys/TaydennysServiceITest.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/hakemus/HakemusService.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/taydennys/TaydennysService.kt
When sending a täydennys to Allu, also send an updated haittojenhallintasuunnitelma when the application is a kaivuilmoitus. Always generate a new haittojenhallintasuunnitelma, since it also contains other information about the application besides the actual haittojenhallintasuunnitelma.
Send a täydennys to Allu, then check that the new haittojenhallintasuunnitelma is in Allu.
> HAI-3324 Send updated haittojenhallintasuunnitelma with täydennys

- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/UpdateHankeITests.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/HankeService.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/factory/GeometriaFactory.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/factory/HakemusBuilder.kt
When updating a hanke, check that all hakemusalue are still inside valid hankealue. For johtoselvityshakemus this means that every hakemusalue needs to be inside some hankealue. For kaivuilmoitus, each työalue is inside the hankealue it's created for.
This also solves HAI-917 and HAI-2091.
Create a hanke with several hankealue. Add a johtoselvityshakemus and a kaivuilmoitus to the hankealue. You should be able to expand the hankealue, but not delete or make them smaller.
> HAI-2089 Protect hakemusalue in hanke udpates

- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/geometria/GeometriatDaoITest.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/hakemus/HakemusServiceITest.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/geometria/GeometriatDao.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/hakemus/HakemusService.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/hakemus/HakemusServiceTest.kt
- services/hanke-service/src/test/resources/sql/monen-alueen-hanke.sql
Refactor `isInsideHankeAlue` to `matchingHankealueet`, so it returns a list of the hankealue IDs that cover the given geometry instead of a boolean whether any exist. This makes the function more versatile, it can be used to check other properties about the hankealueet in code.
> HAI-1243 Refactor `isInsideHankeAlue` to return the matching IDs

- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/UpdateHankeITests.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/HankeService.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/factory/HakemusFactory.kt
Decline hanke updates if the dates of hanke areas no longer cover all applications of the hanke.
Consider nulls as unknown values, so all edits are allowed.
1. Create a hanke.
2. Add an area to the hanke with dates.
3. Add a hakemus.
4. Use the hankealue dates and geometry for the hakemus.
5. Try to change the hanke area dates. You should be able to extend the dates, but not shrink them under the hakemus dates.
> HAI-1243 Add validation for hankealue dates against hakemukset

- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/geometria/GeometriatDao.kt
- Use the jdbcOperations dependency everywhere instead of sometimes passing it as a parameter.
- Move the methods that use jdbcOperations to the class from the companion object.
- Remove `with(jdbcOperations)` blocks, since jdbcOperations is always used just once.
- Move queries and row mappers to separate values, making the query calls simpler.
> HAI Refactor GeometriatDao

- email/kaivuilmoitus-paatos.mjml
- email/taydennyspyynto-peruttu.mjml
- email/taydennyspyynto.mjml
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/email/EmailSenderServiceITest.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/hakemus/HakemusHistoryServiceITest.kt
- services/hanke-service/src/main/resources/email/template/kaivuilmoitus-paatos.html.mustache
- services/hanke-service/src/main/resources/email/template/kaivuilmoitus-paatos.subject.mustache
- services/hanke-service/src/main/resources/email/template/kaivuilmoitus-paatos.text.mustache
- services/hanke-service/src/main/resources/email/template/taydennyspyynto-peruttu.html.mustache
- services/hanke-service/src/main/resources/email/template/taydennyspyynto-peruttu.subject.mustache
- services/hanke-service/src/main/resources/email/template/taydennyspyynto-peruttu.text.mustache
- services/hanke-service/src/main/resources/email/template/taydennyspyynto.html.mustache
- services/hanke-service/src/main/resources/email/template/taydennyspyynto.subject.mustache
- services/hanke-service/src/main/resources/email/template/taydennyspyynto.text.mustache
Added Swedish and English translations for kaivuilmoitus päätös, täydennyspyyntö and täydennyspyyntö cancellation emails.
1. Create a new or use an existing kaivuilmoitus, send it to Allu
2. In Allu, create a täydennyspyyntö for the kaivuilmoitus
3. After a while check that the email notification is correct with new translations
4. Cancel the täydennyspyyntö in Allu
5. After a while check that the email notification is correct with new translations
6. Create a decision for the kaivuilmoitus in Allu
7. After a while check that the email notification is correct with new translations
> HAI-3427 Add missing email translations for kaivuilmoitus

- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/profiili/ProfiiliService.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/security/OAuth2ResourceServerSecurityConfiguration.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/profiili/ProfiiliServiceTest.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/security/AdGroupValidatorTest.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/test/AuthenticationMocks.kt
Add a check to AD token validation that checks that the token has non-blank claims for given and family names. Without them, we don't know who the user is and Haitaton can't add them to a hanke.
Also, add a check to getting a user's validated name that checks that the given and family names are not blank. There was already a check that they are present. The check shouldn't come up now that we don't even allow access to AD users without name claims, but I added it as a defence-in-depth thing.
We don't have an account to test this with, so I trust the unit tests.
> HAI-3438 Refuse AD tokens without names

- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/configuration/MockAlluUpdateService.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/testdata/TestDataControllerDisabledITest.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/testdata/TestDataControllerEnabledITest.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/logging/DisclosureLoggingAspect.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/security/AccessRules.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/testdata/TestDataController.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/testdata/TestDataService.kt
Add an API that, when called, immediately retrieves the latest application history from Allu and updates the application statuses accordingly. The update is executed using the same code as the timed updates, ensuring that the last update time is refreshed and that the mutex safeguards against simultaneous updates.
Waiting for the next Allu history update can be frustrating when testing the Haitaton code. This functionality allows us to update and observe the effects in Haitaton instantly.
The endpoint is a GET, making it easy to call. You may use a shell alias that invokes it with cURL, a bookmark in your browser, or a custom shortcut in your IDE.
The endpoint can also be invoked from E2E tests, which often have to wait for a status update from Allu. In the johtoselvitys täydennys test …
> HAI Add test API for triggering Allu updates

- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/IntegrationTestConfiguration.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/muutosilmoitus/MuutosilmoitusAuthorizerITest.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/muutosilmoitus/MuutosilmoitusControllerITest.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/muutosilmoitus/MuutosilmoitusServiceITest.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/muutosilmoitus/UpdateMuutosilmoitusITest.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/HankeError.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/domain/HasYhteystietoEntities.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/hakemus/HakemusEntity.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/hakemus/HakemusService.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/muutosilmoitus/MuutosilmoitusAuthorizer.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/muutosilmoitus/MuutosilmoitusController.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/muutosilmoitus/MuutosilmoitusEntity.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/muutosilmoitus/MuutosilmoitusService.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/taydennys/TaydennysEntity.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/taydennys/TaydennysService.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/factory/HakemusUpdateRequestFactory.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/factory/MuutosilmoitusBuilder.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/factory/MuutosilmoitusFactory.kt
Add an API for updating a muutosilmoitus. The muutosilmoitus can't be sent yet. Handle both johtoselvityshakemus and kaivuilmoitus, even though currently a muutosilmoitus can be only created for a kaivuilmoitus.
Also add a missing test: a muutosilmoitus can be only created for a kaivuilmoitus.
After creating a muutosilmoitus, use [Swagger UI](http://localhost:3001/api/swagger-ui/index.html#/muutosilmoitus-controller/update_1) to modify it.
> HAI-3400 Add API for updating a muutosilmoitus

- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/hakemus/HakemusControllerITest.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/hakemus/HakemusServiceITest.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/Constants.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/Utils.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/hakemus/HakemusController.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/hakemus/HakemusRepository.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/hakemus/HakemusService.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/hakemus/HakemusWithExtras.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/hakemus/HankkeenHakemuksetResponse.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/factory/MuutosilmoitusFactory.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/hakemus/HakemusDataDeserializer.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/hakemus/HakemusDataResponseDeserializer.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/hakemus/HakemusResponseDeserializer.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/hakemus/HankkeenHakemusResponseDeserializer.kt
Add any muutosilmoitus under hakemus for the list of hankkeen hakemukset.
Also, simplify some test deserializers by using a new ObjectMapper instance that has a hard mapping for the required interface types.
With a kaivuilmoitus that has a muutosilmoitus, look at the response when opening the related hanke page.
> HAI-3402 Add muutosilmoitukset to hankkeen hakemukset

- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/testdata/TestDataServiceITest.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/testdata/TestDataService.kt
`testdata/unlink-applications` endpoint deletes all muutosilmoitus
1. Have a kaivuilmoitus with muutosilmoitus
2. Call http://localhost:3001/api/swagger-ui/index.html#/test-data-controller/unlinkApplicationsFromAllu
3. Check that there is no more muutosilmoitus in database
> HAI Unlinking applications deletes muutosilmoitukset

- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/hakemus/HankkeenHakemuksetResponse.kt
Renamed `HankkeenHakemusMuutosilmoitusResponse.hakemusdata` to `applicationData` to be uniform with `MuutosilmoitusResponse`.
> HAI Rename hakemusdata to applicationData

- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/muutosilmoitus/MuutosilmoitusControllerITest.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/muutosilmoitus/MuutosilmoitusServiceITest.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/taydennys/TaydennysControllerITest.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/taydennys/TaydennysServiceITest.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/Persistence.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/domain/Loggable.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/hakemus/Hakemus.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/hakemus/HakemusService.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/muutosilmoitus/MuutosilmoitusController.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/muutosilmoitus/MuutosilmoitusIdentifier.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/muutosilmoitus/MuutosilmoitusService.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/taydennys/TaydennysController.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/taydennys/TaydennysIdentifier.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/taydennys/TaydennysService.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/factory/MuutosilmoitusBuilder.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/factory/MuutosilmoitusFactory.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/muutosilmoitus/MuutosilmoituksenYhteystietoRepository.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/test/Asserts.kt
Don't delete the muutosilmoitus if it has been already sent to Allu.
Also change delete täydennys API to return 204 on success instead of 200.
Create a muutosilmoitus. Call the delete API from [Swagger UI](http://localhost:3001/api/swagger-ui/index.html#/muutosilmoitus-controller/delete_1).
> HAI-3406 Add API for deleting a muutosilmoitus

- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/taydennys/TaydennysServiceITest.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/allu/AlluClient.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/taydennys/TaydennysService.kt
Täydennys changed fields have included attachments only when it's the only change on the täydennys. (Except for when a kaivuilmoitus has changes in its haittojenhallintasuunnitelma, but that is a separate mechanism.)
This means that the handler in Allu might not notice that an attachment has been added, since it's not shown when processing the täydennys.
Fix this by including 'attachment' in the changed fields also when there are other fields.
Replication steps are listed on the ticket.
> HAI-3455 Add attachment to changed fields with other changes

- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/hakemus/HakemusHistoryServiceITest.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/muutosilmoitus/MuutosilmoitusServiceITest.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/muutosilmoitus/UpdateMuutosilmoitusITest.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/domain/HasYhteystietoEntities.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/hakemus/HakemusHistoryService.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/hakemus/YhteystietoEntity.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/muutosilmoitus/MuutosilmoitusService.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/taydennys/TaydennysService.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/factory/MuutosilmoitusBuilder.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/factory/MuutosilmoitusFactory.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/hakemus/HakemusHistoryServiceTest.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/muutosilmoitus/MuutosilmoitusServiceTest.kt
Merge the data from muutosilmoitus to hakemus when the hakemus gets a replacement decision. The muutosilmoitus is deleted afterwards.
Suppose - for some reason - the hakemus gets a replacement decision with a muutosilmoitus that hasn't been sent yet. In that case, the decision can't be a reaction to the muutosilmoitus, so do nothing with it.
Use the yhteystieto interfaces to implement a lot of the merging behaviour, since the behaviour is the same for both täydennys and muutosilmoitus.
1. Create a muutosilmoitus with some changes.
2. Send it to Allu.
3. In Allu, process the muutosilmoitus and create a replacement decision.
4. In Haitaton, check that the changes from the muutosilmoitus are visible on the hakemus and that it no longer has a muutosilmoitus.
5. Create a muutosilmoitus with …
> HAI-151 Merge muutosilmoitus to hakemus

- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/hakemus/HakemusHistoryServiceITest.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/hakemus/HakemusHistoryService.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/factory/HakemusBuilder.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/factory/MuutosilmoitusBuilder.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/factory/MuutosilmoitusFactory.kt
When a täydennyspyyntö is received from Allu, merge any muutosilmoitus to the hakemus if it has one. This loses the information that the täydennys is for a muutosilmoitus, except that the hakemus already has a decision. The täydennys can be filled and sent like normal.
1. Create a muutosilmoitus for a kaivuilmoitus.
2. Send it to Allu.
3. In Allu, start processing the muutosilmoitus and request a täydennyspyyntö.
4. In Haitaton, the hakemus should be in 'Odottaa täydennystä' state but the previous decision should be visible.
5. Fill in a täydennys and send it.
6. In Allu, process the täydennys and create a decision.
7. In Haitaton, the hakemus should have a new identifier and decision.
> HAI-712 Merge muutosilmoitus to hakemus on täydennyspyyntö

- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/attachment/hanke/HankeAttachmentControllerITests.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/attachment/hanke/HankeAttachmentMetadataServiceITests.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/attachment/hanke/HankeAttachmentServiceITest.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/attachment/taydennys/TaydennysAttachmentServiceITest.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/attachment/application/ApplicationAttachmentMetadataService.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/attachment/application/ApplicationAttachmentService.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/attachment/common/AttachmentEntity.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/attachment/common/AttachmentService.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/attachment/common/Domain.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/attachment/common/Exceptions.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/attachment/common/FileScanClient.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/attachment/hanke/HankeAttachmentContentService.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/attachment/hanke/HankeAttachmentController.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/attachment/hanke/HankeAttachmentMetadataService.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/attachment/hanke/HankeAttachmentService.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/attachment/taydennys/TaydennysAttachmentMetadataService.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/attachment/taydennys/TaydennysAttachmentService.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/factory/HankeAttachmentFactory.kt
Attachment creation has some logic to it that needs to happen in a specific way every way. I.e. the uploaded file needs to be deleted if saving the attachment info to the database fails for some reason. This wasn't done with hanke attachments.
Extract this logic to an interface. Wrap the service calls to abstract interface methods, so the interface doesn't have to know anything about which services are involved. Use the proper logic also for hanke attachments.
Make hanke attachment services return domain objects instead of DTOs. To make the conversion of domain to DTO possible, add hanketunnus to the domain object. The hankeId from the domain object can be removed since it's not used anywhere and the hanketunnus serves the same purpose.
Also, move the `scanAttachment` method to …
> HAI-3412 Share attachment creation between services

- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/IntegrationTestConfiguration.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/attachment/muutosilmoitus/MuutosilmoitusAttachmentControllerITest.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/attachment/muutosilmoitus/MuutosilmoitusAttachmentServiceITest.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/attachment/taydennys/TaydennysAttachmentControllerITest.kt
- services/hanke-service/src/integrationTest/resources/clear-db.sql
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/ControllerExceptionHandler.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/attachment/muutosilmoitus/MuutosilmoitusAttachmentController.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/attachment/muutosilmoitus/MuutosilmoitusAttachmentEntity.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/attachment/muutosilmoitus/MuutosilmoitusAttachmentMetadata.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/attachment/muutosilmoitus/MuutosilmoitusAttachmentMetadataDto.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/attachment/muutosilmoitus/MuutosilmoitusAttachmentMetadataService.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/attachment/muutosilmoitus/MuutosilmoitusAttachmentRepository.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/attachment/muutosilmoitus/MuutosilmoitusAttachmentService.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/logging/DisclosureLoggingAspect.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/muutosilmoitus/MuutosilmoitusController.kt
- services/hanke-service/src/main/resources/db/changelog/changesets/106-create-table-for-muutosilmoitus-attachment.sql
- services/hanke-service/src/main/resources/db/changelog/db.changelog-master.yaml
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/factory/MuutosilmoitusAttachmentFactory.kt
Add an API for adding attachments to muutosilmoitus. The attachments are uploaded to Blob Storage using the same prefix as the attachments for the hakemus. If any attachments are left orphaned by the muutosilmoitus, they will be deleted when the hakemus is deleted.
An attachment cannot be added if the muutosilmoitus has been sent to Allu.
1. Create a muutosilmoitus for a kaivuilmoitus.
2. Use [Swagger UI](http://localhost:3001/api/swagger-ui/index.html#/muutosilmoitus-attachment-controller/postAttachment_1) to add an attachment to it.
3. Check from DB (`muutosilmoituksen_liite` table) that the attachment was added and with Azure Storage Explorer that the attachment in the hakemusliitteet container.
4. Send the muutosilmoitus to Allu. (The attachment is not sent yet)
5. Try to add a new …
> HAI-3412 Add attachment API for muutosilmoitus

- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/attachment/muutosilmoitus/MuutosilmoitusAttachmentControllerITest.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/attachment/muutosilmoitus/MuutosilmoitusAttachmentServiceITest.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/muutosilmoitus/MuutosilmoitusAuthorizerITest.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/ControllerExceptionHandler.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/attachment/application/ApplicationAttachmentController.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/attachment/application/ApplicationAttachmentService.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/attachment/common/AttachmentService.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/attachment/hanke/HankeAttachmentService.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/attachment/muutosilmoitus/MuutosilmoitusAttachmentController.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/attachment/muutosilmoitus/MuutosilmoitusAttachmentMetadataService.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/attachment/muutosilmoitus/MuutosilmoitusAttachmentService.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/attachment/taydennys/TaydennysAttachmentController.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/attachment/taydennys/TaydennysAttachmentService.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/muutosilmoitus/MuutosilmoitusAuthorizer.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/factory/MuutosilmoitusAttachmentFactory.kt
Add an API for downloading muutosilmoitus attachments. The download is refused if the attachment is a power of attorney (valtakirja).
Add missing descriptions about the valtakirja case also to application and täydennys attachment API documentations.
Also, merge the `getContent` methods for all attachment services. They were all identical, except hanke was missing the valtakirja check.
With a muutosilmoitus that has an attachment:
1. Check the database `muutosilmoituksen_liite` table to see the attachment ID and muutosilmoitus ID.
2. Call the [Swagger UI](http://localhost:3001/api/swagger-ui/index.html#/muutosilmoitus-attachment-controller/getApplicationAttachmentContent_1) to download the attachment.
> HAI-3413 Download API for muutosilmoitus attachment

- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/attachment/muutosilmoitus/MuutosilmoitusAttachmentControllerITest.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/attachment/muutosilmoitus/MuutosilmoitusAttachmentServiceITest.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/attachment/application/ApplicationAttachmentService.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/attachment/common/AttachmentService.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/attachment/common/Domain.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/attachment/hanke/HankeAttachmentController.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/attachment/hanke/HankeAttachmentService.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/attachment/muutosilmoitus/MuutosilmoitusAttachmentController.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/attachment/muutosilmoitus/MuutosilmoitusAttachmentMetadataService.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/attachment/muutosilmoitus/MuutosilmoitusAttachmentService.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/attachment/taydennys/TaydennysAttachmentService.kt
Add an API for deleting attachments from muutosilmoitus.
Also, combine the delete methods of the attachment services, there's not much shared code, but the wrapper methods were mostly already there, so it didn't require much. Having the same amount of logging between different types of attachments is good, at least.
With an unsent muutosilmoitus that has an attachment:
1. Check the database muutosilmoituksen_liite table to see the attachment ID and muutosilmoitus ID.
2. Call the [Swagger UI](http://localhost:3001/api/swagger-ui/index.html#/muutosilmoitus-attachment-controller/removeAttachment).
3. The attachment should no longer be in the DB or Azure Storage Manager.
With a sent muutosilmoitus that has an attachment (add the attachment before sending it):
1. Check the database …
> HAI-3414 Delete attachment API for muutosilmoitus

- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/hakemus/HakemusControllerITest.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/hakemus/HakemusServiceITest.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/attachment/muutosilmoitus/MuutosilmoitusAttachmentMetadataService.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/attachment/muutosilmoitus/MuutosilmoitusAttachmentRepository.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/hakemus/HakemusService.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/muutosilmoitus/Muutosilmoitus.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/muutosilmoitus/MuutosilmoitusResponse.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/factory/MuutosilmoitusFactory.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/hakemus/HakemusServiceTest.kt
Add attachments for muutosilmoitus to hakemus response. 
With a muutosilmoitus that has attachments, see the response from the network tab when opening the hakemus page. There should be `liitteet` under `muutosilmoitus`.
> HAI-3415 Add attachments for muutosilmoitus to hakemus response

- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/muutosilmoitus/MuutosilmoitusServiceITest.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/attachment/muutosilmoitus/MuutosilmoitusAttachmentMetadataService.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/attachment/muutosilmoitus/MuutosilmoitusAttachmentRepository.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/attachment/muutosilmoitus/MuutosilmoitusAttachmentService.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/muutosilmoitus/MuutosilmoitusService.kt
Delete all attachments added to a muutosilmoitus if it is cancelled (deleted). Don't stop if deleting the file from Blob Storage fails, the file will be deleted when the hakemus is eventually deleted.
1. Add an attachment to a muutosilmoitus.
2. Cancel the muutosilmoitus.
3. The attachment should be removed from DB and Azure Storage Manager.
> HAI-3416 Delete attachments when muutosilmoitus is cancelled

- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/attachment/muutosilmoitus/MuutosilmoitusAttachmentMetadataServiceITest.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/muutosilmoitus/MuutosilmoitusServiceITest.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/attachment/muutosilmoitus/MuutosilmoitusAttachmentMetadataService.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/attachment/muutosilmoitus/MuutosilmoitusAttachmentService.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/muutosilmoitus/MuutosilmoitusService.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/factory/MuutosilmoitusAttachmentFactory.kt
Move attachments to hakemus when muutosilmoitus is merged.
1. Create a muutosilmoitus with some attachments.
2. Send it to Allu.
3. In Allu, create a decision or a täydennyspyyntö.
4. In Haitaton, the attachments should now be under the hakemus.
> HAI-3418 Move attachments to hakemus when muutosilmoitus is merged

- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/HankeControllerITests.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/HankeServiceITests.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/domain/PublicHankeControllerITests.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/HankeMapper.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/PublicHankeController.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/domain/Hanke.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/domain/PublicHanke.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/factory/HankeFactory.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/validation/HankePublicValidatorTest.kt
- Add all omistajat, but only add their names when they are businesses or organisations. A private person will have null in `organisaatioNimi`.
- Remove `osasto` from public customers, since it's always null for omistajat, the only customer added to public hanke.
- Use the common pattern for the PublicHanke conversion methods.
- Remove the unused audit fields from PublicGeometriat, leaving only the feature collection.
- Remove `tormaystarkasteluTulos` from PublicHanke.
- Add `tormaystarkasteluTulos` to PublicHankeAlue.
Also, remove `tormaystarkasteluTulos` from Hanke. The public hanke was the last using it in backend. It shouldn't be used anymore on frontend side.
Open the public hanke map and look at the response from the network tab of developer tools.
> HAI-3420 Update public hankkeet API

- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/muutosilmoitus/MuutosilmoitusServiceITest.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/taydennys/TaydennysServiceITest.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/attachment/application/ApplicationAttachmentMetadataService.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/attachment/common/AttachmentService.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/attachment/muutosilmoitus/MuutosilmoitusAttachmentMetadataService.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/attachment/muutosilmoitus/MuutosilmoitusAttachmentService.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/attachment/taydennys/TaydennysAttachmentMetadataService.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/hakemus/HakemusService.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/muutosilmoitus/HasUploadFormDataPdf.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/muutosilmoitus/MuutosilmoitusService.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/pdf/JohtoselvityshakemusPdfEncoder.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/pdf/KaivuilmoitusPdfEncoder.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/taydennys/TaydennysService.kt
When there are attachments added to the muutosilmoitus, send them to Allu. Add the `ATTACHMENT` field key to changed fields, if attachments are sent. Update the form data PDF to include attachments from the muutosilmoitus as well as the attachments from the hakemus.
1. With a muutosilmoitus that has attachments, send it to Allu. (The muutosilmoitus shouldn't have changes in haittojenhallinta, since that will add the ATTACHMENT field key to the changes regardless of actual attachments).
3. Check that the attachments are visible in Allu when processing the muutosilmoitus.
4. Check the uploaded form data PDF. It should mention all the attachments for the hakemus and the muutosilmoitus.
> HAI-3419 Send muutosilmoitus attachments to Allu

- services/hanke-service/build.gradle.kts
Also update logback-access, because old version wasn't compatible with the new Spring Boot version. The old workaround with excluding Tomcat dependencies is no longer needed.
> Upgrade Spring Boot to 3.3.10

- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/HankeCompletionServiceITest.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/hakemus/HakemusServiceITest.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/HankeCompletionScheduler.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/HankeCompletionService.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/Persistence.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/hakemus/Hakemus.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/hakemus/HakemusEntity.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/hakemus/HakemusService.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/logging/AuditLogService.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/logging/ChangeLoggingService.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/logging/DisclosureLogService.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/logging/HankeLoggingService.kt
- services/hanke-service/src/main/resources/application.yml
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/HankeCompletionSchedulerTest.kt
Once per day, delete all hanke that were completed 6 months ago. The hanke is not deleted if it has an active application for some unexpected reason.
All information related to the hanke is deleted, like users, applications and attachments.
Haitaton is not an archive, so we need to delete old hanke after they are no longer useful. Six months after completion was decided to be a enough time for users to download any decisions and other information that the hanke and its applications might still have.
1. Complete some hanke like in #1013.
2. Change their `completedAt` value in the database to be in the past.
3. Change the `deletionCron` value or add `@EventListener(ApplicationReadyEvent::class)` to `deleteCompletedHanke`.
4. Check that the hanke were deleted and the `audit_logs` table has …
> HAI-156 Delete hanke after being completed for 6 months

- .gitignore
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/HankeControllerITests.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/attachment/hanke/HankeAttachmentAuthorizerITest.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/hakemus/HakemusAuthorizerITest.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/muutosilmoitus/MuutosilmoitusAuthorizerITest.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/paatos/PaatosAuthorizerITest.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/permissions/HankeAuthorizerITest.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/permissions/HankeKayttajaAuthorizerITest.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/permissions/HankeKayttajaControllerITest.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/taydennys/TaydennysAuthorizerITest.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/ControllerExceptionHandler.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/HankeError.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/Persistence.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/permissions/Authorizer.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/permissions/HankeKayttajaAuthorizer.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/permissions/HankeKayttajaController.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/HankeAuthorizerTest.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/factory/HankeFactory.kt
- services/hanke-service/src/test/resources/application-test.yml
The authorizer will by default deny any API calls where:
1. The permission asked for is not VIEW
2. The hanke has COMPLETED status.
This should stop any edits being done to completed hanke.
The exception is resending the invitation to join a hanke. That can be sent even after the hanke has been completed. It would've been possible to implement this by also allowing the `RESEND_INVITATION` permission for completed hanke, but it felt safer to allow editing completed hanke explicitly in the controller.
Tests were added to all authorizer methods to check that calling them for completed hanke works correctly.
I added unit tests for HankeAuthorizers to check that all permission codes except VIEW are blocked for completed hanke. I didn't see it necessary to repeat this for every other authorizer …
> HAI-1150 Deny most modifying API calls for completed hanke

- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/hakemus/HakemusServiceITest.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/hakemus/HakemusService.kt
The kaivuilmoitus has rock excavation information just because it's needed to create a johtoselvityshakemus when sending the kaivuilmoitus. The identifier of the created johtoselvityshakemus is added to the kaivuilmoitus and the flag that a new johtoselvityshakemus is needed is reset, so it makes sense that the rock excavation information is also removed, since it's no longer used in anything.
Having the rock excavation information set after sending can cause problems later when creating a muutosilmoitus for the kaivuilmoitus. Muutosilmoitus form doesn't have a field for the rock excavation info, so it's always removed. This causes the 'OTHER' change being set for the muutosilmoitus, even when no changes are made on the muutosilmoitus form.
1. Create a kaivuilmoitus and ask for a …
> HAI-148 Remove rock excavation info when sending kaivuilmoitus

- email/hanke-poistetaan.mjml
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/HankeCompletionServiceITest.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/HankeCompletionScheduler.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/HankeCompletionService.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/Persistence.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/domain/Hanke.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/email/EmailEvent.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/email/EmailSenderService.kt
- services/hanke-service/src/main/resources/application.yml
- services/hanke-service/src/main/resources/email/template/hanke-poistetaan.html.mustache
- services/hanke-service/src/main/resources/email/template/hanke-poistetaan.subject.mustache
- services/hanke-service/src/main/resources/email/template/hanke-poistetaan.text.mustache
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/HankeCompletionSchedulerTest.kt
A hanke will be deleted after it has been completed and locked for 6 months. Send a reminder that the users should save any data from the hanke 5 days before the deletion. The reminder is sent to everyone with EDIT permissions on the hanke.
1. Complete some hanke like in https://github.com/City-of-Helsinki/haitaton-backend/pull/1013.
2. Change their completedAt value in the database to between 6 months ago and 5 months 25 days ago.
3. Change the deletionCron value or add @EventListener(ApplicationReadyEvent::class) to sendDeletionReminders.
4. Check from http://localhost:3003 that the reminders were sent.
> HAI-3444 Send reminder before a hanke is deleted

- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/HankeCompletionServiceITest.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/HankeCompletionService.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/Persistence.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/HankeCompletionServiceTest.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/factory/HankealueFactory.kt
When a draft hanke has end dates in every hankealue, complete it like a public hanke. If a draft hanke has no areas or some areas don't have end dates, return without doing anything with it.
1. Create a new hanke.
2. On the form, fill out only the hankealue. Add it with dates from the past.
3. Change the `haitaton.hanke.completions.cron` value or add `@Eventlistener(ApplicationReadyEvent::class)` to completeHankkeet.
4. The hanke should be completed.
There will be another PR about completing drafts without end dates (based on the last time they were updated).
> HAI-3447 Complete draft hanke with all end dates

- services/hanke-service/build.gradle.kts
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/attachment/common/AttachmentValidator.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/attachment/AttachmentValidatorTest.kt
Apache Commons is only used to get and remove filename extensions. Kotlin has built-in extensions to do the same thing. Less dependencies are better, so it's better to use the Kotlin extensions if necessary.
The Kotlin extension uses `java.io.File.name` which cleans the path part from the filename. This means a file named '/etc/var/file.txt' will be cleaned to 'file.txt'. I think this is a positive change.
> HAI Remove Apache Commons dependency

- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/HankeCompletionServiceITest.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/HankeCompletionScheduler.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/HankeCompletionService.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/Persistence.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/testdata/TestDataService.kt
- services/hanke-service/src/main/resources/application.yml
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/HankeCompletionSchedulerTest.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/factory/HankeBuilder.kt
Complete draft hanke that don't have an end date and that have been unmodified for 180 days. The hanke should also have no active applications. Send a notification when the hanke is marked as completed.
If the draft has an end date, i.e. all its areas have end dates, it will be completed like a public hanke.
1. Create a new draft hanke.
2. Set its `modifiedBy` date to 180 days in the past.
3. Run the scheduled `completeDrafts` in one of the usual ways.
> HAI-3447 Complete draft hanke

- email/hanke-paattyy.mjml
- email/hanke-poistetaan.mjml
- email/hanke-valmistunut.mjml
- email/johtoselvitys-valmis.mjml
- email/kayttaja-poistettu-hanke.mjml
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/HankeCompletionServiceITest.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/email/EmailSenderService.kt
- services/hanke-service/src/main/resources/email/template/hanke-paattyy.html.mustache
- services/hanke-service/src/main/resources/email/template/hanke-paattyy.subject.mustache
- services/hanke-service/src/main/resources/email/template/hanke-paattyy.text.mustache
- services/hanke-service/src/main/resources/email/template/hanke-poistetaan.html.mustache
- services/hanke-service/src/main/resources/email/template/hanke-poistetaan.subject.mustache
- services/hanke-service/src/main/resources/email/template/hanke-poistetaan.text.mustache
- services/hanke-service/src/main/resources/email/template/hanke-valmistunut.html.mustache
- services/hanke-service/src/main/resources/email/template/hanke-valmistunut.subject.mustache
- services/hanke-service/src/main/resources/email/template/hanke-valmistunut.text.mustache
- services/hanke-service/src/main/resources/email/template/johtoselvitys-valmis.html.mustache
- services/hanke-service/src/main/resources/email/template/johtoselvitys-valmis.text.mustache
- services/hanke-service/src/main/resources/email/template/kayttaja-poistettu-hanke.html.mustache
- services/hanke-service/src/main/resources/email/template/kayttaja-poistettu-hanke.text.mustache
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/email/EmailSenderServiceTest.kt
Add translations for recently added emails.
- Hanke ending reminder
- Hanke deletion reminder
- Hanke completed notification
Add unit tests for those emails, mainly to make sure dates are formatted correctly for each language.
Johtoselvitys completed email was missing a paragraph. It's added to the Finnish version and translations. The swedish version also had a grammatical error.
Removal from hanke email had some errors in the translations.
> HAI-3475 Add and update email translations

- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/muutosilmoitus/MuutosilmoitusServiceITest.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/taydennys/TaydennysServiceITest.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/allu/InformationRequest.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/factory/MuutosilmoitusBuilder.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/factory/TaydennysBuilder.kt
Add cable reports and placement contracts as OTHER Allu fields in kaivuilmoitus täydennys and muutosilmoitus.
1. Create a täydennys or muutosilmoitus for kaivuilmoitus that has johtoselvitys or sijoitussopimus identifiers
2. Change only johtoselvitys or sijoitussopimus
3. Send täydennys or muutosilmoitus - there should be no errors
> HAI-3549 Add cable reports and placement contracts as OTHER Allu fields in kaivuilmoitus täydennys and muutosilmoitus

- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/muutosilmoitus/MuutosilmoitusServiceITest.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/taydennys/TaydennysServiceITest.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/allu/InformationRequest.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/allu/InformationRequestTest.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/factory/TaydennysBuilder.kt
Added these changes to kaivuilmoitus täydennys and muutosilmoitus Allu messages:
* additionalInfo --> OTHER
* alueet[n].katuosoite --> POSTAL_ADDRESS
* aluuet[n].tyonTarkoitukset --> ATTACHMENT
* aluuet[n].meluhaitta --> ATTACHMENT
* aluuet[n].polyhaitta --> ATTACHMENT
* aluuet[n].tarinahaitta --> ATTACHMENT
* aluuet[n].kaistahaitta --> ATTACHMENT
* aluuet[n].kaistahaittojenPituus --> ATTACHMENT
* aluuet[n].lisatiedot--> ATTACHMENT
1. Create a kaivuilmoitus and a täydennys or muutosilmoitus for it
2. Change only some of those fields mentioned in description
3. Send to Allu - there should not be errors about sending without any changes
or other location: https://helsinkisolutionoffice.atlassian.net/wiki/spaces/HAI/pages/9217376257/Kaivuilmoituksen+t+ydennyspyynt+ja+muutosilmoitus+kentt+koko …
> HAI-3549 Add missing changes to Allu messages for täydennys and muutosilmoitus

- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/HankeCompletionServiceITest.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/HankeCompletionService.kt
- services/hanke-service/src/main/resources/application.yml
Fix a bug where the deletion reminder is sometimes sent too early on the 5th last day of the month.
This boils down to the fact that [25th Apr 2025 + 6 days - 6 months](https://www.wolframalpha.com/input?i=25th+Apr+2025+%2B+6+days++++-+6+months+++) is not the same day as [25th Apr 2025 - 6 months + 6 days](https://www.wolframalpha.com/input?i=25th+Apr+2025+-+6+months+%2B+6+days).
Fix by doing the calculation in the same order each time. Fix by doing the calculation in the same order each time. In tests, when constructing a specific deletion date, the order of operations needs to be the opposite. Add asserts to tests to make sure the deletion date is set correctly.
Also, change the env vars for some of the completion cron schedules. Some variables were reused unintentionally.
> HAI-16 Fix date handling for deletion reminders

- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/geometria/GeometriatServiceITest.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/HankeService.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/HankealueService.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/Utils.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/geometria/GeometriatService.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/hakemus/HakemusService.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/muutosilmoitus/MuutosilmoitusService.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/taydennys/TaydennysService.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/geometria/GeometriatServiceTest.kt
When GeometryService code is run through a scheduled method, namely the Allu update method, `currentUserId()` throws a NullPointerException. Replace the implicit user id with an explicit parameter.
In Allu updates, use 'Allu' as a placeholder user id.
> HAI-3564 Use explicit current user id in GeometryService

- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/HankeCompletionServiceITest.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/HankeServiceITests.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/UpdateHankeITests.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/hakemus/HakemusServiceITest.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/muutosilmoitus/MuutosilmoitusServiceITest.kt
- services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/taydennys/TaydennysServiceITest.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/Constants.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/Extensions.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/HankeCompletionService.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/Persistence.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/test/AuditLogEntryEntityAsserts.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/test/TestUtils.kt
When testing hanke deletion using month increase/decrease has caused errors when the current date is close to month's end. This PR fixes this by using a fixed date in tests instead of current date. Also, in deletion date calculation, PR uses the logic of persisting the end of the month: if a completion date is e.g. 30.4. (end of the month), then adding 6 months into it does not produce 30.10. but 31.10. (end of the month). Same goes when decreasing months from a date.
Also, change constant mockedIp to follow naming practices (all uppercase)
This fix is only for tests so it should not affect any real functionality.
> HAI-3579: Fix using months in calculating the hanke deletion date

- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/HankealueService.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/hakemus/HakemusEntity.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/hakemus/HakemusService.kt
- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/tormaystarkastelu/TormaystarkasteluTulos.kt
- services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/hakemus/HakemusServiceTest.kt
Use only regular classes as JPA Entity - not Kotlin data classes (except AuditLogEntryEntity which is an immutable entity and does not use copy to create new entities). Using data classes can cause database errors especially when used in entity collections or creating new entities by copyin existing ones.
* Check that "everything" works in the application: creating a hanke, adding johtoselvitys to it, changing areas (törmäystarkastelu changes), sending applications to Allu, making täydennyspyyntö for them in Allu, making muutosilmoitus after päätös
> HAI-3569 Use only regular classes as JPA Entity - not data classes

- services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/allu/ApplicationHistory.kt
Add new Allu application status `ANONYMIZED'. Its absense blocks handling of all Allu events since it comes already in application history fetching.
> HAI-3601 Add new allu status
