.github/pull_request_template.md
Added a pr template. Paradoxically this pr template is not visible in this pr, since it needs to be merged first.
=> HAI-29 added pr template

services/hanke-service/build.gradle.kts, services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/HankeRepositoryTests.kt, services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/HankeDao.kt, services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/HankeDaoImpl.kt, services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/Persistence.kt, services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/db/DbConfigProperties.kt, services/hanke-service/src/main/resources/application.properties, services/hanke-service/src/main/resources/db/changelog/README-db-migrations.txt, services/hanke-service/src/main/resources/db/changelog/changesets/create-initial-tables.yml, services/hanke-service/src/main/resources/db/changelog/db.changelog-master.yaml, services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/HankeGeometriaServiceImplTest.kt
The renaming of HankeEntity to OldHankeEntity was just to allow old code to continue working as before, without having to do lots of refactoring at this point.  The OldHankeEntity will of course be dropped as part of next steps.
=> HAI-202 Initial Liquibase and half-start for JPA

services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/HankeControllerITests.kt, services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/Domain.kt, services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/HankeController.kt, services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/HankeDao.kt, services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/HankeDaoImpl.kt, services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/HankeService.kt, services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/HankeServiceImpl.kt, services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/domain/Hanke.kt, services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/domain/HankeYhteystiedot.kt, services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/validation/HankeValidator.kt, services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/HankeControllerTest.kt
* HAI-248 new domain class for Contact Information and lists for Hanke for them
* Changed Controller to use PathVariable. More implementation for conta… …
* HAI-248 one test needed fixing for param change
* StartTime and endtime validation adding. 
* Hanke to its own domain class file
=> HAI-248 contact information

services/hanke-service/build.gradle.kts
trying to fix connection problemns in OpenShift/Azure environment - see https://github.com/pgjdbc/pgjdbc/issues/1868
=> HAI-307: latest PostgreSQL JDBC driver 42.2.18

services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/HankeControllerITests.kt, services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/HankeController.kt, services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/domain/Hanke.kt, services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/domain/HankeSearch.kt, services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/geometria/HankeGeometriatService.kt, services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/geometria/HankeGeometriatServiceImpl.kt, services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/HankeControllerTest.kt
* /hankkeet?geometry=true (possibly with other search parameters as well) includes geometry in results
* Added Hanke.geometriat
* Added HankeSearch.geometry
* NOTICE TODO in HankeController.getHankeList for moving search logic into service instead of controller - I think it would be better in service (checking what kind of search it is and returning results accordingly).
=> Hai 430 hankkeet kartalla rajapinta

services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/HankeControllerITests.kt, services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/HankeServiceITests.kt, services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/HankeController.kt, services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/HankeService.kt, services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/HankeServiceImpl.kt, services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/HankeControllerTest.kt
…service layer
Test initializations changed accordingly. Some IDE warnings fixed at the same time: var -> val and some unnecessary object declarations removed
=> Hai-469 refactoring controller

scripts/nginx/nginx.conf
Fixes POST request HTTP 502 bad gateway error.
https://www.getpagespeed.com/server-setup/nginx/tuning-proxy_buffer_size-in-nginx
=> HAI-481: Update nginx reverse proxy settings

azure-pipelines.yml
removed feature branches from triggering builds
=> Azure pipelines fix

services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/HankeControllerITests.kt, services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/geometria/HankeGeometriatServiceImplITest.kt, services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/HankeController.kt, services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/domain/Hanke.kt, services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/geometria/HankeGeometriat.kt, services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/geometria/HankeGeometriatController.kt, services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/geometria/HankeGeometriatService.kt, services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/geometria/HankeGeometriatServiceImpl.kt
Plus some minor fixes on places where IDE had some complains.
=> HAI-646: include hankeTunnus in returned Hanke GeoJson Feature.properties

services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/HankeControllerITests.kt, services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/HankeServiceITests.kt, services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/IntegrationTestConfiguration.kt, services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/geometria/HankeGeometriatServiceImplITest.kt, services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/Configuration.kt, services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/HankeController.kt, services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/HankeService.kt, services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/HankeServiceImpl.kt, services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/Persistence.kt, services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/domain/Hanke.kt, services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/domain/HankeTilat.kt, services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/domain/HankeYhteystieto.kt, services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/geometria/HankeGeometriatServiceImpl.kt, services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/validation/HankeValidator.kt, services/hanke-service/src/main/resources/db/changelog/changesets/add-hanke-flag-fields.yml, services/hanke-service/src/main/resources/db/changelog/db.changelog-master.yaml, services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/geometria/HankeGeometriatServiceImplTest.kt
Added state flags to Hanke.
Note, different flags are updated in different way; geometry flag is updated whenever geometry is modified (its service methods called), while certain other flags are simply recalculated when the Hanke is loaded from its service.
PR contains also some notes on possible bugs (to be checked, fixed and tested separately), and refactored certain methods around to make the logic checks clearer (and less likely to have mismatching code implementation in different places).
Integration tests finally go through, too.
=> Hai 583 tila liput backendista

.env.local, services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/tormaystarkastelu/TormaystarkasteluEnum.kt, services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/tormaystarkastelu/TormaystarkasteluPaikkaServiceImpl.kt, services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/tormaystarkastelu/TormaystarkasteluPaikkaServiceImplTest.kt
Tram classification implementer pretty much the same than cycling.
=> Hai-666 tram traffic classification

services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/IntegrationTestConfiguration.kt, services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/tormaystarkastelu/TormaystarkasteluControllerITests.kt, services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/Configuration.kt, services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/Domain.kt, services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/domain/Hanke.kt, services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/tormaystarkastelu/TormaystarkasteluController.kt, services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/tormaystarkastelu/TormaystarkasteluLaskentaService.kt, services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/tormaystarkastelu/TormaystarkasteluLaskentaServiceImpl.kt, services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/tormaystarkastelu/TormaystarkasteluTulos.kt
=> Hai-688 tormays api

services/auth-service/realms/haitaton-realm-with-users.json, services/auth-service/realms/haitaton-realm.json, services/auth-service/realms/haitaton-users-0.json
Keycloakissa asetukset oletuksena näin:
=> HAI-761: rekisteröityminen päälle

services/auth-service/realms/haitaton-realm-with-users.json, services/auth-service/realms/haitaton-realm.json, services/auth-service/realms/haitaton-users-0.json
Enable PKCE (S256) to "haitaton-ui"-client and add two test users.
tiinatestaaja (haitaton-user)
timotestaaja (default)
=> HAI-768: Enable PKCE and add test users

services/auth-service/realms/haitaton-realm-with-users.json, services/auth-service/realms/haitaton-realm.json, services/auth-service/realms/haitaton-users-0.json, services/auth-service/themes/haitaton/login/messages/messages_en.properties
Keycloakiin tekstiresurssimuutoksia koskien käyttöehtoja ja puuttuneita suomennoksia. 
Plus Keycloakin asetuksiin valmiiksi päälle alla mainittu "Terms and Conditions" Default Action.
Rekisteröidy Haitattoman käyttäjäksi. Keycloakissa pitää olla asetettu "Terms and Conditions" Default Actioniksi Authentication --> Required Actions -kohdassa
=> HAI-869: käyttöehdot + muutamia muita suomennoksia

services/auth-service/realms/haitaton-realm-with-users.json, services/auth-service/realms/haitaton-realm.json
=> email-server pois

.github/workflows/auth-service-main.yml, .github/workflows/hanke-service-main.yml
GitHub workflows for `main` branch for hanke-service and auth-service. Are identical to `dev` branch workflows except they trigger by changes in `main` branch instead of `dev` and they build a Docker image with tag/version `main` (instead of `dev`).
=> HAI-815: github workflows for main branch

services/auth-service/themes/haitaton/login/resources/css/haitaton.css, services/auth-service/themes/haitaton/login/template.ftl
=> Hai 997:Taustakuvan levitys koko ruudulle+"Haitaton Beta" teksti loginiin

docker-compose-e2e.yml
Use ready-built docker images for hanke-service, auth-service and ui
=> E2E docker-compose.yml

services/hanke-service/src/main/resources/application.properties, services/hanke-service/src/main/resources/db/changelog/README-db-migrations.txt, services/hanke-service/src/main/resources/db/changelog/changesets/add-tormaystarkastelu-results.yml, services/hanke-service/src/main/resources/db/changelog/changesets/create-hankeyhteystieto-table.yml, services/hanke-service/src/main/resources/db/changelog/changesets/create-initial-hanke-table.yml, services/hanke-service/src/main/resources/db/changelog/changesets/create-log-tables-for-personaldata.yml
TODO/cleanups step 1: db-migration files.
HAI-946
n/a
=> HAI-946 db migration cleanups

services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/HankeServiceImpl.kt, services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/domain/Hanke.kt
Step 2: main Hanke code cleanups
HAI-946
n/a
=> HAI-946 main Hanke code cleanups

services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/tormaystarkastelu/TormaystarkasteluDaoImpl.kt, services/hanke-service/src/manualTest/kotlin/fi/hel/haitaton/hanke/tormaystarkastelu/TormaystarkasteluLaskentaServiceImplManualTest.kt, services/hanke-service/src/manualTest/resources/fi/hel/haitaton/hanke/tormaystarkastelu/hankeGeometriat.json
Törmäystarkastelun SQL-kyselyiden muutos, joka pienessä service-tason suorituskykytestissä näyttäisi nopeuttavan n. 50 %.
=> Muutettu törmäystarkastelun SQL-kyselyitä nopeammiksi

services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/tormaystarkastelu/TormaystarkasteluDaoImpl.kt, services/hanke-service/src/manualTest/kotlin/fi/hel/haitaton/hanke/tormaystarkastelu/TormaystarkasteluLaskentaServiceImplManualTest.kt, services/hanke-service/src/manualTest/resources/fi/hel/haitaton/hanke/tormaystarkastelu/hankeGeometriat.json
=> Muutettu törmäystarkastelun SQL-kyselyitä nopeammiksi (#161)

services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/Application.kt, services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/domain/PublicHanke.kt, services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/security/AccessRules.kt
Add endpoint for getting public information (non-sensitive data available to everyone) of hankkeet.
=> Add public-hankkeet endpoint

services/hanke-service/src/main/resources/db/changelog/changesets/002-rename-column-permissions-permissionCode.yml, services/hanke-service/src/main/resources/db/changelog/db.changelog-master.yaml
Rename column permissionCode to lowercase for consistency
=> Rename permissionCode to lowercase for consistency

services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/domain/PublicHanke.kt
Move featureCollection inside geometriat, include public information of HankeGeometriat in the response.
=> Change public-hankkeet api response schema

services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/HankeControllerITests.kt, services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/IntegrationTestConfiguration.kt, services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/security/HankeControllerSecurityTests.kt, services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/Configuration.kt, services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/HankeController.kt, services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/HankeService.kt, services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/HankeServiceImpl.kt, services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/permissions/Permissions.kt, services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/HankeControllerTest.kt, services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/permissions/PermissionsTest.kt
Use permissions on hanke creation and listing api
=> Hai 1027 use permissions on hanke apis

services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/tormaystarkastelu/TormaystarkasteluControllerITests.kt, services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/ControllerExceptionHandler.kt, services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/Domain.kt, services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/tormaystarkastelu/TormaystarkasteluLaskentaServiceImpl.kt
Allow tormaystarkastelu to be calculated multiple times.
=> Dont check if tormaystarkastelu is already calculated

services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/domain/PublicHanke.kt
=> Add liikennehaittaindeksi, tormaystarkasteluTulos to /public-hankkeet

services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/tormaystarkastelu/TormaystarkasteluDaoImpl.kt
Use `ST_Intersects` instead of `ST_Overlaps OR ST_Within(a,b) OR ST_Within(b,a)`
Further improves #161
=> Optimize SQL used in törmäystarkastelu 

services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/domain/PublicHanke.kt
Add nimi and kuvaus to /public-hankkeet
=> Add nimi and kuvaus to /public-hankkeet

services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/Application.kt, services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/HankeController.kt, services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/HankeService.kt, services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/HankeServiceImpl.kt, services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/permissions/Permissions.kt, services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/security/AccessRules.kt, services/hanke-service/src/main/resources/db/changelog/changesets/004-add-on-delete-to-hanke-fkeys.yml, services/hanke-service/src/main/resources/db/changelog/changesets/005-add-delete-permission-to-creator.sql, services/hanke-service/src/main/resources/db/changelog/db.changelog-master.yaml
Add possibility to delete Hanke
=> Add possibility to delete Hanke

services/hanke-service/build.gradle.kts, services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/logging/AccessLogConfiguration.kt, services/hanke-service/src/main/resources/logback-access.xml, services/hanke-service/src/main/resources/logback.xml
=> Add logstash-logback-encoder and logback-access

services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/security/HankeControllerSecurityTests.kt, services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/security/HankeGeometriaControllerSecurityTests.kt, services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/security/AccessRules.kt
=> Remove haitaton-user role check

services/hanke-service/build.gradle.kts, services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/application/CableReportServiceAlluITests.kt, services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/application/AlluCommonDomain.kt, services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/application/ApplicationHistory.kt, services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/application/CableReportApplication.kt, services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/application/CableReportService.kt, services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/application/CableReportServiceAllu.kt, services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/application/InformationRequest.kt
Solution to sending cable report applications to Allu. Extracting common logic between different application types left as future exercise.
=> Allu client for cable reports applications

services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/security/OrganisaatioControllerSecurityTests.kt, services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/security/AccessRules.kt
Allow anonymous access to actuator endpoints 
=> Allow anonymous access to actuator endpoints 

services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/Persistence.kt, services/hanke-service/src/main/resources/db/changelog/changesets/008-suunnitteluvaihe-enumtype-string.sql, services/hanke-service/src/main/resources/db/changelog/db.changelog-master.yaml
For consistency and extensibility
=> Add @Enumerated(EnumTyp.STRING) to suunnitteluVaihe

services/hanke-service/build.gradle.kts, services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/application/Application.kt, services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/application/ApplicationController.kt, services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/application/ApplicationService.kt
=> Jannen ehdotuksia

services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/application/CableReportServiceAllu.kt
=> Fix getDecisionPDF

docker-compose.yml, scripts/nginx/nginx.conf, services/hanke-service/build.gradle.kts, services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/ResourceServerConfig.kt, services/hanke-service/src/main/resources/application.properties
=> Use tunnistamo, disable auth-service and auth-db

services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/Application.kt
=> /hakemukset ja /hakemukset/** tulisi lisätä cors sääntöjen piiriin

.github/workflows/hanke-service-feature.yml, services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/StatusController.kt
Log errors when status endpoint fails.
=> HAI Log errors when status endpoint fails.

.github/workflows/hanke-service-dev.yml, .github/workflows/hanke-service-main.yml
Checkout all branches for automated formatting in all build scripts.
This is needed to make spotless work on Github Actions.
=> HAI-1222 Checkout all branches for automated formatting

scripts/gis-material-update/README.md, scripts/gis-material-update/config.yaml, scripts/gis-material-update/fetch/fetch_data.sh, scripts/gis-material-update/process/modules/ylre_katuosat.py, scripts/gis-material-update/process/process_data.py, scripts/gis-material-update/process/test/test_ylre_katuosat.py
Implementation of processing YLRE parts to Haitaton tormays-polygons.
https://helsinkisolutionoffice.atlassian.net/browse/HAI-1290
Prerequisite: fetch `ylre_katuosat` source materials, as per instructions in the README
Go to directory: haitaton-backend/scripts/gis-material-update/process
* (create and) activate Python virtual environment
* run `python -m unittest discover -v`
-
=> HAI-1290/ylre parts gis material

scripts/gis-material-update/README.md, scripts/gis-material-update/config.yaml, scripts/gis-material-update/fetch/fetch_data.sh, scripts/gis-material-update/process/modules/ylre_katualueet.py, scripts/gis-material-update/process/process_data.py, scripts/gis-material-update/process/test/test_ylre_katualueet.py
Implement processing of YLRE classes GIS material.
[HAI-1291](https://helsinkisolutionoffice.atlassian.net/browse/HAI-1291)
Prerequisite: fetch `ylre_katualueet` source materials, as per instructions in the README
Go to directory: haitaton-backend/scripts/gis-material-update/process
* (create and) activate Python virtual environment
* run `python -m unittest discover -v`
-
=> HAI-1291/YLRE classes gis material preparation

scripts/gis-material-update/process/modules/hsl.py
Data types were changed to `int32` for attributes:
* `rush_hour` - previously `double precision`
* `direction_id` - previously `int64`
https://helsinkisolutionoffice.atlassian.net/browse/HAI-1381
Run data fetch and data process as instructed here: https://github.com/City-of-Helsinki/haitaton-backend/blob/dev/scripts/gis-material-update/README.md
```
docker-compose run --rm gis-fetch hsl hki
docker-compose run --rm gis-process hsl
```
Verify by checking output result (at directory `gis-material-update` ):
```
ogrinfo haitaton-gis-output/tormays_buses_polys.gpkg tormays_buses_polys -so | tail -6
FID Column = fid
Geometry Column = geom
route_id: String (0.0)
direction_id: Integer (0.0)
rush_hour: Integer (0.0)
trunk: String (0.0)
```
or …
=> HSL tormays polygon data types fixed

services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/HankeServiceITests.kt, services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/allu/ApplicationServiceITest.kt, services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/test/TestUtils.kt
Fix tests so that they work also in the year 2023.
There are some tests that have hardcoded years in excepted results. These are failing now that the year has changed. Fix them to use the next year from the current one as the excepted year.
=> HAI Fix tests for 2023

services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/domain/Hanke.kt, services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/domain/Hankealue.kt
Add ignore unknown properties to hankealue.
An unknown feature-field is stopping us from creating a hanke.
=> HAI Add ignore unknown properties to hankealue

scripts/gis-material-update/README.md, scripts/gis-material-update/config.yaml, scripts/gis-material-update/process/modules/tram_lines.py, scripts/gis-material-update/process/process_data.py, scripts/gis-material-update/process/test/test_tram_lines.py
Implemented tram lines (based on public transport schedules) tormays-material processing.
[HAI-1480](https://helsinkisolutionoffice.atlassian.net/browse/HAI-1480)
See README for preparing containers (building containers, copying files). After these initial steps, run fetch and process as separate docker runs. See exact details from README:
```
docker-compose run --rm gis-fetch hsl
docker-compose run --rm gis-process tram_lines
```
Results are in haitaton-gis-output directory.
See unit test instructions and Python virtual environment setup instructions in README, if required.
[HAI-1480]: https://helsinkisolutionoffice.atlassian.net/browse/HAI-1480?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoi …
=> HAI 1480 tram lines gis material

services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/email/EmailSenderService.kt
=> HAI-1525 Remove commented test code

services/hanke-service/build.gradle.kts, services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/HankeServiceITests.kt, services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/IntegrationTestConfiguration.kt, services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/application/ApplicationServiceITest.kt, services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/attachment/AttachmentServiceITests.kt, services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/security/HankeControllerSecurityTests.kt, services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/application/ApplicationService.kt, services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/email/EmailSenderService.kt, services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/security/OAuth2ResourceServerSecurityConfiguration.kt, services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/HankeControllerTest.kt
WebSecurityConfigurerAdapter has been deprecated, so replace that with a configuration class defining a SecurityFilterChain @Bean. Define a similar bean in IntegrationTestConfiguration.
=> HAI-1559 Upgrade to Spring Boot 2.7

services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/HankeControllerITests.kt, services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/HankeServiceITests.kt, services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/IntegrationTestConfiguration.kt, services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/allu/CableReportServiceAlluITests.kt, services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/application/ApplicationControllerITest.kt, services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/application/ApplicationServiceITest.kt, services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/attachment/hanke/HankeAttachmentControllerITests.kt, services/hanke-service/src/integrationTest/resources/application-test.properties, services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/ControllerExceptionHandler.kt, services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/HankeController.kt, services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/allu/AlluCommonDomain.kt, services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/allu/CableReportService.kt, services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/allu/CableReportServiceAllu.kt, services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/application/ApplicationData.kt, services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/application/ApplicationService.kt, services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/application/CustomerWithContacts.kt, services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/attachment/application/ApplicationAttachmentService.kt, services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/attachment/hanke/HankeAttachmentController.kt, services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/configuration/Configuration.kt, services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/configuration/FeatureFlags.kt, services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/validation/ApplicationValidator.kt, services/hanke-service/src/main/resources/application.properties, services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/HankeControllerTest.kt, services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/application/ApplicationServiceTest.kt
=> Dev to main

services/hanke-service/Dockerfile, services/hanke-service/Dockerfile-local
=> Change dockerfile to not use root user

services/hanke-service/Dockerfile, services/hanke-service/Dockerfile-local
Revert the previous change as it does not work in azure devops.
=> HAI-1743 Revert Dockerfile change

services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/configuration/Configuration.kt, services/hanke-service/src/main/resources/application.properties
Increase decision limit to 100MB
I couldn't test this, because Allu test environment gave errors with a large decision.
=> HAI-1613 Increase decision limit to 100MB

services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/attachment/common/AttachmentValidator.kt, services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/attachment/AttachmentValidatorTest.kt
This was merged into main by accident. Re-opening to merge in dev.
=> HAI-1737 Accept filenames in uppercase

azure-pipelines-build-keycloak-devtest.yml
=> Devtest keycloak pipeline YAML stub file

services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/attachment/application/ApplicationAttachmentService.kt, services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/attachment/hanke/HankeAttachmentService.kt
Write to log at the beginning of when adding an attachment starts, and include the size of the attachment in that log. This will help us debug e.g. situations where the antivirus scan fails.
=> HAI Improve logging in adding attachments

services/hanke-service/build.gradle.kts, services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/HankeRepositoryITests.kt, services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/SpringDocITest.kt
Springdoc needs to be upgraded to v2 to work with Spring Boot 3.x.
Open the Swagger UI and see if it's working.
=> HAI-1560 Fix OpenAPI docs and Swagger-UI

services/hanke-service/Dockerfile-platta
Platta requires a new Dockerfile to build the application and create the runtime image in the same file.
=> HAI-1843 Add new Dockerfile for platta

azure-pipelines-build-hanke-service-devtest.yml
Trigger branch name fix from main to dev. Expected functionality is that a code change to dev should automatically trigger the pipeline and deploy to dev and test.
=> HAI-1843 Trigger branch name fix

services/hanke-service/build.gradle.kts
Add a variable that ties the Kotlin-plugins to the same version.
=> HAI-1516 Upgrade kotlin to 1.9.10

.github/dependabot.yml, services/hanke-service/build.gradle.kts
Add Dependabot config
Needs to be in main-branch to be tested. Seems to work when already pushed there.
=> HAI-1516 Add Dependabot config

email/kayttaja-lisatty-hakemus.mjml, services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/application/ApplicationServiceITest.kt, services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/email/EmailSenderServiceITest.kt, services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/email/EmailSenderServicePropertiesITest.kt, services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/permissions/HankeKayttajaServiceITest.kt, services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/Utils.kt, services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/application/ApplicationData.kt, services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/application/ApplicationService.kt, services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/application/validation/CableReportErrorValidation.kt, services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/application/validation/CableReportMissingValidation.kt, services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/domain/UserContact.kt, services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/email/EmailSenderService.kt, services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/permissions/HankeKayttajaService.kt, services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/permissions/KayttajaTunniste.kt, services/hanke-service/src/main/resources/email/template/kayttaja-lisatty-hakemus.html.mustache, services/hanke-service/src/main/resources/email/template/kayttaja-lisatty-hakemus.text.mustache, services/hanke-service/src/main/resources/email/template/kayttaja-lisatty-hanke.text.mustache, services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/UtilsKtTest.kt, services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/application/ApplicationServiceTest.kt, services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/domain/UserContactTest.kt, services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/factory/AlluDataFactory.kt, services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/factory/HankeFactory.kt, services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/factory/HankeKayttajaFactory.kt
Send hanke invitations to new hanke contacts and send application notification to every contact. Does not send messages to the inviter himself.
Additional: Fix email text versions so that variables are not converted to html escaped characters.
Create johtoselvitys with contacts. Send application. Check localhost:3003 that emails are sent correctly, i.e. new contacts receive hanke invitation, all contacts receive application notification.
=> HAI-1526 Send application invitations

email/common/attributes.mjml, services/hanke-service/src/main/resources/email/template/kayttaja-lisatty-hakemus.html.mustache, services/hanke-service/src/main/resources/email/template/kayttaja-lisatty-hanke.html.mustache
Additional commit to HAI-1526. Increase email text line height according to figma.
=> HAI-1526 Increase email text line height according to figma

services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/security/OAuth2ResourceServerSecurityConfiguration.kt
Authorization was missing an annotation so it wasn't running.
Authentication was working the whole time.
=> HAI Hotfix for authorization

services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/security/UserIdLoggingFilter.kt, services/hanke-service/src/main/resources/logback-access.xml, services/hanke-service/src/main/resources/logback.xml
It has proven itself valuable to have the user's id present in all logs. Add them to both application and access logs.
Do something and check logs. Also try listing public hankkeet while logged out.
=> HAI Add userId to all logs

services/hanke-service/build.gradle.kts, services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/HankeMapper.kt, services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/HankeServiceImpl.kt, services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/HankealueEntity.kt, services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/HankealueService.kt, services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/Persistence.kt, services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/Utils.kt, services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/application/Application.kt, services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/application/ApplicationService.kt, services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/configuration/Configuration.kt, services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/domain/BaseHanke.kt, services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/domain/HankeYhteystieto.kt, services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/domain/HasId.kt, services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/domain/SavedHankealue.kt, services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/geometria/Geometriat.kt, services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/UtilsKtTest.kt, services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/factory/HankeFactory.kt, services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/factory/HankealueFactory.kt
Separate hankealue stuff from HankeService to a new service
Refactoring, nothing should change.
=> HAI-2039 Seperate hankealue stuff from HankeService to a new service

docker-compose.yml, services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/HankeControllerITests.kt, services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/HankeServiceITests.kt, services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/Constants.kt, services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/HankealueEntity.kt, services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/HankealueService.kt, services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/domain/BaseHanke.kt, services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/domain/CreateHankeRequest.kt, services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/domain/PublicHanke.kt, services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/domain/SavedHankealue.kt, services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/validation/HankePublicValidator.kt, services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/validation/HankeValidator.kt, services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/validation/Validators.kt, services/hanke-service/src/main/resources/db/changelog/changesets/055-make-nimi-mandatory-in-hankealue.yml, services/hanke-service/src/main/resources/db/changelog/db.changelog-master.yaml, services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/domain/HankeTest.kt, services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/factory/HankeFactory.kt, services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/factory/HankealueFactory.kt, services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/tormaystarkastelu/TormaystarkasteluLaskentaServiceTest.kt, services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/validation/HankePublicValidatorTest.kt, services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/validation/HankeValidatorTest.kt, services/hanke-service/src/test/resources/sql/senaatintorin-hanke.sql
Hankealue has to have a non-null, non-empty name.
There are unit tests in place for the change. 
or other location:  Added this new mandatory info on https://helsinkisolutionoffice.atlassian.net/wiki/spaces/HAI/pages/8184234008/Hankkeiden+tilat#Pakolliset-kent%C3%A4t
=> HAI-2007 Make Hankealue name mandatory

docker-compose.yml
See https://github.com/City-of-Helsinki/haitaton-ui/pull/425
=> HAI-1776 Set LOGIN_SERVER for local ui

services/hanke-service/src/main/resources/email/template/johtoselvitys-valmis.html.mustache, services/hanke-service/src/main/resources/email/template/kayttaja-lisatty-hakemus.html.mustache, services/hanke-service/src/main/resources/email/template/kayttaja-lisatty-hanke.html.mustache
MJML has been upgraded and the Gradle plugin we use always uses the latest stable version of it. The latest version had minor changes in how the HTML is rendered, and those are reflected in our compiled templates. Add these changes as a separate commit, so they don't have to be included in an unrelated commit.
=> HAI Add template changes from MJML upgrade

services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/HankeServiceITests.kt, services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/domain/Yhteyshenkilo.kt, services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/factory/HankeYhteyshenkiloFactory.kt
=> HAI Fix for email field in yhteyshenkilo

services/hanke-service/src/integrationTest/resources/clear-db.sql, services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/hakemus/HakemusyhteystietoEntity.kt, services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/permissions/HankeKayttaja.kt, services/hanke-service/src/main/resources/db/changelog/changesets/070-create-hakemusyhteystieto-tables.sql, services/hanke-service/src/main/resources/db/changelog/db.changelog-master.yaml
Create tables for application customers and contacts. Also, create entities for them.
=> HAI-2189 Create tables for application customers and contacts

services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/allu/ApplicationHistory.kt
=> Merge main back to dev

services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/hakemus/HakemusServiceITest.kt, services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/HankeService.kt, services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/HankealueService.kt, services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/application/ApplicationService.kt, services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/hakemus/HakemusResponse.kt, services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/hakemus/HakemusService.kt, services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/hakemus/HakemusUpdateRequest.kt, services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/hakemus/Hakemusyhteystieto.kt, services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/hakemus/HakemusyhteystietoEntity.kt, services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/factory/HakemusBuilder.kt, services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/factory/HakemusFactory.kt, services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/factory/HakemusResponseFactory.kt, services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/factory/HakemusUpdateRequestFactory.kt, services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/logging/DisclosureLogServiceTest.kt
HakemusService.updateHakemus() implementation
JUnit integration tests are currently only way to test the implementation.
=> HAI-2253 Implementation of HakemusService.updateHakemus

services/hanke-service/src/main/resources/email/template/kayttaja-lisatty-hakemus.text.mustache
When going through the email texts for translations I came by this static application identifier in an English message template.
=> HAI-2367 Removed a static application identifier

services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/hakemus/HakemusMigrationServiceITest.kt, services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/hakemus/HakemusMigrationService.kt, services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/hakemus/HakemusMigrationServiceTest.kt
Add code for migrating a single hanke.
Still needs:
- Logging
- Starting the migration at startup or with a timer
Until there's a trigger, this can only be tested with integration and unit tests-
I'll add logging in a separate PR since this is getting very long.
The trigger for running the migration, which loads all hanke IDs and migrates them one-by-one will be added later.
=> HAI-2231 Add code for migrating a single hanke

services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/hakemus/HakemusServiceITest.kt, services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/application/ApplicationEntity.kt, services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/hakemus/HakemusService.kt, services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/factory/HakemusFactory.kt, services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/hakemus/HakemusServiceTest.kt
Get the recipients from 'kortisto' instead of applicationdata
This can only be tested with unit/integration tests
=> HAI-2452 Get the recipients from 'kortisto' instead of applicationdata

services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/tormaystarkastelu/TormaystarkasteluTormaysService.kt
Fixed bug in new törmäystarkastelu data where two values had a slightly different spelling in the database.
=> HAI-2495 Bug fix for törmäystarkastelu katuluokka

services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/hakemus/HakemusServiceITest.kt, services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/application/ApplicationEntity.kt
Bugfix for sending duplicate emails to new users added to an application
=> HAI-2456 bugfix for sending duplicate emails to new users added to an application

email/kayttaja-lisatty-hakemus.mjml, services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/email/EmailSenderService.kt, services/hanke-service/src/main/resources/email/template/kayttaja-lisatty-hakemus.html.mustache, services/hanke-service/src/main/resources/email/template/kayttaja-lisatty-hakemus.text.mustache, services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/email/EmailSenderServiceTest.kt
Added last missing translations for emails
=> HAI-2456 Added last missing translations

services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/hakemus/HakemusServiceITest.kt, services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/hakemus/HakemusService.kt, services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/factory/HakemusFactory.kt, services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/factory/HakemusUpdateRequestFactory.kt
Set generated project name when application name is updated
=> HAI-2487 Set generated project name when application name is updated

azure-pipelines-build-hanke-service-stageprod.yml
Azure pipeline for stageprod build was deleted at some point. Now it is restored.
=> Restored deleted azure pipeline file

services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/HankeServiceITests.kt, services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/hakemus/HakemusServiceITest.kt, services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/permissions/HankekayttajaDeleteServiceITest.kt, services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/HankeService.kt, services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/application/ApplicationData.kt, services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/attachment/application/ApplicationAttachmentService.kt, services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/hakemus/HakemusService.kt, services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/permissions/HankekayttajaDeleteService.kt, services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/attachment/common/MockFileClient.kt, services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/attachment/common/MockFileClientExtension.kt, services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/factory/HakemusUpdateRequestFactory.kt
=> Haitaton HAI.01.9

services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/hakemus/HakemusServiceITest.kt, services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/HankealueService.kt, services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/application/ApplicationData.kt, services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/hakemus/Hakemus.kt, services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/hakemus/HakemusResponse.kt, services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/hakemus/HakemusService.kt, services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/hakemus/HakemusUpdateRequest.kt, services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/hakemus/Hakemusalue.kt, services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/factory/ApplicationFactory.kt, services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/factory/HakemusBuilder.kt, services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/factory/HakemusFactory.kt, services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/factory/HakemusResponseFactory.kt, services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/factory/HakemusUpdateRequestFactory.kt, services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/hakemus/HakemusPdfServiceTest.kt
Rename ApplicationArea to Hakemusalue and move it under the hakemus package.
=> HAI-2310 Move and rename ApplicationArea

services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/HankeServiceITests.kt, services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/gdpr/GdprServiceITest.kt, services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/hakemus/HakemusServiceITest.kt, services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/Persistence.kt, services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/hakemus/ApplicationRepository.kt, services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/hakemus/HakemusEntity.kt, services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/hakemus/HakemusService.kt, services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/hakemus/HakemusUpdateRequest.kt, services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/hakemus/HakemusyhteystietoEntity.kt, services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/hakemus/HankkeenHakemuksetResponse.kt, services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/factory/ApplicationAttachmentFactory.kt, services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/factory/ApplicationFactory.kt, services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/factory/HakemusBuilder.kt, services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/factory/HakemusFactory.kt, services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/factory/HakemusyhteystietoFactory.kt, services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/factory/HankeKayttajaFactory.kt, services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/hakemus/HakemusServiceTest.kt, services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/hakemus/HakemusUpdateRequestTest.kt
Rename application entity to hakemus entity.
=> HAI-2310 Rename application entity to hakemus entity

services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/HankeServiceITests.kt, services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/gdpr/GdprServiceITest.kt, services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/hakemus/HakemusControllerITest.kt, services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/hakemus/HakemusServiceITest.kt, services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/permissions/HankeKayttajaServiceITest.kt, services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/testdata/TestDataServiceITest.kt, services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/attachment/application/ApplicationAttachmentService.kt, services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/hakemus/AlluUpdateService.kt, services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/hakemus/ApplicationDeletionResultDto.kt, services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/hakemus/HakemusAuthorizer.kt, services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/hakemus/HakemusController.kt, services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/hakemus/HakemusDeletionResultDto.kt, services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/hakemus/HakemusEntity.kt, services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/hakemus/HakemusEntityData.kt, services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/hakemus/HakemusRepository.kt, services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/hakemus/HakemusService.kt, services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/hakemus/HakemusUpdateRequest.kt, services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/hakemus/HankkeenHakemuksetResponse.kt, services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/testdata/TestDataService.kt, services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/factory/ApplicationFactory.kt, services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/factory/HakemusBuilder.kt, services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/factory/HakemusFactory.kt, services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/factory/HankeKayttajaFactory.kt, services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/hakemus/AlluUpdateServiceTest.kt, services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/hakemus/HakemusServiceTest.kt, services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/hakemus/HakemusUpdateRequestTest.kt
Rename ApplicationData to HakemusEntityData.
Rename ApplicationRepository to HakemusRepository.
=> HAI-2310 Rename ApplicationRepository and ApplicationData

services/hanke-service/src/main/resources/application.yml
There's a problem with SonarCloud in CI, and this comment was moved when it started. Let's try to move it to another position to see if it changes anything.
=> HAI Move a comment if application.yml

services/hanke-service/build.gradle.kts
HAI Bump Spring Boot to 3.1.12
=> HAI Bump Spring Boot to 3.1.12

services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/allu/CableReportServiceITests.kt, services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/hakemus/HakemusServiceITest.kt, services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/hakemus/HakemusService.kt, services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/factory/HakemusBuilder.kt
Add tests for sending kaivuilmoitus. 
=> HAI-2418 Add tests for sending kaivuilmoitus

services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/hakemus/UpdateHakemusITest.kt, services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/factory/HakemusFactory.kt
Use `@ParametrizedTest` to combine tests in hakemus update tests where the only difference between the tests is the type of application tested.
=> HAI-2749 Combine identical tests in updating hakemus

services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/pdf/HaittojenhallintasuunnitelmaPdfEncoder.kt, services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/pdf/PdfHelpers.kt, services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/pdf/WmsConfiguration.kt, services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/pdf/HaittojenhallintasuunnitelmaPdfEncoderTest.kt, services/hanke-service/src/test/resources/fi/hel/haitaton/hanke/pdf-test-data/hankealueet.json
Replay of #925, since that went to the wrong branch.
=> HAI-3355 Add haittojenhallintasuunnitelma from hankealue to the PDF

services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/profiili/ProfiiliControllerITest.kt, services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/profiili/ProfiiliController.kt
Add missing exception handling for NameClaimNotFound
=> HAI Add missing exception handling for NameClaimNotFound

services/hanke-service/src/main/resources/db/changelog/changesets/103-replace-function-check-kaivuilmoitus-changes-to-fix-toiminnallinen-kunto-and-tyo-valmis-dates.sql, services/hanke-service/src/main/resources/db/changelog/db.changelog-master.yaml
Excavation notice history fix of "toiminnallinen kunto" and "tyo valmis" date handling.
=> Excavation notice history fix of toiminnallinen kunto and tyo valmis dates

email/hanke-valmistunut.mjml, services/hanke-service/src/integrationTest/kotlin/fi/hel/haitaton/hanke/HankeCompletionServiceITest.kt, services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/HankeCompletionService.kt, services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/email/EmailEvent.kt, services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/email/EmailSenderService.kt, services/hanke-service/src/main/resources/email/template/hanke-valmistunut.html.mustache, services/hanke-service/src/main/resources/email/template/hanke-valmistunut.subject.mustache, services/hanke-service/src/main/resources/email/template/hanke-valmistunut.text.mustache
Send an email to all hanke users with EDIT permissions.
Complete a hanke, get email.
=> HAI-3443 Send email notifications when a hanke completes

services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/allu/ApplicationKind.kt
Add missing GEO_HEATING Allu application type.
=> HAI-3591 Add missing GEO_HEATING Allu application type

.sdkmanrc, README.md, services/hanke-service/Dockerfile-local, services/hanke-service/Dockerfile-platta, services/hanke-service/build.gradle.kts, services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/pdf/Fonts.kt, services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/pdf/HaittojenhallintasuunnitelmaPdfEncoder.kt, services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/pdf/JohtoselvityshakemusPdfEncoder.kt, services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/pdf/KaivuilmoitusPdfEncoder.kt, services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/pdf/NuisanceColor.kt, services/hanke-service/src/main/kotlin/fi/hel/haitaton/hanke/pdf/PdfHelpers.kt, services/hanke-service/src/main/resources/email/template/hanke-paattyy.html.mustache, services/hanke-service/src/main/resources/email/template/hanke-poistetaan.html.mustache, services/hanke-service/src/main/resources/email/template/hanke-valmistunut.html.mustache, services/hanke-service/src/main/resources/email/template/johtoselvitys-valmis.html.mustache, services/hanke-service/src/main/resources/email/template/kaivuilmoitus-paatos.html.mustache, services/hanke-service/src/main/resources/email/template/kayttaja-lisatty-hakemus.html.mustache, services/hanke-service/src/main/resources/email/template/kayttaja-lisatty-hanke.html.mustache, services/hanke-service/src/main/resources/email/template/kayttaja-poistettu-hanke.html.mustache, services/hanke-service/src/main/resources/email/template/kayttooikeustason-muutos.html.mustache, services/hanke-service/src/main/resources/email/template/taydennyspyynto-peruttu.html.mustache, services/hanke-service/src/main/resources/email/template/taydennyspyynto.html.mustache, services/hanke-service/src/test/kotlin/fi/hel/haitaton/hanke/pdf/PdfTestUtil.kt
Updated Java version from 17 to 21.
This was needed for the latest OpenPDF version which did not compile with Java 17.
=> Java 17 -> Java 21
